### ISSUE TITLE
[BUG] Flaky org.opensearch.threadpool.ScalingThreadPoolTests.testScalingThreadPoolConfiguration test

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#7530] opened 2023-05-11 19:42 UTC
**Describe the bug**
The org.opensearch.threadpool.ScalingThreadPoolTests.testScalingThreadPoolConfiguration test became flaky after https://github.com/opensearch-project/OpenSearch/pull/7400

**To Reproduce**
```
./gradlew ':server:test' --tests "org.opensearch.threadpool.ScalingThreadPoolTests.testScalingThreadPoolConfiguration" -Dtests.seed=6EC695D9A055C669 
```

If the commit (https://github.com/opensearch-project/OpenSearch/pull/7400) is reverted, test passes normally (seems to be caused by REMOTE_REFRESH thread pool) 

**Expected behavior**
Test should always pass

**Plugins**
Standard

**Screenshots**
- https://build.ci.opensearch.org/job/gradle-check/15255
- https://build.ci.opensearch.org/job/gradle-check/15143/

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
N/A

**Comment by reta** [comment] 2023-05-11 19:43
@ashking94 could you please take a look?

**Comment by ashking94** [comment] 2023-05-12 03:55
> @ashking94 could you please take a look?

Ack

**Comment by ashking94** [comment] 2023-05-12 04:10
thanks for creating this @reta. Here is the fix pr - https://github.com/opensearch-project/OpenSearch/pull/7539. Do take a look.

**Comment by dblock** [comment] 2023-10-06 15:06
This is back in https://github.com/opensearch-project/OpenSearch/pull/10430.

**Comment by ashking94** [comment] 2023-10-07 10:09
> This is back in #10430.

Happened due to some other reason this time, should we create another issue?

**Comment by dblock** [comment] 2023-10-10 21:02
@ashking94 Feel free to open another one and (I can) close this one.

**Comment by ashking94** [comment] 2023-11-01 18:39
I was able to reproduce this on the commit id where this failed and it was happening due to `Names.REMOTE_RECOVERY` not being handled in the expectedSize method. This has been handled subsequently recently with https://github.com/opensearch-project/OpenSearch/pull/10750.

https://github.com/opensearch-project/OpenSearch/blob/8673fa937db405b8d614f8d4a02c0aa52587c037/server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java#L143-L158

Also, this has not shown up from multiple days.

**Closed by ashking94** 2023-11-01 18:39 UTC
Labels: bug, untriaged, flaky-test
