### ISSUE TITLE
[CI] o.o.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks multiple failures

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1703] opened 2021-12-10 20:41 UTC
Multiple PR test failures (most [recent](https://github.com/opensearch-project/OpenSearch/pull/1698#issuecomment-991270666) for the following:

```
./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=403F055E1F14E391 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-TN -Dtests.timezone=Africa/Conakry -Druntime.java=17
```

```
2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([403F055E1F14E391:4749D095249295CC]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks(RemoteClustersIT.java:125)
  1> [2021-12-10T20:14:09,766][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] before test
  1> [2021-12-10T20:14:10,385][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] Configuring remote cluster [opensearch-2:9300]
  1> [2021-12-10T20:14:10,487][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] Connection info: org.opensearch.client.cluster.RemoteConnectionInfo@688b190
  1> [2021-12-10T20:14:10,693][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] after test
  1> [2021-12-10T20:14:10,737][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] before test
  1> [2021-12-10T20:14:11,294][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] Configuring remote cluster [opensearch-2:9300]
  1> [2021-12-10T20:14:11,363][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] Connection info: org.opensearch.client.cluster.RemoteConnectionInfo@5aef8603
  1> [2021-12-10T20:14:11,500][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] after test
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/remote-clusters/build/testrun/integTest/temp/org.opensearch.cluster.remote.test.RemoteClustersIT_403F055E1F14E391-001
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-TN, timezone=Africa/Conakry
  2> NOTE: Linux 5.4.0-1045-aws amd64/Eclipse Adoptium 17.0.1 (64-bit)/cpus=72,threads=1,free=451487832,total=536870912
  2> NOTE: All tests run in this JVM: [RemoteClustersIT]
```

Note:
```
        RemoteConnectionInfo rci = cluster1Client().cluster().remoteInfo(new RemoteInfoRequest(), RequestOptions.DEFAULT).getInfos().get(0);
        logger.info("Connection info: {}", rci);
        assertTrue(rci.isConnected());
```

[RemoteConnectionInfo](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/RemoteConnectionInfo.java) logging is useless. (**todo**: add `toString` support for logging)

**Comment by dblock** [comment] 2021-12-14 14:27
failed in https://github.com/opensearch-project/OpenSearch/pull/1723 again

**Comment by dblock** [comment] 2021-12-22 20:02
https://github.com/opensearch-project/OpenSearch/pull/1791#issuecomment-999827973

**Comment by dreamer-89** [comment] 2021-12-29 20:47
Looking into it

**Comment by dreamer-89** [comment] 2021-12-29 23:44
When I try to run the repro command mentioned in issue description above, it doesn't run the defined task. 

Command Used:
```
./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=403F055E1F14E391 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-TN -Dtests.timezone=Africa/Conakry -Druntime.java=17
```
Output:
```
➜  OpenSearch git:(main) ✗ ./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=403F055E1F14E391 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-TN -Dtests.timezone=Africa/Conakry -Druntime.java=11

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :buildSrc:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :buildSrc:compileGroovy
Note: /Users/singhnjb/OpenSearch/buildSrc/src/main/groovy/org/opensearch/gradle/test/TestWithSslPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :buildSrc:compileTestFixturesJava
Note: /Users/singhnjb/OpenSearch/buildSrc/src/testFixtures/java/org/opensearch/gradle/test/GradleIntegrationTestCase.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :buildSrc:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.3.3
  OS Info               : Mac OS X 11.6.2 (x86_64)
  Runtime JDK Version   : 11 (Eclipse Adoptium JDK)
  Runtime java.home     : /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
  Gradle JDK Version    : 11 (Eclipse Adoptium JDK)
  Gradle java.home      : /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
  Random Testing Seed   : 403F055E1F14E391
  In FIPS 140 mode      : false
=======================================

> Task :libs:opensearch-x-content:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :server:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :modules:aggs-matrix-stats:compileJava
Note: /Users/singhnjb/OpenSearch/modules/aggs-matrix-stats/src/main/java/org/opensearch/search/aggregations/matrix/MatrixAggregationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :modules:lang-mustache:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :modules:parent-join:compileJava
Note: /Users/singhnjb/OpenSearch/modules/parent-join/src/main/java/org/opensearch/join/ParentJoinPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :client:rest-high-level:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :test:framework:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 1m 26s
58 actionable tasks: 48 executed, 10 up-to-date
```

**Comment by dreamer-89** [comment] 2021-12-30 18:20
The test in question needs docker-compose to run; this was causing the test to get silently ignored. Passing `-i` (info) flag reveals this.

**Comment by dreamer-89** [comment] 2021-12-30 18:31
Ran tests in multiple iterations (1,10,100) but test did not fail even once.

**Comment by dreamer-89** [comment] 2022-03-11 05:55
This issue is still causing gradle check failures; even though this specific test is not reproducible when only this test is run.

@anasalkouz : Reopening this to have correct root cause fix.

**Comment by saratvemulapalli** [comment] 2022-03-21 20:53
Another PR: https://github.com/opensearch-project/OpenSearch/pull/2541#issuecomment-1074405738

**Comment by dblock** [comment] 2022-04-18 20:52
I've removed v2.0.0 label from this.

**Comment by andrross** [comment] 2023-07-27 18:47
Another failure here: https://github.com/opensearch-project/OpenSearch/pull/8901#issuecomment-1654221576

**Comment by dbwiddis** [comment] 2023-08-09 20:56
And here: https://github.com/opensearch-project/OpenSearch/pull/9184#issuecomment-1672105941

**Comment by ankitkala** [comment] 2023-11-02 06:56
- The test is updating cluster settings to add a remote cluster in proxy mode and then verifying that remote cluster is connected. 
https://github.com/opensearch-project/OpenSearch/blob/163a51fc5a7a7c5c2346c510aee52c3ad031f2f7/qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/RemoteClustersIT.java#L117-L125
- After the cluster setting gets updated, update listener will invoke this method to update the `RemoteClusterService`. The listener will timeout if the connection isn't updated within 10 seconds. We should log the message from `warn` to `error`.
https://github.com/opensearch-project/OpenSearch/blob/9ee37548dd268b7e9d57805d894a04523240bd91/server/src/main/java/org/opensearch/transport/RemoteClusterService.java#L264-L278
- `RemoteClusterService` will  start tracking the new remote cluster. It also invokes `ensureConnected` so that there is atleast one active connection to the remote cluster. https://github.com/opensearch-project/OpenSearch/blob/9ee37548dd268b7e9d57805d894a04523240bd91/server/src/main/java/org/opensearch/transport/RemoteClusterService.java#L304-L309
- For remote cluster in proxy mode, `ProxyConnectionStrategy` will establish the connections to the remote cluster nodes. https://github.com/opensearch-project/OpenSearch/blob/9ee37548dd268b7e9d57805d894a04523240bd91/server/src/main/java/org/opensearch/transport/ProxyConnectionStrategy.java#L305-L323

**Comment by ankitkala** [comment] 2023-11-02 07:02
Currently there is no wait condition between setting update and assertion on `isConnected` in the test. Connection establishment doesn't happen in sync path of cluster update anyways. To start with, I think we introduce as an assertBusy with timeout of 10 seconds(same as `RemoteClusterService.updateRemoteCluster` above)

**Comment by ankitkala** [comment] 2023-11-09 03:00
The PR has been merged. Keeping this issue open in case anyone is still observing this issue.

**Comment by andrross** [comment] 2024-07-31 22:44
Tracked by autocut: #14599

**Closed by andrross** 2024-07-31 22:44 UTC
Labels: bug, >test-failure, flaky-test, Indexing:Replication
