### ISSUE TITLE
Improve "OpenSearch exited with code 137" OOM error message on OSX

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#978] opened 2021-07-16 18:31 UTC
On attempting to setup OpenSearch and OpenSearch Dashboard, with Docker compose using only this documentation - it does not show expected behaviour and the dashboard is unavailable: 
https://opensearch.org/downloads.html 

Here is the terminal output on running the "docker-compose up" command as mentioned in the documented steps:
[TerminalOutput.txt](https://github.com/opensearch-project/OpenSearch/files/6832677/TerminalOutput.txt)

Operating System: Amazon Linux 2 x86_64

**Comment by Poojita-Raj** [comment] 2021-07-16 21:57
The opensearch dashboard doesn't connect and gives this error on following the documentation instructions (https://opensearch.org/downloads.html): 
`opensearch-dashboards  | {"type":"log","@timestamp":"2021-07-16T18:22:29Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1 opensearch-node1:9200"}` 

However, if you set: 
`vm.max_map_count=262144`
in the /etc/sysctl.conf file and use `sudo sysctl -p` to reload, the opensearch dashboard should work now and you will see the below message instead: 
`opensearch-dashboards  | {"type":"log","@timestamp":"2021-07-16T19:56:41Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0:5601"}
opensearch-dashboards  | {"type":"log","@timestamp":"2021-07-16T19:56:41Z","tags":["info","http","server","OpenSearchDashboards"],"pid":1,"message":"http server running at http://0:5601"}`

**Comment by setiah** [comment] 2021-07-16 22:51
Dashboard returns connection error with OpenSearch because the opensearch process exited on bootstrap check failures. 
```
opensearch-node2         | [2021-07-16T22:11:19,768][INFO ][o.o.b.BootstrapChecks    ] [opensearch-node2] bound or publishing to a non-loopback address, enforcing bootstrap checks
opensearch-node2         | ERROR: [1] bootstrap checks failed
opensearch-node2         | [1]: max virtual memory areas vm.max_map_count [65536] is too low, increase to at least [262144]
opensearch-node2         | ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log
```

On a Linux machine, it fails with proper error indicating bootstrap check failures due to `vm.max_map_count [65536] is too low`. However, when I run the same from Mac, this messaging seems ambiguous.

On Mac, it returns -
```opensearch-node2         | OpenSearch exited with code 137```

Exit code 137 stands for OOM failure. We need to fix this.


Anyways, the fix is increasing the vm.max_map_count to 262144 (as recommended above) https://gist.github.com/slovenski/48cbcbdfe05fda0bbe02f988c75914fa

**Comment by dblock** [comment] 2021-07-16 23:12
I renamed this issue to say that the error message needs to be improved on OSX and marked it as "good first issue". Maybe someone on this thread can PR a fix!

**Comment by owaiskazi19** [comment] 2021-07-21 16:44
I tried running OpenSearch with Docker compose on Mac with the default `vm.max_map_count` as `65535` and got the expected error message

`ERROR: [1] bootstrap checks failed
opensearch-node1         | [1]: max virtual memory areas vm.max_map_count [65535] is too low, increase to at least [262144]
opensearch-node1         | ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log
opensearch-node1         | [2021-07-21T16:40:32,973][INFO ][o.o.n.Node               ] [opensearch-node1] stopping ...
opensearch-node2         | ERROR: [1] bootstrap checks failed
opensearch-node2         | [1]: max virtual memory areas vm.max_map_count [65535] is too low, increase to at least [262144]
opensearch-node2         | ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-`

**Comment by setiah** [comment] 2021-07-21 23:37
Failure logs from last run for docker mac w/ exit code 137 error - https://gist.github.com/setiah/5c500960ebc76ab04e00a542e9709e37

```
^[[32mopensearch-node2         |^[[0m [2021-07-16T19:46:56,428][INFO ][o.o.t.TransportService   ] [opensearch-node2] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
^[[32mopensearch-node2         |^[[0m [2021-07-16T19:46:56,909][INFO ][o.o.b.BootstrapChecks    ] [opensearch-node2] bound or publishing to a non-loopback address, enforcing bootstrap checks
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:46:57,309][DEPRECATION][o.o.d.c.s.Settings       ] [opensearch-node1] [node.max_local_storage_nodes] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:46:59,115][WARN ][o.o.s.c.Salt             ] [opensearch-node1] If you plan to use field masking pls configure compliance salt e1ukloTsQlOgPquJ to be a random string of 16 chars length identical on all nodes
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:46:59,195][INFO ][o.o.s.a.i.AuditLogImpl   ] [opensearch-node1] Message routing enabled: true
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:46:59,331][INFO ][o.o.s.f.SecurityFilter   ] [opensearch-node1] <NONE> indices are made immutable.
^[[36mopensearch-dashboards    |^[[0m {"type":"log","@timestamp":"2021-07-16T19:46:59Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 172.18.0.4:9200"}
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:46:59,878][INFO ][o.o.a.b.ADCircuitBreakerService] [opensearch-node1] Registered memory breaker.
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:47:00,524][INFO ][o.o.t.NettyAllocator     ] [opensearch-node1] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={opensearch.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=512mb}]
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:47:01,022][INFO ][o.o.d.DiscoveryModule    ] [opensearch-node1] using discovery type [zen] and seed hosts providers [settings]
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:47:03,152][WARN ][o.o.g.DanglingIndicesState] [opensearch-node1] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
^[[36mopensearch-dashboards    |^[[0m {"type":"log","@timestamp":"2021-07-16T19:47:03Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 172.18.0.4:9200"}
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:47:04,361][INFO ][o.o.p.h.c.PerformanceAnalyzerConfigAction] [opensearch-node1] PerformanceAnalyzer Enabled: false
^[[36mopensearch-dashboards    |^[[0m {"type":"log","@timestamp":"2021-07-16T19:47:04Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 172.18.0.4:9200"}
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:47:04,830][INFO ][o.o.n.Node               ] [opensearch-node1] initialized
^[[33mopensearch-node1         |^[[0m [2021-07-16T19:47:04,830][INFO ][o.o.n.Node               ] [opensearch-node1] starting ...
^[[32mopensearch-node2         |^[[0m Killing performance analyzer process 11
^[[32mopensearch-node2         |^[[0m OpenSearch exited with code 137
```

**Comment by setiah** [comment] 2021-07-22 00:05
I can reproduce it at my end. 

Below steps were followed on Mac (same as described on the website) - 
1. Download docker-compose.yml from https://opensearch.org/downloads.html
2. Run docker-compose up

> Docker Images
```
➜  opensearch-docker docker images
REPOSITORY                                TAG                 IMAGE ID       CREATED         SIZE
opensearchproject/opensearch              latest              88b67cc9e81f   12 days ago     1.54GB
opensearchproject/opensearch-dashboards   latest              6a109c3fbebf   12 days ago     1.63GB
```

Setup

Docker version : Docker version 20.10.5, build 55c4c88
ProductName:	Mac OS X
ProductVersion:	10.14.6

Logs - https://gist.github.com/setiah/e05c93f5e925e2eb942d06febf0becd7

**Comment by owaiskazi19** [comment] 2021-07-22 00:07
I'm not able to reproduce the error by building docker image locally using `./gradlew assemble` and it's running as expected. We can add in the document [()](https://opensearch.org/downloads.html) to increase the `vm.max_map_count` to `262144`.
Ref: https://github.com/elastic/elasticsearch/issues/23498#issuecomment-284728221

**Comment by itsul** [comment] 2021-07-22 11:37
Hi there,

we installed OpenSearch via Docker on Debian 10. The error "...[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1..." could be solved by adjusting the mentioned kernel parameter.

Regards

**Comment by dblock** [comment] 2021-07-22 13:52
@setiah Sounds like we do have a repro, what's different?

@owaiskazi19 Definitely track down adding the right thing(s) to the doc(s), please.

**Comment by owaiskazi19** [comment] 2021-07-22 19:11
Code 137 is lack of memory indication.
If we are using Docker Desktop for Mac or Windows, need to have at least 4GB of RAM for Docker Engine to run or OpenSearch nodes might fail.

**Comment by dblock** [comment] 2021-07-22 20:56
The original issue was that we don't log the recommendation of changing a JVM setting on OSX. I can't tell by the above whether that's still the case or not? What's the definitive answer?

**Comment by setiah** [comment] 2021-07-22 20:58
Basically, we need to add these pre-requisites before running `docker-compose up`.

1. For linux, increase the vm.max_map_count to `262144`. The default value is 65536. 
```
1. Add the following line to /etc/sysctl.conf:
vm.max_map_count=262144
2. Reload the config:
sudo sysctl -p
3. Check the new value:
cat /proc/sys/vm/max_map_count
```

2. For Mac, increase the docker desktop runtime memory to 4GB.  By default, Docker Desktop is set to use 2 GB runtime memory, allocated from the total available memory on your Mac. 

Issue to fix the documentation on website - https://github.com/opensearch-project/project-website/issues/222

**Comment by stockholmux** [comment] 2021-07-22 21:00
...is this a memory usage regression from Open Distro? I don't recall having to set this and [it's not in the documentation](https://opensearch.org/docs/opensearch/install/docker/) where the docker-compose file was sourced from.

**Comment by setiah** [comment] 2021-07-22 21:00
@dblock the reason we don't see this on OSX is because we don't have this bootstrap check for OSX. It is only there for linux. I'm not sure of the reason, but seems like operating system specific difference.

It crashes on mac due to lower RAM allocated to docker by default. Increasing the RAM to 4GB fixed it.

**Comment by dblock** [comment] 2021-07-22 21:06
> @dblock the reason we don't see this on OSX is because we don't have this [bootstrap check](https://github.com/opensearch-project/OpenSearch/blob/9168f1fb43015cf7f33eab30f1300ec85f4d4305/server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java#L220) for OSX. It is only there for linux. I'm not sure of the reason, but seems like operating system specific difference.

Ok, so this seems like we want this implemented for OSX, which is the original issue reported here.

> It crashes on mac due to lower RAM allocated to docker by default. Increasing the RAM to 4GB fixed it.

**Comment by owaiskazi19** [comment] 2021-07-22 21:06
@stockholmux it's mentioned on [https://opensearch.org/docs/opensearch/install/important-settings/](https://opensearch.org/docs/opensearch/install/important-settings/). As @setiah mentioned we need to fix the documentation on website and add the above link there.

**Comment by setiah** [comment] 2021-07-22 21:06
@stockholmux odfe documentation calls out increasing docker RAM to 4G https://opensearch.org/docs/opensearch/install/docker/. 

docker-compose file is sourced from the download link on the website. https://opensearch.org/downloads.html

**Comment by stockholmux** [comment] 2021-07-22 21:09
OK. Fair enough 🤦‍♂️.  We'll add the same notice about 4gb to the download page.

**Comment by stockholmux** [comment] 2021-07-22 21:17
Fixed by opensearch-project/project-website/issues/222

**Comment by stockholmux** [comment] 2021-07-22 21:38
@owaiskazi19 and @setiah can either of you confirm that the `vm.max_map_count` is actually needed in docker in Linux? 

The documentation indicates otherwise: "For production workloads, make sure the Linux setting vm.max_map_count is set to at least 262144. On the **OpenSearch Docker image, this setting is the default.**"

**Comment by owaiskazi19** [comment] 2021-07-22 23:55
Yes @stockholmux. Here is the Linux docker-compose up logs with default vm.max_map_count.

`opensearch-node1         | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
opensearch-node1         | ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log
opensearch-node1         | [2021-07-22T23:52:53,072][INFO ][o.o.n.Node               ] [opensearch-node1] stopping ...
opensearch-node1         | [2021-07-22T23:52:53,072][INFO ][o.o.s.a.r.AuditMessageRouter] [opensearch-node1] Closing AuditMessageRouter
opensearch-node1         | [2021-07-22T23:52:53,073][INFO ][o.o.s.a.s.SinkProvider   ] [opensearch-node1] Closing InternalOpenSearchSink
opensearch-node1         | [2021-07-22T23:52:53,073][INFO ][o.o.s.a.s.SinkProvider   ] [opensearch-node1] Closing DebugSink
opensearch-node2         | [2021-07-22T23:52:53,084][INFO ][o.o.n.Node               ] [opensearch-node2] stopped
opensearch-node2         | [2021-07-22T23:52:53,085][INFO ][o.o.n.Node               ] [opensearch-node2] closing ...
opensearch-node1         | [2021-07-22T23:52:53,084][INFO ][o.o.n.Node               ] [opensearch-node1] stopped
opensearch-node1         | [2021-07-22T23:52:53,085][INFO ][o.o.n.Node               ] [opensearch-node1] closing ...
opensearch-node2         | [2021-07-22T23:52:53,089][INFO ][o.o.s.a.i.AuditLogImpl   ] [opensearch-node2] Closing AuditLogImpl
opensearch-node1         | [2021-07-22T23:52:53,089][INFO ][o.o.s.a.i.AuditLogImpl   ] [opensearch-node1] Closing AuditLogImpl
opensearch-node2         | [2021-07-22T23:52:53,091][INFO ][o.o.n.Node               ] [opensearch-node2] closed
opensearch-node1         | [2021-07-22T23:52:53,091][INFO ][o.o.n.Node               ] [opensearch-node1] closed
opensearch-node2         | Killing performance analyzer process 11
opensearch-node2         | OpenSearch exited with code 78
opensearch-node2         | Performance analyzer exited with code 143
opensearch-node1         | Killing performance analyzer process 11
opensearch-node1         | OpenSearch exited with code 78
opensearch-node1         | Performance analyzer exited with code 143
opensearch-node2 exited with code 0
opensearch-node1 exited with code 0
opensearch-dashboards    | {"type":"log","@timestamp":"2021-07-22T23:52:54Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1 opensearch-node1:9200"}
opensearch-dashboards    | {"type":"log","@timestamp":"2021-07-22T23:52:57Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1 opensearch-node1:9200"}
opensearch-dashboards    | {"type":"log","@timestamp":"2021-07-22T23:52:59Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1 opensearch-node1:9200"}
opensearch-dashboards    | {"type":"log","@timestamp":"2021-07-22T23:53:02Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1 opensearch-node1:9200"}`

**Comment by stockholmux** [comment] 2021-07-28 21:54
OK - I have a PR for the website that address all plaforms: https://github.com/opensearch-project/project-website/pull/241 - I'm waiting on an update to the docs site to deploy it (there is also a merged but not deployed change on Docs for this issue).

**However,** I've been doing some reading on the `vm.max_map_count` and it seems [setting it for WSL on windows is a long unresolved problem](https://github.com/docker/for-win/issues/5202) with Docker. Most search results on google for `vm.max_map_count` related someone trying (and failing) to run Elasticsearch. Do we know what the root cause of needing to use `vm.max_map_count` actually is? Can we fix it?

**Comment by owaiskazi19** [comment] 2021-07-29 19:21
OpenSearch uses `mmapfs` to store the indices which requires virtual memory space of the host machine. We want to set or increase the virtual memory using `vm.max_map_count` for the host machine and not on the container level. This is the reason why it should be set manually and can be reset later.

**Comment by stockholmux** [comment] 2021-07-29 19:35
@owaiskazi19 OK. Makes sense.

I'm wondering if it would be wise to use a different `index.store.type` for those just trying out OpenSearch via docker-compose. This would likely get around special settings and reduce friction for those wanting to get started on a desktop machine. Of course, for production workloads `mmapfs` would be better.

**Comment by owaiskazi19** [comment] 2021-07-29 21:44
We can bypass the bootstrap check (where it checks for `vm.max_map_count`) by setting some flag (https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java#L307) but I'm not sure if it's the correct way to do it and what all needs to be addressed if we create a flag.
cc: @setiah @saratvemulapalli

**Comment by saratvemulapalli** [comment] 2021-09-22 23:09
@owaiskazi19 following up on this one. 
Could you help understand what more work is needed here?

**Comment by owaiskazi19** [comment] 2021-09-23 00:08
@saratvemulapalli we have already changed the steps for downloading opensearch.
Ref: https://opensearch.org/downloads.html. We can close this issue.

**Closed** 2021-09-23 00:10 UTC
Labels: enhancement, good first issue, help wanted, Build Libraries & Interfaces
