### ISSUE TITLE
[BUG]  Fix flaky test org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#4215] opened 2022-08-15 16:21 UTC
**Describe the bug**
New flaky test `org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits` ,  spotted in [1]

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([82C1833901696ED6:1091E20136EA4FEE]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits(ShardIndexingPressureConcurrentExecutionTests.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

[1] https://build.ci.opensearch.org/job/gradle-check/1710/testReport/junit/org.opensearch.index/ShardIndexingPressureConcurrentExecutionTests/testCoordinatingPrimaryThreadedUpdateToShardLimits_2/

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits" -Dtests.seed=82C1833901696ED6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mt -Dtests.timezone=Pacific/Funafuti -Druntime.java=17
```

**Expected behavior**
Test should pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: CI
 - Version `main`

**Additional context**

**Comment by andrross** [comment] 2022-11-08 21:45
Closing as a duplicate of #2241

**Comment by andrross** [comment] 2022-11-08 22:07
Reopening, not actually the same test as #2241

**Closed** 2022-11-09 18:39 UTC
Labels: bug, Indexing & Search
