### ISSUE TITLE
[BUG] Test failure in org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#3872] opened 2022-07-13 00:30 UTC
**Describe the bug**
First seen in PR https://github.com/opensearch-project/OpenSearch/pull/3863#issuecomment-1182074587

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating" -Dtests.seed=5A433E181EF43D3D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-BH -Dtests.timezone=Mexico/General -Druntime.java=17

org.opensearch.indices.replication.SegmentReplicationTargetServiceTests > testShardAlreadyReplicating FAILED
    java.lang.AssertionError: can't move replication to stage [DONE]. current stage: [INIT] (expected [REPLICATING])
        at __randomizedtesting.SeedInfo.seed([5A433E181EF43D3D:799ABB039433F434]:0)
        at org.opensearch.indices.replication.SegmentReplicationState.validateAndSetStage(SegmentReplicationState.java:88)
        at org.opensearch.indices.replication.SegmentReplicationState.setStage(SegmentReplicationState.java:107)
        at org.opensearch.indices.replication.SegmentReplicationTarget.onDone(SegmentReplicationTarget.java:87)
        at org.opensearch.indices.replication.common.ReplicationTarget.markAsDone(ReplicationTarget.java:143)
        at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:139)
``` 

**To Reproduce**
The test failure in the method `testShardAlreadyReplicating` can be reproduced by running the test cases in the whole class.
The either random seed can reproduce the test failure.
`./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests" -Dtests.seed=5A433E181EF43D3D`
`./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests" -Dtests.seed=9A5D3217135E5052`

**Expected behavior**
Test passes.

**Plugins**
none.

**Screenshots**
none.

**Host/Environment (please complete the following information):**

**Additional context**
none.

**Comment by dreamer-89** [comment] 2022-07-13 17:12
Another occurence
https://github.com/opensearch-project/OpenSearch/pull/3863

**Comment by dreamer-89** [comment] 2023-08-16 17:10
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/8928. Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/8928

**Closed by dreamer-89** 2023-08-16 17:10 UTC
Labels: bug, >test-failure
