### ISSUE TITLE
[BUG] IndicesRequestCacheIT timing out

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/OpenSearch#13734] opened 2024-05-17 16:08 UTC
### Describe the bug

Sometimes builds fail due to IndicesRequestCacheIT timing out with error -  `abandoned because suite timeout was reached`

### Related component

Search:Performance

### To Reproduce

1. Go to [this build failure](https://build.ci.opensearch.org/job/gradle-check/38870/console#:~:text=2%3E%20java.lang.Exception%3A%20Test%20abandoned%20because%20suite%20timeout%20was%20reached.%0A%20%20%20%20%20%20%20%20at%20__randomizedtesting.SeedInfo.seed(%5B4F0B8D205DAA8C0%5D%3A0))

### Expected behavior

The suite should not time out.

**Comment by peternied** [comment] 2024-05-22 15:24
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/scrawfor99) [3](https://github.com/reta/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/peternied) [6](https://github.com/lukas-vlcek/) [7](https://github.com/cwperks) [8](https://github.com/akolarkunnu) [9](https://github.com/truesellj) [10](https://github.com/mch2)]
@kiranprakash154 Thanks for creating this issue - before you get started please take a look to see if there is another issues tracking this specific test class

**Comment by reta** [comment] 2024-05-22 15:25
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/13503

**Closed by reta** 2024-05-22 15:25 UTC
Labels: bug, :test, flaky-test, Search, Search:Performance
