### ISSUE TITLE
opensearch-x-content-2.7.0.jar missing many classes

### ISSUE THREAD

**Issue by kesiju** [opensearch-project/OpenSearch#7728] opened 2023-05-24 13:46 UTC
Hi,
   I am getting multiple class not found exceptions trying to compile a plugin with 2.7.0 release. 

```
error: cannot find symbol
import org.opensearch.common.xcontent.XContentBuilder;
import org.opensearch.common.xcontent.XContentParser;
import org.opensearch.common.xcontent.NamedXContentRegistry;

```
This jar is coming from the tar ball at https://artifacts.opensearch.org/releases/bundle/opensearch/2.7.0/opensearch-2.7.0-linux-x64.tar.gz .

Checking the jar I saw it has very few classes compared to previous releases.

`jar tvf ../lib/opensearch-x-content-2.7.0.jar 
`
```
     0 Fri Feb 01 00:00:00 EST 1980 META-INF/
   667 Fri Feb 01 00:00:00 EST 1980 META-INF/MANIFEST.MF
 11358 Fri Feb 01 00:00:00 EST 1980 META-INF/LICENSE.txt
   369 Fri Feb 01 00:00:00 EST 1980 META-INF/NOTICE.txt
     0 Fri Feb 01 00:00:00 EST 1980 org/
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/
  7417 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentFactory.class
  1044 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentType$1.class
   943 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentType$2.class
   936 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentType$3.class
   936 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentType$4.class
  3778 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentType.class
  2196 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/XContentUtils.class
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/cbor/
  5650 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/cbor/CborXContent.class
  1451 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/cbor/CborXContentGenerator.class
  1118 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/cbor/CborXContentParser.class
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/json/
  5484 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/json/JsonXContent.class
   944 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/json/JsonXContentGenerator$1.class
 15182 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/json/JsonXContentGenerator.class
  1984 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/json/JsonXContentParser$1.class
  8189 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/json/JsonXContentParser.class
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/smile/
  5911 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/smile/SmileXContent.class
  1457 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/smile/SmileXContentGenerator.class
  1124 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/smile/SmileXContentParser.class
     0 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/yaml/
  5027 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/yaml/YamlXContent.class
  1451 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/yaml/YamlXContentGenerator.class
  1118 Fri Feb 01 00:00:00 EST 1980 org/opensearch/common/xcontent/yaml/YamlXContentParser.class

```

TIA for any help.
Siju

**Comment by dblock** [comment] 2023-05-29 13:39
I believe this is caused by https://github.com/opensearch-project/OpenSearch/pull/6470. cc: @nknize 

Btw, what does your plugin do @kesiju?

**Comment by andrross** [comment] 2023-05-30 23:24
@kesiju Some internal classes changed packages. You should be able to resolve this by updating the imports in your plugin code to reflect the new package location (`org.opensearch.core.xcontent`).

**Comment by anasalkouz** [comment] 2023-06-06 21:35
Hey @kesiju, closing this for now, since we you should have path forward. please feel free to comment to re-open the issue if needed.

**Closed by anasalkouz** 2023-06-06 21:35 UTC
Labels: distributed framework

**Comment by kesiju** [comment] 2023-06-08 10:41
Thank you @dblock for the response. The plugin runs some custom rollup jobs.
