### ISSUE TITLE
Support both elasticsearch.yml and opensearch.yml under config directory

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/OpenSearch#728] opened 2021-05-19 20:16 UTC
Need information on whether we are supporting both these files or only one of which is used.

This raise the question that should we support `open_distro` related config in `opensearch.yml` or vise versa. Which may cause confusion if not well documented config file presents in `config` directory

**Comment by nknize** [comment] 2021-05-20 14:36
The plan is to not support both files and nothing in the old yml file has been removed in the opensearch.yml. If there are custom parameters that were added to the old .yml file by way of a patch then lets open separate PRs to propose adding them to opensearch.yml. Plugin specific parameters, however, should not be proposed in the opensearch.yml file since they have their own repos and may or may not be installed in every distribution.

**Comment by dblock** [comment] 2021-05-20 15:17
Related #640, @mch2 is looking at introducing backwards compatibility for this exact case

**Comment by dblock** [comment] 2021-05-20 15:19
@nknize I believe a safe proposal would be to 

1. Abort if both elasticsearch.yml and opensearch.yml exist.
2. If only elasticsearch.yml exists, load it.
3. If opensearch.yml exists, load it.

This way simple 1-node installations aren't surprised their settings aren't read, and the implementation is fairly straightforward. 

There are other cases in #640 with similar problems.

**Comment by nknize** [comment] 2021-05-20 15:48
> This way simple 1-node installations aren't surprised their settings aren't read

Supporting elasticsearch.yml as a nuclear catch all should not be an option. Instead we should be teasing out what exactly is broken in opensearch.yml and address those on a case by case basis. Can we list here the exact settings that aren't being read?

**Comment by dblock** [comment] 2021-05-20 16:56
@nknize are you saying this is not a problem we need to worry about, and if so, why:

1. Install ES 7.x
2. Add `path.data: /var/lib/ilovedata` to `config/elasticsearch.yml`.
3. Decide to upgrade to OpenSearch
4. Overwrite ES 7.x binaries with OpenSearch
5. Run, old value of `path.data` not used.

**Comment by nknize** [comment] 2021-05-20 17:13
Is this what you've done and you're seeing an error? If so can you post the stack trace or a reproducible integration test?

If this is trying to capture the "upgrade process" I'm not sure number 4 is the thing to do? Rolling upgrades would be nice, but if that's not working because of a settings migration issue, or a version marshalling issue in the transport layer, then let's create issues around those concrete failures and create unit/integration tests to easily reproduce and fix.

**Comment by dblock** [comment] 2021-05-20 18:13
We decided that OpenSearch will raise an error if both `elasticsearch.yml` and `opensearch.yml` are present to prevent users like myself from making mistakes, @mch2 is taking this as part of #640.

**Comment by vrozov** [comment] 2021-05-20 23:48
Will opensearch provide migration utility (path) from elasticsearch.yml to opensearch.yml assuming that such migration includes migration from `elasticsearch.xxx` to `opensearch.xxx` and `opendistro.xxx` to `opensearch.xxx` settings? Why new file (opensearch.yml) would contain old settings unless it was a direct copy from elasticsearch.yml to opensearch.yml? IMO, such copy does not add any value and should not be supported, but instead migration utility must be provided.

**Comment by dblock** [comment] 2021-05-21 14:00
> IMO, such copy does not add any value and should not be supported, but instead migration utility must be provided.

I disagree with no value. Knowing that all settings that I put in elasticsearch.yml before for good reason continue working seems reassuring and easy for me as an operator. I am also of the opinion that we should support both filenames, but I think @nknize is arguing that we might want to be able to run two instances with different settings between ES and OpenSearch. I don't feel that strongly about a file name, environment variables is where I'm really worried about.

**Comment by vrozov** [comment] 2021-05-22 20:19
I don't question the value of supporting existing settings in `elasticsearch.yml`, I question value of coping `elasticsearch.yml` to `opensearch.yml` as is, without migrating (and providing migration utility) the old settings names to the new settings names. This question is mostly independent from the question whether both files needs to be supported or only one should be supported. My personal take on the later question is that both needs to be supported with `opensearch.yml` taking precedence over `elasticsearch.yml` if both are present in the config directory (with deprecation warning when only `elasticsearch.yml` is present).

**Comment by dblock** [comment] 2021-05-23 14:28
@vrozov why is that your preference?

**Comment by vrozov** [comment] 2021-05-23 20:14
It gives an option to use `elasticsearch.yml` in backward compatible mode if users are not yet ready to fully migrate from `elasticsearch.yml` to `opensearch.yml`.

**Comment by dblock** [comment] 2021-06-08 17:29
We decided we won't support both, closing.

**Closed by dblock** 2021-06-08 17:29 UTC
Labels: discuss
