### ISSUE TITLE
[BUG] org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT/test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials} flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#5219] opened 2022-11-11 21:21 UTC
org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT/test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials}

  https://build.ci.opensearch.org/job/gradle-check/6782/
  https://build.ci.opensearch.org/job/gradle-check/6779/
  https://build.ci.opensearch.org/job/gradle-check/6778/
  https://build.ci.opensearch.org/job/gradle-check/6766/
  https://build.ci.opensearch.org/job/gradle-check/6751/
  https://build.ci.opensearch.org/job/gradle-check/6750/

**Comment by dblock** [comment] 2022-11-11 21:36
```
java.lang.AssertionError: Failure at [repository_s3/20_repository_permanent_credentials:201]: expected [2xx] status code but api [snapshot.create] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_exception","reason":"[repository_permanent] concurrent modification of the index-N file, expected current generation [30972] but it was not found in the repository","stack_trace":"RepositoryException[[repository_permanent] concurrent modification of the index-N file, expected current generation [30972] but it was not found in the repository]\n\tat 
```

```
java.lang.AssertionError: Failure at [repository_s3/20_repository_permanent_credentials:152]: expected [2xx] status code but api [snapshot.create] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"invalid_snapshot_name_exception","reason":"[repository_permanent:snapshot-one] Invalid snapshot name [snapshot-one], snapshot with the same name already exists","stack_trace":"InvalidSnapshotNameException[[repository_permanent:snapshot-one] Invalid snapshot name [snapshot-one], snapshot with the same name already exists]\n\tat 
```

```
java.lang.AssertionError: Failure at [repository_s3/20_repository_permanent_credentials:262]: expected [2xx] status code but api [snapshot.delete] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_exception","reason":"[repository_permanent] concurrent modification of the index-N file, expected current generation [30954] but it was not found in the repository","stack_trace":"RepositoryException[[repository_permanent] concurrent modification of the index-N file, expected current generation [30954] but it was not found in the repository]\n\tat 
```

```
"type" : "repository_exception",
        "reason" : "[repository_permanent] concurrent modification of the index-N file, expected current generation [30896] but it was not found in the repository",
        "stack_trace" : "RepositoryException[[repository_permanent] concurrent modification of the index-N file, expected current generation [30896] but it was not found in the repository]
```

```
java.lang.AssertionError: Failure at [repository_s3/20_repository_permanent_credentials:201]: expected [2xx] status code but api [snapshot.create] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_exception","reason":"[repository_permanent] concurrent modification of the index-N file, expected current generation [30818] but it was not found in the repository","stack_trace":"RepositoryException[[repository_permanent] concurrent modification of the index-N file, expected current generation [30818] but it was not found in the repository]\n\tat 
```

Tells me it's some race condition.

**Comment by reta** [comment] 2022-11-14 21:31
@dblock  I will try to fix this one

**Comment by dblock** [comment] 2022-11-15 13:54
@reta Take it! I suspect the root cause is a failure in setup/teardown of tests, but so far I didn't find anything meaningful.

**Comment by reta** [comment] 2022-11-24 01:55
https://build.ci.opensearch.org/job/gradle-check/7310

```
RepositoryException[[repository_permanent] could not read repository data from index blob]; nested: NoSuchFileException[Blob object [base_integration_tests/index-33116] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: BV24YG8Z1EYBVKQV; S3 Extended Request ID: RzTmKdLPXdgVFSDIpmulCFgiVMTc82ccLUA/rV2Ibkdz8RUIyP6SvUn02mCH3ffjrumP/jmtyCo=; Proxy: null)];
	at org.opensearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1842)
	at org.opensearch.repositories.blobstore.BlobStoreRepository.safeRepositoryData(BlobStoreRepository.java:798)
	at org.opensearch.repositories.blobstore.BlobStoreRepository$2.doRun(BlobStoreRepository.java:731)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.nio.file.NoSuchFileException: Blob object [base_integration_tests/index-33116] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: BV24YG8Z1EYBVKQV; S3 Extended Request ID: RzTmKdLPXdgVFSDIpmulCFgiVMTc82ccLUA/rV2Ibkdz8RUIyP6SvUn02mCH3ffjrumP/jmtyCo=; Proxy: null)
	at org.opensearch.repositories.s3.S3RetryingInputStream.openStream(S3RetryingInputStream.java:118)
	at org.opensearch.repositories.s3.S3RetryingInputStream.<init>(S3RetryingInputStream.java:96)
	at org.opensearch.repositories.s3.S3RetryingInputStream.<init>(S3RetryingInputStream.java:79)
	at org.opensearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:112)
	at org.opensearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1827)
	... 7 more
```

**Comment by dblock** [comment] 2022-11-28 17:44
@reta Looks like this is a legit bug (thanks for opening https://github.com/opensearch-project/OpenSearch/issues/5371) vs. random flaky test failure. Shall we re-close this one to avoid confusion?

**Comment by reta** [comment] 2022-11-28 18:32
> @reta Looks like this is a legit bug (thanks for opening #5371) vs. random flaky test failure. Shall we re-close this one to avoid confusion?

Thanks @dblock, the second occurrence (https://github.com/opensearch-project/OpenSearch/issues/5219#issuecomment-1325849190) is not clear to me, I suspect it is still flakyness, I will watch the builds a bit and update you, thanks!

**Comment by reta** [comment] 2022-12-06 19:19
Thanks @dreamer-89 

> To repro, I ran `./gradlew :plugins:repository-s3:yamlRestTest` but didn't see a single failure even with 100 of repitition counts.

Same, no luck reproducing it locally

>  I verified that by setting the creds and running the repository-s3 tests. We updated the gradle check job in https://github.com/opensearch-project/OpenSearch/issues/1763 to use the external s3 end-points.

Aha, that could be the difference since locally the tests are run against Minio clusters

**Comment by dreamer-89** [comment] 2022-12-07 05:27
Unrelated to flaky test and more around repro'ing test failure which was unsuccessful :(

Previous effort to decipher heap dump (auto generated by gradle check) was unsuccessful due to large heap dump files (~5GB). 
```
ubuntu@ip-172-31-41-165:~/OpenSearch$ ls -al
total 35339500
...
-rwxrwxr-x  1 ubuntu ubuntu       8070 Dec  5 21:55 gradlew
-rw-rw-r--  1 ubuntu ubuntu       2763 Jun 14 19:40 gradlew.bat
-rw-------  1 ubuntu ubuntu 5219185718 Dec  6 09:25 java_pid1532657.hprof
-rw-------  1 ubuntu ubuntu 4971058607 Dec  6 04:35 java_pid1745377.hprof
-rw-------  1 ubuntu ubuntu 5271518597 Dec  6 03:05 java_pid2568.hprof
-rw-------  1 ubuntu ubuntu 5260716271 Dec  6 10:50 java_pid2681937.hprof
-rw-------  1 ubuntu ubuntu 5155513083 Dec  6 06:15 java_pid3408534.hprof
-rw-------  1 ubuntu ubuntu 5101514079 Dec  6 12:18 java_pid3882150.hprof
-rw-------  1 ubuntu ubuntu 5207750826 Dec  6 07:54 java_pid419165.hprof
...
```
Used `jhat`, Eclipse's `mat` but failed due to heap space issue. Increased available heap for mat to 8GB (slowed down my machine drastically) but still not enough.
```
➜  ~ jhat -port 9999 Desktop/dumps/java_pid2568.hprof
Reading from Desktop/dumps/java_pid2568.hprof...
Dump file created Mon Dec 05 19:04:38 PST 2022
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.sun.tools.hat.internal.model.Snapshot.makeId(Snapshot.java:586)
	at com.sun.tools.hat.internal.model.Snapshot.addHeapObject(Snapshot.java:166)
	at com.sun.tools.hat.internal.parser.HprofReader.readInstance(HprofReader.java:744)
	at com.sun.tools.hat.internal.parser.HprofReader.readHeapDump(HprofReader.java:491)
	at com.sun.tools.hat.internal.parser.HprofReader.read(HprofReader.java:275)
	at com.sun.tools.hat.internal.parser.Reader.readFile(Reader.java:92)
	at com.sun.tools.hat.Main.main(Main.java:159)
```

To capture m/y issue, re-ran the gradle check and used `pstree` to capture long running java processes (>1 hr using red color code) depicts gradle process GC & jar transform are running. 
```
  ├─java,5272,5272 -XX:+HeapDumpOnOutOfMemoryError -Xss2m --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exportsjdk.compiler/com.sun.tools.javac.parser=ALL
  │   ├─{C1 CompilerThre},5334,5272
  │   ├─{C2 CompilerThre},5333,5272
  │   ├─{Cache worker fo},6470,5272
  │   ├─{Cache worker fo},8552,5272
```
All sub-process from above can be checked in [gist](https://gist.github.com/dreamer-89/aea9422ef074b0637903cb856ae73023) 

Survivor space 1 shows 100% consumption probably issue with garbage collection. May be increasing YG size may help. Just curious how gradle check not causing m/y issues on CI. 
```
ubuntu@ip-172-31-41-165:~/OpenSearch$ jstat -gcutil 5272 1000 5
  S0     S1     E      O      M     CCS    YGC     YGCT     FGC    FGCT     CGC    CGCT       GCT
  0.00 100.00  64.50  62.84  58.16  43.30    105     4.694     0     0.000    24     1.307     6.000
  0.00 100.00  64.50  62.84  58.16  43.30    105     4.694     0     0.000    24     1.307     6.000
  0.00 100.00  64.50  62.84  58.16  43.30    105     4.694     0     0.000    24     1.307     6.000
  0.00 100.00  64.50  62.84  58.16  43.30    105     4.694     0     0.000    24     1.307     6.000
  0.00 100.00  64.50  62.84  58.16  43.30    105     4.694     0     0.000    24     1.307     6.000
```

**Comment by reta** [comment] 2022-12-07 13:56
@dreamer-89 I think I know what is happening (this is related to S3 fixture failures, not OOM): since we now run against S3 (after https://github.com/opensearch-project/OpenSearch/issues/1763) and the tests use same bucket, it is highly likely that a few builds running at the same time do modify same S3 bucket concurrently, hence these random failures, I will try to randomize this part.

**Comment by dreamer-89** [comment] 2022-12-07 16:26
> @dreamer-89 I think I know what is happening (this is related to S3 fixture failures, not OOM): since we now run against S3 (after #1763) and the tests use same bucket, it is highly likely that a few builds running at the same time do modify same S3 bucket concurrently, hence these random failures, I will try to randomize this part.

Thanks @reta, I think this makes sense. 

I tried creating a [randomized base path](https://github.com/dreamer-89/OpenSearch/commit/3a07bc5e9e5076eb7b8ffe4575f9805b241ab62b) and it seems to work fine.

**Comment by reta** [comment] 2022-12-07 17:27
> I tried creating a [randomized base path](https://github.com/dreamer-89/OpenSearch/commit/3a07bc5e9e5076eb7b8ffe4575f9805b241ab62b) and it seems to work fine.

Exactly @dreamer-89 , we already do that in a few places with `testSeed`, pull request on the way (testing)

**Closed** 2022-12-07 18:51 UTC
Labels: bug, flaky-test

**Comment by dreamer-89** [comment] 2022-12-19 18:26
Verified in latest runs there are no s3 repository test failures.

```
➜  OpenSearch git:(main) ✗ ruby flaky-finder.rb y-finder.rb --s 7740 --e 8258
Will crawl builds from 7740 to 8258
------------------
8 org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness (7814,7864,8014,8066,8078,8166,8217,8248)
5 org.opensearch.indices.stats.IndexStatsIT.testFilterCacheStats (7932,7977,8066,8156,8169)
3 org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=pit/10_basic/Delete all} (7947,8078,8154)
2 org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex (7976,8250)
2 org.opensearch.snapshots.DedicatedClusterSnapshotRestoreIT.testIndexDeletionDuringSnapshotCreationInQueue (8004,8122)
2 org.opensearch.cluster.service.MasterServiceTests.classMethod (8193,8193)
1 org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT.testNodesRemovedAfterZoneDecommission_ClusterManagerNotInToBeDecommissionedZone (7930)
1 org.opensearch.repositories.s3.S3BlobContainerRetriesTests.testReadRangeBlobWithRetries (7942)
1 org.opensearch.cluster.routing.allocation.decider.ConcurrentRecoveriesAllocationDeciderTests.testClusterConcurrentRecoveries (8035)
1 org.opensearch.client.PitIT.testDeleteAllAndListAllPits (8115)
1 org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringFetchPhase (8142)

```
