### ISSUE TITLE
Error accessing opensearch API

### ISSUE THREAD

**Issue by CCTV-six** [opensearch-project/OpenSearch#16586] opened 2024-11-07 08:15 UTC
### Describe the bug

Accessing the opensearch API returns missing authentication credentials

### Related component

Cluster Manager

### To Reproduce

none

### Expected behavior

Resolve the issue

### Additional Details

none

**Comment by andrross** [comment] 2024-11-07 20:05
I encourage you to use the forum or slack for support. If you think there is a bug then this is the right place, but we'll need a lot more detail and reproduction steps to be able to take action. Closing this issue for now due to lack of details.

**Closed by andrross** 2024-11-07 20:05 UTC
Labels: bug, untriaged, Cluster Manager
