### ISSUE TITLE
[BUG] High Level Rest Client broken compatibility with Open Distro 

### ISSUE THREAD

**Issue by robertdkmarshall** [opensearch-project/OpenSearch#1965] opened 2022-01-24 00:20 UTC
**Describe the bug**
Health check fails when talking to non-OpenSearch clusters. Additional field is not in earlier versions of Open Distro etc.

Exception in thread "main" java.io.IOException: Unable to parse response body for Response{requestLine=GET /_cluster/health?master_timeout=30s&level=cluster&timeout=30s HTTP/1.1, host=http://52.43.191.95:9201, response=HTTP/1.1 200 OK}
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1781)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1728)
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696)
	at org.opensearch.client.ClusterClient.health(ClusterClient.java:162)
	at RESTClientSample.main(RESTClientSample.java:123)
Caused by: java.lang.IllegalArgumentException: Required [discovered_master]
	at org.opensearch.common.xcontent.ConstructingObjectParser$Target.finish(ConstructingObjectParser.java:540)
	at org.opensearch.common.xcontent.ConstructingObjectParser$Target.access$000(ConstructingObjectParser.java:444)
	at org.opensearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:186)
	at org.opensearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:178)
	at org.opensearch.action.admin.cluster.health.ClusterHealthResponse.fromXContent(ClusterHealthResponse.java:406)
	at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2075)
	at org.opensearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:1696)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1779)

**To Reproduce**
Using the Health Check when talking to Open Distro 

        ClusterHealthRequest clusterHealthRequest = new ClusterHealthRequest();
        client.cluster().health(clusterHealthRequest, RequestOptions.DEFAULT);

**Expected behavior**
Health check should succeed 

**Plugins**
N/A

**Screenshots**

**Host/Environment (please complete the following information):**
 - Version OpenSearch 1.2 High Level Rest Client talking to Open Distro cluster (probably effects other non Open Search as well)

**Additional context**
Look like it was broken by https://github.com/opensearch-project/OpenSearch/pull/656

**Comment by mariuszpala** [comment] 2022-01-26 17:55
Hi, is there any plan to fix it, we have also just migrated Elasticsearch 7.10.2 API to OpenSearch API and we experience the same issue. This is critcal for us to support existing OpenDistro installations and also ES 7.10

**Comment by dblock** [comment] 2022-02-02 17:02
@saratvemulapalli Did we introduce a regression we didn't want to in https://github.com/opensearch-project/OpenSearch/pull/656?

**Comment by saratvemulapalli** [comment] 2022-02-08 00:13
> @saratvemulapalli Did we introduce a regression we didn't want to in #656?
> 
> If someone else wants to make a PR, or at least a unit test that reproduces the problem, that would be greatly appreciated.

From what I understand, looks like it. OpenSearch is taken care of cleanly on the server but the client doesn't handle it.

**Comment by erezgong** [comment] 2022-03-27 10:32
@CEHENKLE any updates?

**Comment by CEHENKLE** [comment] 2022-03-28 03:41
I pinged @mgodwan to take a look, since it seems like #656 might be where this regression came in.  I'll also do a deeper dive on Monday to see what else I can see.

Thanks,
/C

**Comment by mgodwan** [comment] 2022-03-28 12:18
* The The issue seems to be due to client expecting field discovered_master to be present in the response coming from server (required arg), but older server versions not returning it (which is expected e.g. ODFE). The issue should not be encountered when using an older client (e.g. ES 7.10 client) with opensearch but only when using opensearch client with ODFE/ES servers.

* The change was done with the first opensearch version, and before the opensearch client was launched, and this change is compatible with the older version of the client. @CEHENKLE Do we maintain backward compatibility between new versions of client, and old server versions? If yes, I see 2 options to address this:

1. Make discovered_master optional in the ClusterHealthResponse ser-de logic, and treat it as false if missing.
2. Make discovered_master from primitive boolean to `Boolean` and support null values while keeping the arg as optional.
 
I have a commit with a fix and a UT which passes after the fix for 1st solution which should address the issue: https://github.com/mgodwan/OpenSearch/commit/2df6764652e83120612f936d3d4cabf7c48bccb5 which I can create a PR for if the approach looks fine.

CC: @dblock @saratvemulapalli @CEHENKLE 

I see one more related change which can cause the same issue: https://github.com/opensearch-project/OpenSearch/commit/1c2bdd86429fe8ff5c5ea323482d40d5b6a972a4

**Comment by dblock** [comment] 2022-03-28 19:01
@mgodwan The approach in (1) looks reasonable to me! Make a PR. Thank you.

**Comment by saratvemulapalli** [comment] 2022-03-28 19:10
>@CEHENKLE Do we maintain backward compatibility between new versions of client, and old server versions? 
> 
Correct, we would like to maintain this compatibility for customers to migrate from older major versions. 
+1 to solution we have to fix the client to support backwards-compatibility and we should add tests to catch these problems in future. I'm surprised it was not caught.

**Comment by mgodwan** [comment] 2022-03-29 17:38
@dblock @saratvemulapalli  Can you help with approving merging this PR https://github.com/opensearch-project/OpenSearch/pull/2641?

**Comment by dblock** [comment] 2022-03-29 18:21
Closed via https://github.com/opensearch-project/OpenSearch/pull/2641

**Closed by dblock** 2022-03-29 18:21 UTC
Labels: bug, Clients & Libraries

**Comment by CEHENKLE** [comment] 2022-03-30 03:50
Thank you @mgodwan !  :)
