### ISSUE TITLE
[BUG] org.opensearch.indices.replication.SegmentReplicationAllocationIT.testAllocationAndRebalanceWithDisruption is flaky

### ISSUE THREAD

**Issue by backslasht** [opensearch-project/OpenSearch#13046] opened 2024-04-03 06:06 UTC
### Describe the bug

Details in https://build.ci.opensearch.org/job/gradle-check/36350/testReport/org.opensearch.indices.replication/SegmentReplicationAllocationIT/testAllocationAndRebalanceWithDisruption/

### Related component

Storage:Remote

### To Reproduce

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationAllocationIT.testAllocationAndRebalanceWithDisruption" -Dtests.seed=99CB296230F30435 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CO -Dtests.timezone=America/Argentina/Cordoba -Druntime.java=21

### Expected behavior

The test should not fail.

**Comment by peternied** [comment] 2024-04-03 15:21
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@backslasht Thanks for filing

Thanks @mch2 for volunteering to look into this issue.

**Comment by andrross** [comment] 2024-04-04 19:56
@mch2 This test case was newly added in #12656. Should we revert that PR?

**Comment by mch2** [comment] 2024-04-04 20:36
@andrross I am on board with that or at least muting this test until this is resolved, I've run this locally and the seed is reproducible, haven't yet figured out why though @Arpit-Bandejiya mind taking a look?

**Comment by ashking94** [comment] 2024-04-17 15:03
@Arpit-Bandejiya  do take a look at this if you can.

**Comment by dblock** [comment] 2024-05-03 19:50
https://github.com/opensearch-project/OpenSearch/pull/13513#issuecomment-2093668534

**Comment by mch2** [comment] 2024-05-07 21:03
@Arpit-Bandejiya wondering if you've had a chance to look at this yet. Seems to be popping up more frequently. I think we should go ahead and mute this test for now?

**Comment by reta** [comment] 2024-06-19 15:37
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14327

**Closed by reta** 2024-06-19 15:37 UTC
Labels: bug, flaky-test, Storage:Remote
