### ISSUE TITLE
[TEST BUG] SnapshotResilencyTests.testSnapshotPrimaryRelocations very slow

### ISSUE THREAD

**Issue by rmuir** [opensearch-project/OpenSearch#579] opened 2021-04-19 17:04 UTC
This test is extremely slow (hundreds of seconds). The number of nodes, indexes, or iterations should be toned down.

**Comment by harold-wang** [comment] 2021-04-23 16:16
Thanks @rmuir, can you post the log of this test?  @abbashus I would link this issue with #578.

**Comment by CEHENKLE** [comment] 2021-08-24 18:54
@abbashus assigning this to you because it's related to 578

**Comment by abbashus** [comment] 2021-08-24 18:57
Sure @CEHENKLE, will take a look.

**Comment by abbashus** [comment] 2021-08-30 06:18
Reproduced this with following command and different build envs:

```
./gardlew clean && ./gradlew ':server:test'  --no-build-cache
```

Checked the following reports for test run time at 
```
file:///<path-to-OpenSearch-repo>/server/build/reports/tests/test/classes/org.opensearch.snapshots.SnapshotResiliencyTests.html
```

| Environment                                                                                                             	| max 10 Datanodes, max 10 Shards 	| max 5 Datanodes, max 5 Shards 	|
|-------------------------------------------------------------------------------------------------------------------------	|---------------------------------	|-------------------------------	|
| Amazon Linux  (Linux 5.11.0-1016-aws)<br>- 48 core<br>- 48 Gradle workers<br>- Max JVM memory heap size 3GB<br>- JVM 14 	| 2m 0.355s                       	| 1.110s                        	|
| Mac OS X 10.15.7<br>- 12 core<br>- 12 Gradle workers<br>- Max JVM memory heap size 3GB<br>- JVM 14                      	| 2m 37.060s                      	| 1.889s                        	|

After tuning down the max datanodes down to 5 and max shards down to 5, I was able to reduce testing time by  2 minutes for both MaOS and Amazon Linux.

**Closed** 2021-08-30 17:13 UTC
Labels: bug
