### ISSUE TITLE
[BUG] FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout (Random test Failure)

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#1567] opened 2021-11-16 18:23 UTC
**Describe the bug**
Random Test Failure.   Please dig in, figure out what's wrong :(

[https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1068.log](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1068.log)
[https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1068_reports.zip](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1068_reports.zip)

**Comment by tlfeng** [comment] 2021-11-16 19:09
Most recently found in [#1541](https://github.com/opensearch-project/OpenSearch/pull/1541#issuecomment-967747854)

**Comment by Poojita-Raj** [comment] 2021-11-18 20:42
Also found in #1584

**Comment by tlfeng** [comment] 2021-12-01 04:35
The failed test is introduced by commit https://github.com/opensearch-project/OpenSearch/commit/f7e2984248f81b6bd1e0c38a3506af150da996cc

**Comment by andrross** [comment] 2021-12-07 19:04
@tlfeng Can you easily reproduce the failure?

**Comment by tlfeng** [comment] 2021-12-07 19:29
> @tlfeng Can you easily reproduce the failure?

Hi Andrew, I couldn't. Although decreasing some of the time interval can caused the assertion failed, it's not likely the same case in CI.
```
long healthyTimeoutThreshold = 100; // randomLongBetween(500, 1000);
long refreshInterval = 50; // randomLongBetween(500, 1000);
long slowLogThreshold = randomLongBetween(100, 200);
long delayBetweenChecks = 20; // 100;
```

I guess there might be 3 possible causes:
1. The wait time in the assertion statement is not enough for the code `disruptFileSystemProvider.injectIODelay.set(false);` ("Fix file system disruption") processing.
2. The file system somehow is not back to normal after the test case `testLoggingOnHungIO()` runs, because it hung the file system, but maybe didn't restore properly (https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L181).
Note for 1$2: I'm not sure if "Fix file system disruption" is a necessary step in the test, because the test case `testLoggingOnHungIO()` written by Elastic didn't restore the hanging status manually in the test case.
3. There is defect for the logic of `FileSystemFsyncHungProvider` (https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L422), and it was modified in the commit https://github.com/opensearch-project/OpenSearch/commit/f7e2984248f81b6bd1e0c38a3506af150da996cc recently.
4.

**Comment by tlfeng** [comment] 2021-12-08 05:46
Hi @Bukhtawar, do you have any thoughts about the test failure?
It can not be easily reproduced, but it failed several times in the gradle `check` task in our Jenkins CI. The most recent seems on the last Sunday in the daily "gradle check build".

**Comment by Bukhtawar** [comment] 2021-12-08 17:02
Adding more delay here should help I guess, assuming this is the only assertion failing

https://github.com/opensearch-project/OpenSearch/blob/e983facc161e8f0ee0e77ed0c51e0850e31d296d/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L239-L244

**Comment by andrross** [comment] 2021-12-08 17:30
Maybe just increase that 2x multiplier in the `waitUntil` step to 3x or 4x to give the FsHealthService a couple more chances to observe a healthy state?

Also, super minor, but I'd also remove this assertion:

https://github.com/opensearch-project/OpenSearch/blob/e983facc161e8f0ee0e77ed0c51e0850e31d296d/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L239

As long as the thing after this wait step is to do `assertEquals(HEALTHY, fsHealth.getStatus());` then you're covering this assertion and a failure will give a much better error message.

**Comment by tlfeng** [comment] 2021-12-08 18:23
Thanks @Bukhtawar and @andrross for providing suggestions on resolving the test failure.

I realized that it's a bit duplicate to have double assertion statements to check the File System health status around the 2 `waitUntil()`. That's a good point 👍 😁

Further, I'm curious is it necessary to have the steps to restore the file system status? Or just a good habit to restore the status after a test case.
Such as:
https://github.com/opensearch-project/OpenSearch/blob/e983facc161e8f0ee0e77ed0c51e0850e31d296d/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L237-L249

I noticed that in the test `testLoggingOnHungIO()`, it didn't restore the disrupted file system.
https://github.com/opensearch-project/OpenSearch/blob/e983facc161e8f0ee0e77ed0c51e0850e31d296d/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L145

**Comment by andrross** [comment] 2021-12-08 18:31
This is the critical line that must happen after each test invocation:

https://github.com/opensearch-project/OpenSearch/blob/e983facc161e8f0ee0e77ed0c51e0850e31d296d/server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java#L188

The actual disrupted filesystem is an instance local to a single test invocation, so as long as that static teardown method is called to reset the underlying static variable in PathUtils, then it doesn't matter what is done to the instance.

**Comment by andrross** [comment] 2021-12-16 17:20
@tlfeng Just came across a failure of this test in an unrelated PR. I see the updated error message, so it appears the additional retry time didn't fix it in this case.

[Gradle Check 1532](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1532.log)

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout" -Dtests.seed=3ED0AD06FBD1DA83 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCach
eSize=64m -Djava.security.manager=allow" -Dtests.locale=en-CA -Dtests.timezone=Asia/Dubai -Druntime.java=17

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/home/ubuntu/.gradle/wrapper/dists/gradle-7.3-all/dfe0rb4hnplvqkibhoc45how8/gradle-7.3/lib/plugins/gradle-testing-base-7.3.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release
org.opensearch.monitor.fs.FsHealthServiceTests > testFailsHealthOnHungIOBeyondHealthyTimeout FAILED
    java.lang.AssertionError: expected:<HEALTHY> but was:<UNHEALTHY>
        at __randomizedtesting.SeedInfo.seed([3ED0AD06FBD1DA83:BCA4F30F8F2DACCB]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.opensearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout(FsHealthServiceTests.java:243)
```

**Comment by dreamer-89** [comment] 2023-01-05 06:14
Reopened after another occurrence https://github.com/opensearch-project/OpenSearch/pull/5344#issuecomment-1371795330

**Comment by anasalkouz** [comment] 2023-12-18 22:11
Seems old one, if someone can try to reproduce it. Otherwise, we can close it.

**Comment by dreamer-89** [comment] 2023-12-20 18:54
Closing this issue as stale and no failures from flaky report https://github.com/opensearch-project/OpenSearch/issues/5031#issuecomment-1863394265.

**Closed** 2023-12-20 18:54 UTC
Labels: bug, flaky-test
