### ISSUE TITLE
[BUG] org.opensearch.index.translog.LocalTranslogTests.testWithRandomException is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#6571] opened 2023-03-07 18:05 UTC
**Describe the bug**

```
Error Message

java.lang.AssertionError: expected:<null> but was:<java.lang.RuntimeException: simulated>

Stacktrace

java.lang.AssertionError: expected:<null> but was:<java.lang.RuntimeException: simulated>
	at __randomizedtesting.SeedInfo.seed([844A5091F9BA4836:E2923B8E825EC627]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.index.translog.LocalTranslogTests.testWithRandomException(LocalTranslogTests.java:3235)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**To Reproduce**
CI build: https://build.ci.opensearch.org/job/gradle-check/12080/

**Expected behavior**
The test should pass all the time

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI (Jenkins)

**Additional context**

**Comment by nisgoel-amazon** [comment] 2024-04-24 11:29
This looks duplicate of https://github.com/opensearch-project/OpenSearch/issues/6625
Which is already fixed.
I have tested this test on local with more than 100 runs and it is passing every time

**Closed as completed** 2024-04-24 13:36 UTC
Labels: bug, flaky-test, Indexing:Replication
