### ISSUE TITLE
[BUG] Calling Create Role API Crashes OpenSearch

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/OpenSearch#1850] opened 2022-01-05 01:35 UTC
**Describe the bug**
Calling Create Role API Crashes OpenSearch.
**Note**: This issue only exists on the 1.3.0 that has log4j-core 2.17.1, doesn't exist in the 1.2.3 that has log4j-core to 2.17.0.

**To Reproduce**
1. Start a local cluster with Dashboards enabled
2. Login as admin
3. Create a role in dev console, for example
```
PUT _opendistro/_security/api/roles/test-role
{
  "cluster_permissions" : [ ],
  "index_permissions" : [
    {
      "index_patterns" : [
        "*"
      ],
      "dls" : "",
      "fls" : [ ],
      "masked_fields" : [ ],
      "allowed_actions" : [
        "indices_all"
      ]
    }
  ],
  "tenant_permissions" : [
    {
      "tenant_patterns" : [
        "test-tenant-1"
      ],
      "allowed_actions" : [
        "kibana_all_write"
      ]
    }
  ]
}
```
4. See response
```
{"statusCode":502,"error":"Bad Gateway","message":"socket hang up"}
```
5. Check the running docker container and see a fatal error
```
[2022-01-05T01:30:16,519][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [smoketestnode] fatal error in thread [opensearch[smoketestnode][generic][T#2]], exiting
java.lang.NoSuchMethodError: 'boolean org.apache.logging.log4j.spi.LoggerContextFactory.isClassLoaderDependent()'
at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:49) ~[?:?]
at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46) ~[log4j-api-2.11.1.jar:2.11.1]
at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33) ~[?:?]
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
at com.jayway.jsonpath.internal.JsonContext.<clinit>(JsonContext.java:41) ~[?:?]
at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:38) ~[?:?]
at com.jayway.jsonpath.JsonPath.parse(JsonPath.java:599) ~[?:?]
at org.opensearch.security.dlic.rest.validation.RolesValidator.validate(RolesValidator.java:54) ~[?:?]
at org.opensearch.security.dlic.rest.api.AbstractApiAction.handleApiRequest(AbstractApiAction.java:115) ~[?:?]
at org.opensearch.security.dlic.rest.api.PatchableResourceApiAction.handleApiRequest(PatchableResourceApiAction.java:253) ~[?:?]
at org.opensearch.security.dlic.rest.api.AbstractApiAction.lambda$prepareRequest$2(AbstractApiAction.java:405) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) ~[opensearch-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Expected behavior**
1. API call success and no error is shown
2. Opensearch should not crash on fatal error

**Plugins**
Security plugin

**Screenshots**
<img width="1594" alt="Screen Shot 2022-01-04 at 5 33 24 PM" src="https://user-images.githubusercontent.com/79167042/148146605-ae70ec4e-530a-43a8-a6f2-8957c0ece1cc.png">

<img width="1542" alt="Screen Shot 2022-01-04 at 5 33 40 PM" src="https://user-images.githubusercontent.com/79167042/148146616-fb9fff16-ebcc-49f8-ba9a-9657258fe035.png">

**Host/Environment (please complete the following information):**
 - OS: ubuntu

**Comment by davidlago** [comment] 2022-01-05 02:34
Just a quick observation, the error messages seems to point to version `2.11.1` of `log4j-api`:

```at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46) ~[log4j-api-2.11.1.jar:2.11.1]```

Which is not part of the distribution at `1.3.0-SNAPSHOT`, where we are using `2.17.1` instead.

**Comment by peterzhuamazon** [comment] 2022-01-05 03:00
> log4j-api

https://github.com/opensearch-project/OpenSearch/blob/1.x/buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle#L19

```
  implementation 'org.apache.logging.log4j:log4j-core:2.11.1'
```

https://github.com/opensearch-project/OpenSearch/blob/1.x/libs/core/.classpath1#L292-L298

```
<classpathentry sourcepath="/home/alpar/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.11.1/acf35297ef03716fc14e11e2978d7c749ed3f7e5/log4j-api-2.11.1-sources.jar" kind="lib" path="/home/alpar/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.11.1/268f0fe4df3eefe052b57c87ec48517d64fb2a10/log4j-api-2.11.1.jar">
		......
	<classpathentry sourcepath="/home/alpar/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.11.1/23bef4ea0494ba9fb9835df0e3e23c6883d8d545/log4j-core-2.11.1-sources.jar" kind="lib" path="/home/alpar/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.11.1/592a48674c926b01a9a747c7831bcd82a9e6d6e4/log4j-core-2.11.1.jar">
		<attributes>
```
The only reference I can find related to log4j and 2.11.1.

**Comment by davidlago** [comment] 2022-01-05 12:57
Thanks @peterzhuamazon. That 2nd one is the `log4j-api` one that pops up in the error. As we have `log4j-api` as a provided dependency in the search plugin:

```
[INFO] +- org.opensearch:opensearch:jar:1.2.4-SNAPSHOT:provided
...
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.17.1:provided
```

I'm wondering if that `2.11.1` is being provided instead and blowing things up.

**Comment by mch2** [comment] 2022-01-06 00:35
Hi @hsiang9431-amzn,
I have not been able to reproduce this issue with archives from CI & built locally.
Could you please provide a bit more info on the artifacts you used when facing this issue?  Did you build from src or pull from CI?  If built from src, do you have the specific commits of both security & opensearch you built from?

I used these versions of min/security from CI:
[min-1.3.0](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/488/linux/arm64/builds/opensearch/dist/opensearch-min-1.3.0-linux-arm64.tar.gz)
[security:1.3.0.0. ](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/488/linux/arm64/builds/opensearch/plugins/opensearch-security-1.3.0.0.zip)
I also built a min archive myself using OpenSearch 1.x branch and built/installed Security from its main branch.  

On the two files linked -
I'll update the build.gradle in testKit to correctly use the project's log4j version so the old version isn't in gradle caches, but I'm unsure how this would sneak in the final dist.

The .classpath1 file looks like an example .classpath file generated by eclipse - I don't think this is used anywhere?

**Comment by cliu123** [comment] 2022-01-06 00:52
Hi @mch2,
Both @hsiang9431-amzn and I was able to reproduce the issue with the following artifacts:
[Opensearch-min-1.3.0-SNAPSHOTS](https://artifacts.opensearch.org/snapshots/core/opensearch/1.3.0/opensearch-min-1.3.0-SNAPSHOT-linux-x64-latest.tar.gz) - Is this the same one as your artifact built on CI?
[Security 1.3.0-SNAPSHOTS](https://github.com/opensearch-project/security/suites/4842781321/artifacts/137298328).

**Comment by mch2** [comment] 2022-01-06 01:06
Thanks @cliu123 taking a look...

The min are built from the same CI but yours is a snapshot version.  CI builds a release and a snapshot at the same time and promotes them.

Where are those security artifacts built from?

**Comment by cliu123** [comment] 2022-01-06 01:08
> Where are those security artifacts built from?

Security plugin repo CI.

**Comment by mch2** [comment] 2022-01-06 01:33
I think the [opensearch-min-1.3.0 ](https://artifacts.opensearch.org/snapshots/core/opensearch/1.3.0-SNAPSHOT/opensearch-min-1.3.0-SNAPSHOT-linux-x64-latest.tar.gz)link is stale - after unzipping I can see version 2.11.1 of log4j-core and log4j-api under /lib. 

The latest from CI should be [here](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/488/linux/x64/builds/opensearch/dist/opensearch-min-1.3.0-linux-x64.tar.gz) -> which includes the correct log4j version at /lib.

**Comment by davidlago** [comment] 2022-01-06 01:36
Nice, thanks @mch2 ! Is there a link we could use in our CI file to always get the latest of  1.3.0-SNAPSHOT? like a symlink of sorts?

**Comment by mch2** [comment] 2022-01-06 01:48
@davidlago  I don't think that has been set up yet on ci.opensearch.

There is [this](https://github.com/opensearch-project/opensearch-build/pull/1378) PR that looks like the gap here to why these are not auto promoted to artifacts.opensearch.

**Comment by davidlago** [comment] 2022-01-06 02:00
This fixed the issue, [first passing build in a while](https://github.com/opensearch-project/security-dashboards-plugin/runs/4722382128?check_suite_focus=true) for the dashboards security plugin! Tempted to close this out but waiting for @hsiang9431-amzn or @cliu123 to confirm that updating the zip in their local makes the 502s go away.

**Comment by peterzhuamazon** [comment] 2022-01-06 03:11
Hi,

@mch2 @davidlago @cliu123 
The artifacts.opensearch.org has not been updated with 1.3.0 for a while.
@gaiksaya is currently having a pipeline to auto publish ci.opensearch.org artifacts to artifacts.opensearch.org.

As of now, use ci.opensearch.org related links like @mch2 says.

Thanks.

**Comment by cliu123** [comment] 2022-01-06 18:00
@mch2 @peterzhuamazon Thanks for help! 
I've used the artifact on CI that @mch2 provided to test it again, and have confirmed the issue doesn't exist. 
@mch2 Please feel free to close this issue. I don't have the permission.

**Closed** 2022-01-06 18:06 UTC
