### ISSUE TITLE
[BUG] Unable to flip feature flags defined in FeatureFlags.java

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch#9564] opened 2023-08-25 23:58 UTC
**Describe the bug**
> A clear and concise description of what the bug is.

The feature flags used for experimental are defined [here](https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L27-L63). This below [example](https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L103) creates an setting static object with the feature flag name and default value.

```
    public static final Setting<Boolean> IDENTITY_SETTING = Setting.boolSetting(IDENTITY, false, Property.NodeScope);
```

However, if the feature flag is not specified as an env variable or written in the yml file, the [FeatureFlags.isEnabled method](https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L85-L91) does not read the value from these static settings and instead sets to 'false' by default.

```
    /**
     * Used to test feature flags whose values are expected to be booleans.
     * This method returns true if the value is "true" (case-insensitive),
     * and false otherwise.
     */
    public static boolean isEnabled(String featureFlagName) {
        if ("true".equalsIgnoreCase(System.getProperty(featureFlagName))) {
            // TODO: Remove the if condition once FeatureFlags are only supported via opensearch.yml
            return true;
        }

        return settings != null && settings.getAsBoolean(featureFlagName, false);
    }
```

Because these feature flag settings are never initialized / registered during node boostrap, it causes the difficulty when adding a static setting with the default value of `true` to keep the feature enabled but still gated behind the flag.

For [example on node.java](https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/node/Node.java#L467-L473), if the default value on `FeatureFlags.IDENTITY` is set to `true`, the FeatureFlags.isEnabled will always return `false`.

```
    final Settings settings = pluginsService.updatedSettings();

    // Ensure to initialize Feature Flags via the settings from opensearch.yml
    FeatureFlags.initializeFeatureFlags(settings);

    final List<IdentityPlugin> identityPlugins = new ArrayList<>();
    if (FeatureFlags.isEnabled(FeatureFlags.IDENTITY)) {
        ...
       # this condition will never entered
    }
```
**To Reproduce**
1. Set any feature flag (for example IDENTITY_SETTING) default value to `true` https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L103
2. Add logs around FeatureFlags.isEnabled method usage during node bootstrap https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/node/Node.java#L467-L473

```
    # Example logging
    logger.info("louis-feature-flag-test: " + FeatureFlags.IDENTITY + " value: " + settings.get(FeatureFlags.IDENTITY));
    if (FeatureFlags.isEnabled(FeatureFlags.IDENTITY)) {
        // If identity is enabled load plugins implementing the extension point
        logger.info("Identity on so found plugins implementing: " + pluginsService.filterPlugins(IdentityPlugin.class).toString());
        identityPlugins.addAll(pluginsService.filterPlugins(IdentityPlugin.class));
    }
```
3. Start cluster
```
./gradlew run --debug-server-jvm --info 
```
```
[2023-08-25T12:46:29,937][INFO ][o.o.n.Node               ] [runTask-0] louis-feature-flag-test: opensearch.experimental.feature.identity.enabled value: null
[2023-08-25T12:46:29,938][INFO ][o.o.n.Node               ] [runTask-0] louis-feature-flag-test: opensearch.experimental.feature.extensions.enabled value: null
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Some options here
1. **Disallow the use case of adding a static setting with the default value of 'true' in order to keep the feature enabled but still gated behind the flag**: We could limit the feature flag's functionality by concealing the default_value during static setting construction. The default value is then set to always `false`. On public doc and java doc, we should explictly mention that flags are required to be removed when you want to enable the feature.
2. FeatureFlags.isEnabled reads the setting object's real default_value.

**Comment by dblock** [comment] 2023-08-28 19:23
I think that a feature flag that allows a default value should ... respect that default value, so this is a real bug. Do you think you can turn it into a unit test?

**Comment by jayeshathila** [comment] 2023-09-01 11:13
I guess we can use the existing [BUILT_IN_FEATURE_FLAGS](https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java#L35) set and modify [isEnabled](https://github.com/opensearch-project/OpenSearch/blob/8cfde6ca4031047b4f7e5ecf706e434e1c535567/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L85-L91) .

The behaviour of `settings.get(FeatureFlags.IDENTITY)`  to return null is seeming correct only, we only need to modify the isEnable function.

Proposal draft PR: https://github.com/opensearch-project/OpenSearch/pull/9691 [Pending UT and log line removal]

Thoughts ?

**Comment by dblock** [comment] 2023-09-05 14:58
I am not sure, feels like a workaround for the problem instead of fixing the actual problem.

I'd really start by writing tests that reproduce the various states of feature flags, then it becomes easy to try and produce a fix that works in all cases.

**Comment by jayeshathila** [comment] 2023-09-05 15:41
@dblock, can confirm what is expectation out of the below ones:

1. UT for `isEnabled`, which tests for all the possibility of returned values and hence covering this use case of default value (in public static fields) being true as well.

2. UT for `public static` feature flags and their different values should be returned from `isEnabled`.

3. General UT which will test settings `Setting.boolSetting`, `floatSetting` etc ?

**Comment by dblock** [comment] 2023-09-05 15:56
I don't have the answers to these without digging deep into what's supposed to be returned or existing tests. I was noting that you found one case where the flag doesn't work as one would expect, so I was commenting on wanting tests (some may exist) that cover all permutations.

PS: Do note that settings can also be declared in plugins.

**Comment by noCharger** [comment] 2023-09-05 16:46
```
        if (settings != null && FeatureFlagSettings.FEATURE_FLAG_MAPPING.get(featureFlagName) != null) {
            defaultValue = (boolean) FeatureFlagSettings.FEATURE_FLAG_MAPPING.get(featureFlagName).getDefault(settings);
        }
```

If I understand correctly, `getDefault(settings)` will retrieve the value of a setting from `settings`, which does not contain FeatureFlagSettings.FEATURE_FLAG_MAPPING. As a result, it will still return null.

**Comment by jayeshathila** [comment] 2023-09-06 06:59
@noCharger  No `getDefaults` implementation is little un-intuitive in this case, it will return the default value of `FeatureFlagSettings.FEATURE_FLAG_MAPPING` . 

[getDefaultRaw implementation](https://github.com/jayeshathila/OpenSearch/blob/78eea275a3e1812a008e815d846ca871d7f09d20/server/src/main/java/org/opensearch/common/settings/Setting.java#L440)
```
    public String getDefault(Settings settings) {
        return defaultValue.apply(settings);
    }
```

here ^  the argument (`settings` ) value will be ignored because the implementation of defaultValue function is no-op for all practical purposes and this method will return defaultValue of featureFlag.

The [defaultValue function implementation] while initializing the featureFlag `Setting.boolSetting` (https://github.com/jayeshathila/OpenSearch/blob/78eea275a3e1812a008e815d846ca871d7f09d20/server/src/main/java/org/opensearch/common/settings/Setting.java#L2013) is
```
 (s) -> Boolean.toString(defaultValue)
```

**Comment by jayeshathila** [comment] 2023-09-19 03:11
@msfroh Sure, please assign it to me.

**Comment by cwperks** [comment] 2024-04-03 01:03
Closing this issue as https://github.com/opensearch-project/OpenSearch/pull/12849 was merged.

**Closed by cwperks** 2024-04-03 01:03 UTC
Labels: bug, good first issue
