### ISSUE TITLE
[BUG] After enabling zstd codec memory usage increased drastically

### ISSUE THREAD

**Issue by shamil** [opensearch-project/OpenSearch#9312] opened 2023-08-14 18:13 UTC
**Describe the bug**

After enabling `zstd` codec memory usage increased drastically.

**To Reproduce**

1. Create index with `zstd` codec 
2. Ingest data to the index, we have around 300GB+ per index
3. Comparing memory usage before and after the index with `zstd`  memory usage increases drastically

**Expected behavior**

Memory usage doesn't increase that drastically

**Screenshots**

Here are memory graphs for 2 nodes from our cluster, it's clearly visible memory usage after enabling `zstd` codec and new indexes created (on 8/10). The memory usage is from the OS metrics. 

![image](https://github.com/opensearch-project/OpenSearch/assets/655447/d70e9ab3-0258-4a46-94f3-201a16937db2)

**Host/Environment (please complete the following information):**
 - OS: Ubunttu 22.04
 - Version 2.9.0

**Comment by mgodwan** [comment] 2023-08-17 11:52
@shamil I observed similar behaviour when using ZSTD codec.
This can be related to https://github.com/opensearch-project/OpenSearch/pull/9403

**Comment by nknize** [comment] 2023-08-17 17:45
🤦🏻‍♂️ Oye. So I'm kind of confused here. Zstd codec [was sandboxed](https://github.com/opensearch-project/OpenSearch/pull/3577) for almost [three months](https://github.com/opensearch-project/OpenSearch/pull/7908). Was this never used while sandboxed such that this regression could be benchmarked and tested before promoting as a LTS feature?

**Comment by nknize** [comment] 2023-08-17 18:09
FTR introducing a core feature that relies on native libraries is SUPER trappy. I didn't realize the native dependencies when I reviewed the first experimental PR. Our portability could easily be burned by incompatibilities in glibc (we ran into this on kNN w/ FAISS not building on M1 macbooks). We need to seriously think about moving all zstd out as optional plugins? Perhaps we even cut a patch release that deprecates this w/ a `DeprecationLogger` warning that says `zstd` compression will be moving to an optional plugin in the next release.

**Comment by ict-one-nl** [comment] 2023-08-17 18:41
What is the solution? To pull the future?

**Comment by reta** [comment] 2023-08-17 18:58
> Hmmm.... why not [switch to direct memory](https://github.com/opensearch-project/OpenSearch/pull/9403/files#r1297561878) and keep the pressure off the heap?
> 
> ```
> try (ZstdDictDecompress dictDecompress = new ZstdDictDecompress(ByteBuffer.wrap(bytes.bytes, 0, dictLength))) {
> ```

It looks like the `ZstdDictDecompress` was leaking native memory, the heap seems to be fine (but we could double check for sure).

**Comment by ict-one-nl** [comment] 2023-08-17 22:35
What about current users, will demoting the feature break the cluster unless they enable the experimental feature? Maybe provide upgrade instructions

**Comment by dblock** [comment] 2023-09-08 17:20
@andrross should we close this? I believe the issue itself is fixed in 2.10

**Comment by andrross** [comment] 2023-09-08 17:26
The fix for this will be available in the 2.10 release

**Closed by andrross** 2023-09-08 17:26 UTC
Labels: bug, untriaged, Performance, storage

**Comment by dblock** [comment] 2023-09-08 18:14
> What about current users, will demoting the feature break the cluster unless they enable the experimental feature? Maybe provide upgrade instructions

With https://github.com/opensearch-project/opensearch-build/issues/3971 this won't be the case for users of the official distribution.
