### ISSUE TITLE
An internal server error occurred

### ISSUE THREAD

**Issue by NagaTeja12** [opensearch-project/OpenSearch#13562] opened 2024-05-06 15:25 UTC
### Describe the bug

Hello All , 

We are facing issue while accessing the logs for our Tenant .Getting the below error 

Error fetching fields for index pattern users-cont-logs* (ID: 28dce7a0-f587-11ee-95bb-35e054d525d9)
Error: An internal server error occurred
    at hostname.com/6391/bundles/plugin/data/data.plugin.js:1:971138
Error
    at Fetch._callee3$ (hostname.com/6391/bundles/core/core.entry.js:15:608217)
    at tryCatch (hostname.com/6391/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2179)
    at Generator._invoke (hostname.com/6391/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:1802)
    at Generator.next (hostname.com/6391/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2954)
    at fetch_asyncGeneratorStep (hostname.com/6391/bundles/core/core.entry.js:15:601129)
    at _next (hostname.com/6391/bundles/core/core.entry.js:15:601445)

The other Tenant have no issues , we were able to fetch the logs and cluster health was always in Green status and there are no unassigned shards . Only this tenant users-cont-logs is having the issues .
The same tenant with the similar configuration is working fine on the other cluster which is deployed in another environment (DEV)

Hoping to find a solution for this 

Thanks in Advance.

### Related component

Cluster Manager

### Expected behavior

It is working on another cluster in diff env

### Additional Details

![Capture](https://github.com/opensearch-project/OpenSearch/assets/144242804/1dd6ee62-2417-413c-bdf5-8836079cfa1a)
![Capture-1](https://github.com/opensearch-project/OpenSearch/assets/144242804/40eead66-c000-4dc6-a7a1-e4db9d30f806)

**Comment by dblock** [comment] 2024-05-07 06:50
@NagaTeja12 Is this consistently reproduced? Which version(s) of the software? 

Look at the server side logs, there should be a detailed error behind the 500, which is what we'll need to figure out what caused it.

**Comment by NagaTeja12** [comment] 2024-05-07 14:41
Hello @dblock , Thanks for looking into this .

I am attaching the logs from the client , master and data pods .
[Logs.txt](https://github.com/opensearch-project/OpenSearch/files/15237068/Logs.txt)

What confusing is that , we can able to see the logs for all the Tenants except this USERS-CONT-LOGS* . It was configured the same like others but unable to view anything on the dashboard .
Let me know if you need more info required to troubleshoot this .

Thanks Again!

**Comment by dblock** [comment] 2024-05-08 08:44
Errors like "Exception during establishing a SSL connection: java.net.SocketException: Connection reset" usually mean bad connectivity or bad SSL certificates. Google gives plenty of threads that have similar errors with no resolution (e.g. https://forum.search-guard.com/t/exception-during-establishing-a-ssl-connection-java-net-socketexception-connection-reset/1902/9). This is almost certainly nothing to do with the software itself and everything to do with the way the tenant's networking is setup.

**Comment by rwali-aws** [comment] 2024-05-08 15:50
[Triage - attendees [1](https://github.com/rwali-aws) [2](https://github.com/rahulkarajgikar) [3](https://github.com/rajiv-kv)]

Thanks for filing this issue. As called out by @dblock, it looks like the issue is related to client side configuration more than anything on server side. Closing for now, feel free to reopen with additional info in case you disagree

**Closed by rwali-aws** 2024-05-08 15:50 UTC
Labels: bug, Cluster Manager
