### ISSUE TITLE
[BUG] aggregation on nested field returns incorrect result

### ISSUE THREAD

**Issue by LantaoJin** [opensearch-project/OpenSearch#14347] opened 2024-06-14 13:27 UTC
### Describe the bug

Aggregation `value_count` on field of `nested` type returns incorrect result. This issue only happens on `nested` type, `object` type without `nested` looks fine.

### Related component

Search:Aggregations

### To Reproduce

Repro:
```
# create an test index with nested field
PUT test_nested_field_index
{
  "mappings" : {
    "properties": {
      "patients": { 
        "type" : "nested"
      }
    }
  }
}
# add some testing data
PUT test_nested_field_index/_doc/100
{ 
  "patients": [ 
    {"name" : "John Doe", "age" : 56, "smoker" : true},
    {"name" : "Mary Major", "age" : 85, "smoker" : false}
  ] 
}
# value_count should return 2 instead of 0
GET test_nested_field_index/_search
{
  "size": 0,
  "aggs": {
    "count_patients_name": {
      "value_count": {
        "field": "patients.name.keyword"
      }
    }
  }
}
```

### Expected behavior

`value_count` should return 2 instead of 0

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Mac
 - Version 2.14

**Additional context**

**Comment by mch2** [comment] 2024-06-26 16:15
possibly related - https://github.com/opensearch-project/OpenSearch/pull/13324 / https://github.com/opensearch-project/OpenSearch/pull/14208

**Comment by jed326** [comment] 2024-06-26 16:38
Also, I think in order to interact with nested fields in an aggregation, a nested aggregation must be used. See: https://opensearch.org/docs/latest/aggregations/bucket/nested/

**Comment by kkewwei** [comment] 2024-06-28 03:16
@jed326, @mch2, I test this, it'ok, it seems not a problem.
```
GET test_nested_field_index/_search
{
   "aggs": {
      "patients1": {
         "nested": {
            "path": "patients"
         },
         "aggs": {
            "aggs1": {
               "value_count": {
                  "field": "patients.name.keyword"
               }
            }
         }
      }
   }
}
```
<img width="212" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/16730433/a4a784a2-0de9-4937-b445-40c125f4b434">

**Comment by jed326** [comment] 2024-06-28 03:20
Thanks @kkewwei! I also took at look at this, I think the problem is the nested aggregation was not used in the original query. I'm going to close this issue for now, @LantaoJin please re-open if there's any other issues here, thanks!

**Closed by jed326** 2024-06-28 03:20 UTC
Labels: bug, Search:Aggregations, needs more info
