### ISSUE TITLE
RemoteStoreMultipartIT.testStaleCommitDeletionWithInvokeFlush test failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#8786] opened 2023-07-19 20:15 UTC
https://github.com/opensearch-project/OpenSearch/pull/8636#issuecomment-1642663618

https://build.ci.opensearch.org/job/gradle-check/20540/consoleFull

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.multipart.RemoteStoreMultipartIT.testStaleCommitDeletionWithInvokeFlush" -Dtests.seed=AEB0C13EAF20980F -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-KW -Dtests.timezone=Australia/Darwin -Druntime.java=20

org.opensearch.remotestore.multipart.RemoteStoreMultipartIT > testStaleCommitDeletionWithInvokeFlush FAILED
    java.lang.AssertionError: 
    Expected: is one of {<7>, <8>}
         but: was <9>
        at __randomizedtesting.SeedInfo.seed([AEB0C13EAF20980F:FA11C17489AC724]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.opensearch.remotestore.RemoteStoreIT.lambda$testStaleCommitDeletionWithInvokeFlush$4(RemoteStoreIT.java:306)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1083)
        at org.opensearch.remotestore.RemoteStoreIT.testStaleCommitDeletionWithInvokeFlush(RemoteStoreIT.java:303)
```

**Comment by sachinpkale** [comment] 2023-07-20 16:35
Muting the test for now.

**Comment by sachinpkale** [comment] 2023-07-20 16:39
Muted as part of: https://github.com/opensearch-project/OpenSearch/pull/8484

**Comment by sachinpkale** [comment] 2023-07-20 16:39
Duplicate of: https://github.com/opensearch-project/OpenSearch/issues/8658

**Closed by sachinpkale** 2023-07-20 16:39 UTC
Labels: bug, distributed framework, flaky-test
