### ISSUE TITLE
[BUG] Flaky test failure - org.opensearch.blocks.SimpleBlocksIT > testAddBlockWhileDeletingIndices

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#2442] opened 2022-03-11 06:32 UTC
**Describe the bug**
Seen in https://github.com/opensearch-project/OpenSearch/pull/2438#issuecomment-1064807138

Gradle run result:
[Log 3254](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3254.log)
[Reports 3254](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3254_reports.zip)
**To Reproduce**
I can't reproduce it locally. 🙂
The below shows in the log of Gradle check.
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.blocks.SimpleBlocksIT.testAddBlockWhileDeletingIndices" -Dtests.seed=EF2BD3D9D42CE8CA -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-LB -Dtests.timezone=Asia/Manila -Druntime.java=17

org.opensearch.blocks.SimpleBlocksIT > testAddBlockWhileDeletingIndices FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=732, name=Thread-16, state=RUNNABLE, group=TGRP-SimpleBlocksIT]

        Caused by:
        java.lang.AssertionError: 
        Expected: an instance of org.opensearch.index.IndexNotFoundException
             but: <ProcessClusterEventTimeoutException[failed to process cluster event (delete-index [[glwvxoqqaa/i2W7ssjoTUeQ4iwAk6ARBQ]]) within 30s]> is a org.opensearch.cluster.metadata.ProcessClusterEventTimeoutException
            at __randomizedtesting.SeedInfo.seed([EF2BD3D9D42CE8CA]:0)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:964)
            at org.junit.Assert.assertThat(Assert.java:930)
            at org.opensearch.blocks.SimpleBlocksIT.lambda$testAddBlockWhileDeletingIndices$14(SimpleBlocksIT.java:483)
            at org.opensearch.blocks.SimpleBlocksIT.lambda$testAddBlockWhileDeletingIndices$15(SimpleBlocksIT.java:498)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=734, name=Thread-18, state=RUNNABLE, group=TGRP-SimpleBlocksIT]

        Caused by:
        java.lang.AssertionError: 
        Expected: an instance of org.opensearch.index.IndexNotFoundException
             but: <ProcessClusterEventTimeoutException[failed to process cluster event (delete-index [[pfoumeuzfk/SuaajRD-SWqAsgyGa_h31Q]]) within 30s]> is a org.opensearch.cluster.metadata.ProcessClusterEventTimeoutException
            at __randomizedtesting.SeedInfo.seed([EF2BD3D9D42CE8CA]:0)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:964)
            at org.junit.Assert.assertThat(Assert.java:930)
            at org.opensearch.blocks.SimpleBlocksIT.lambda$testAddBlockWhileDeletingIndices$14(SimpleBlocksIT.java:483)
            at org.opensearch.blocks.SimpleBlocksIT.lambda$testAddBlockWhileDeletingIndices$15(SimpleBlocksIT.java:498)
```
**Expected behavior**
The test passes.

**Plugins**
none.

**Screenshots**
none.

**Host/Environment (please complete the following information):**

**Additional context**
Occurred since Mar.10th, 2022.

**Comment by ankitkala** [comment] 2023-11-23 11:17
Closing as duplicate of https://github.com/opensearch-project/OpenSearch/issues/2472

**Closed by ankitkala** 2023-11-23 11:17 UTC
Labels: bug, flaky-test
