### ISSUE TITLE
[BUG] Cannot resolve symbol 'RestStatus'

### ISSUE THREAD

**Issue by luckyyaxianzhi** [opensearch-project/OpenSearch#13886] opened 2024-05-30 05:47 UTC
### Describe the bug
<dependency>
    <groupId>org.opensearch.client</groupId>
    <artifactId>spring-data-opensearch</artifactId>
    <version>1.4.0</version>
</dependency>

![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/8b381627-0fa6-4989-96d4-10aa0816b324)
![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/f6724e65-32a6-46db-96fc-81b378c31023)

### Related component

Clients

### Expected behavior

no error

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment] 2024-06-03 12:07
It's likely something to do with the setup of your dependencies, [RestStatus is here](https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java).

I'll close this, but feel free to comment with repro steps, and/or post your code to a GitHub repo that shows the failure if you're stuck. The public Slack `clients` channel is also a good place to ask this.

**Closed by dblock** 2024-06-03 12:07 UTC
Labels: bug, untriaged, Clients

**Comment by luckyyaxianzhi** [comment] 2024-06-04 01:57
@dblock 
Thank you for your answer！
What I want to ask is, why RestStatus is a class, not java. In this jar, other classes are java, not class

![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/29a811fe-2d0d-4e01-8ac0-e83384eadb6b)
![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/85d09d0e-8d4a-4eab-965d-90995fc8479f)

pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.0</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>spring-data-opensearch-starter</artifactId>
			<version>1.4.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
`

**Comment by dblock** [comment] 2024-06-05 18:04
@reta do you know what changed?

**Comment by reta** [comment] 2024-06-05 18:07
> @reta do you know what changed?

Oh, it was moved to different package @dblock :(

**Comment by dblock** [comment] 2024-06-05 19:14
> > @reta do you know what changed?
> 
> Oh, it was moved to different package @dblock :(

I am confused. Where? When?

https://github.com/opensearch-project/OpenSearch/blob/2.11/libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java

https://github.com/opensearch-project/OpenSearch/blob/2.14/libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java

**Comment by reta** [comment] 2024-06-05 19:41
Oh sorry @dblock , it was moved in 2.10.0, I haven't checked the full issue details.

**Comment by dblock** [comment] 2024-06-05 20:55
https://github.com/opensearch-project/OpenSearch/blob/2.9/libs/core/src/main/java/org/opensearch/rest/RestStatus.java

**Comment by dblock** [comment] 2024-06-05 20:56
@luckyyaxianzhi The java/class thing is a red herring, `RestStatus` is an enum, so it shows up correctly.

**Comment by luckyyaxianzhi** [comment] 2024-06-06 01:35
@dblock 
    Thank you for your answer！
    So what should I do so that I don’t get an error?
    The same IDE, there is no error when using 2.11.1

**Comment by dblock** [comment] 2024-06-07 14:41
What do you see in your IDE with 2.11.1 vs. 2.14 for `RestStatus`?

**Comment by luckyyaxianzhi** [comment] 2024-06-11 07:57
2.11.1
![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/798da8f9-c260-470f-8d1d-643fbd4c1fcb)
2.14
![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/2dc2d996-c02e-4b73-94b4-a982033dc131)

**Comment by dblock** [comment] 2024-06-11 12:55
They look identical, what am I missing @luckyyaxianzhi ?

**Comment by luckyyaxianzhi** [comment] 2024-06-12 00:51
Why is 2.14 a RestStatus.class file, and 2.11.1 is a RestStatus file without the .class suffix?
What I hope is that 2.14 is also a RestStatus file without the .class suffix.

**Comment by dblock** [comment] 2024-06-12 14:39
> Why is 2.14 a RestStatus.class file, and 2.11.1 is a RestStatus file without the .class suffix?

I don't know. Note though that your screenshot is cut off and I can't see this.

Going back to the problem, you're saying that your project's build works with 2.11 but not 2.14. Put a complete project up on GitHub that reproduces the problem (a branch that uses 2.11 where I can type `./gradlew build` and it works, and a branch that uses 2.14 where I can type `./gradlew build` and it doesn't work), and I can try to take a look.

**Comment by luckyyaxianzhi** [comment] 2024-06-17 08:28
@dblock  Why is 2.14 a RestStatus.class file, and ReportingService is a .java file
![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/b964ebc3-bfab-4d56-896e-8c5884a4dae9)
![image](https://github.com/opensearch-project/OpenSearch/assets/106720731/0dba9363-7296-4720-9f15-36266fad1947)

**Comment by dblock** [comment] 2024-06-17 14:39
> @dblock Why is 2.14 a RestStatus.class file, and ReportingService is a .java file

I don't know how the IDE resolves references, but this doesn't seem to be the real problem. Happy to help resolve the actual problem of building the project if you can put up a repro.

**Comment by mcc0393** [comment] 2024-08-03 22:39
I'm experiencing the same issue with RestStatus not being resolved in my project, even though I can see it in the library. I'm using IntelliJ IDEA, and I’ve tried various solutions, including clearing Gradle's cache, re-downloading dependencies multiple times, and cleaning the IDE's cache.

When I use OpenSearch 2.11.1, the problem is resolved, but it persists with versions 2.15 and 2.13. I'm not sure if this is related to how IntelliJ resolves references or if it’s something else in my project setup. Any further guidance or steps to reproduce would be greatly appreciated.

Thanks!

**Comment by asbajwa5190** [comment] 2024-09-19 16:34
Hi, I am also facing similar issue as mentioned by others. RestStatus is not getting resolved when using opensearch-rest-high-level-client dependecy for version 2.12.0 and above. It works fine for version 2.11.0. I am using IntelliJ.

Could someone please suggest, how to resolve this issue?

Thanks!

**Comment by mcc0393** [comment] 2024-09-19 16:51
Hi, my conclusion was that the problem was associated with IntelIj. I recommend using another IDE or trying again with the latest versions of IntelIj.
