### ISSUE TITLE
[BUG] search_phase_execution_exception after upgrading to OpenSearch

### ISSUE THREAD

**Issue by MadhavVij** [opensearch-project/OpenSearch#1513] opened 2021-11-05 13:43 UTC
**Describe the bug**
After we upgraded from Elasticsearch cluster to Opensearch (1.0) on AWS, we started getting the following error for some of our queries:
`RequestError(400, 'search_phase_execution_exception', 'failed to create query: field expansion matches too many fields, limit: 1024, got: 1667')
`
We tried changing the max_expansion_clause under AWS Opensearch cluster settings but that didn't work either.

**To Reproduce**
1. Perform search on Elasticsearch (AWS service) to confirm that the results appear without any errors.
2. Click on Upgrade to Opensearch in AWS Console dashboard.
3. After the update is completed, try the search again. This time Opensearch returns error `search_phase_execution_exception `

**Expected behavior**
The upgrade should not change the behavior of search and behaves the same as on AWS Elasticsearch.

**Plugins**
No external plugins installed.

**Host/Environment (please complete the following information):**
 - AWS Elasticsearch -> 7.8
 - AWS Opensearch upgraded -> 1.0

**Comment by Rishikesh1159** [comment] 2021-11-05 17:55
I will look into this.

**Comment by Rishikesh1159** [comment] 2021-11-11 21:31
@MadhavVij in order to reproduce issue, can you provide more information about search queries (like sample queries) which are failing and information about data (like sample dataset or size and configuration)? Also are you using OpenSearch Dashboards as client or any different tool?

**Comment by Rishikesh1159** [comment] 2021-11-15 05:44
@MadhavVij did you try increasing value of "max_clause_count" under Advance Cluster Setting of Cluster Configuration in your AWS OpenSearch Console?

**Comment by MadhavVij** [comment] 2021-11-15 14:39
All search queries which are failing are Multi-Match queries (some are wrapped in nested queries) and then combined using DisMax query.

Example:
```
query_1 = {
                    "nested": {
                        "path": nasted_field_path,
                        "ignore_unmapped": True,
                        "query": {
                            "multi_match": {
                                "query": query,
                                "fields": [nested_field], <- keyword field
                                "type": "phrase",
                            }
                        },
                    }
                }

query_2 = "query": {
                            "multi_match": {
                                "query": query,
                                "fields": [nested_field], <- keyword field
                                "type": "phrase",
                            }
                        }
query_object = DisMax(queries=[query_1, query_2])

```

Note: The query type in the example is phrase, but we see the error with the default query type as well.


These queries were running without any issues with Elasticsearch. We did change the max_clause_count from 1024 to 2048 a while back (on Elasticsearch) when we actually were running multiple clauses (more than 1024).
Since then we reduced our query clauses and never seen this error until upgrading to OpenSearch.

Screenshot of error (Chrome Dev Tools):
<img width="832" alt="Screen Shot 2021-11-15 at 09 25 56" src="https://user-images.githubusercontent.com/8644248/141800168-3a528299-df8a-48f9-a3c2-e9de1a0a3109.png">

**Comment by matthewdeanmartin** [comment] 2021-11-15 15:14
@Rishikesh1159  - I work with Madhav. We've attempted to increase the max_clause_count both via the AWS console and with Terraform. Neither appear to have any effect on the cluster, but the console reports the higher max_clause_count.

**Comment by Rishikesh1159** [comment] 2021-11-16 00:53
@MadhavVij @matthewdeanmartin - This seems to be an issue with the AWS OpenSearch Service offering, please open a ticket against AWS OpenSearch team.  [AWS support](https://console.aws.amazon.com/support/home#/case/create?issueType=technical) is the right place to get assistance with Amazon OpenSearch Service.

**Comment by MadhavVij** [comment] 2021-11-16 18:40
@Rishikesh1159  Thanks for the guidance, I have opened an issue with AWS Support team.

**Comment by kartg** [comment] 2021-11-17 18:38
Closing this out

**Closed by kartg** 2021-11-17 18:38 UTC
Labels: bug, Indexing & Search

**Comment by jackson-theisen** [comment] 2021-12-10 19:12
@matthewdeanmartin @Rishikesh1159 I am running into the exact same issue. Setting the config via console or Terraform results in the value being reflected as you expect in the console, but running a `GET _cluster/settings?include_defaults=true` in dev tools shows that the config doesn't actually get updated. Confirmed and reproduced multiple times. A blue/green deployment after setting the config doesn't solve the problem either. 

I opened a support ticket with AWS but haven't heard back. I'm curious if you have heard anything and know if this issue is being tracked anywhere?

**Comment by matthewdeanmartin** [comment] 2021-12-10 22:14
@jackson-theisen  A support person took the bug, an engineer confirmed it is an issue and they said it is now in their backlog to fix. We downgraded our instance to the non-OpenSearch instance. We were lucky that this was only a dev instance, so destroying it was merely inconvenient. 

Thanks for filing a bug with them, hopefully it will get some priority if they see several people have this issue.
