### ISSUE TITLE
[BUG] more informative error messages for double slashes in API call URLs

### ISSUE THREAD

**Issue by pkalliok-aiven** [opensearch-project/OpenSearch#1499] opened 2021-11-03 10:06 UTC
**Describe the bug**

If you request (by accident?) a URL with an empty index name, you get a pretty random answer:
```
$ curl -X PUT -H 'Content-type: application/json' localhost:9200//_cluster/settings?pretty -d '{}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "string_index_out_of_bounds_exception",
        "reason" : "String index out of range: 0"
      }
    ],
    "type" : "string_index_out_of_bounds_exception",
    "reason" : "String index out of range: 0"
  },
  "status" : 500
}
```

It would be better to explicitly complain about the double slash or empty index component, I suggest the following error message:
> { "status": 400, "error": { "reason": "empty string is an invalid index name (do you have a double slash in the URL by accident?)" } }

**To Reproduce**
1. start OpenSearch locally
2. curl -X PUT -H 'Content-type: application/json' localhost:9200//anything/manything?pretty -d '{}'

**Expected behavior**
A 400 error with a descriptive error message.

**Comment by meghasaik** [comment] 2021-11-05 17:57
Picking this up

**Comment by meghasaik** [comment] 2021-11-12 17:02
Was able to reproduce the bug by using the steps mentioned by user.

**Comment by kartg** [comment] 2021-11-24 18:50
Looks like all of the related changes are merged. Closing this issue out.

**Closed by kartg** 2021-11-24 18:50 UTC
Labels: bug, distributed framework
