### ISSUE TITLE
OpenSearch Coordinating Nodes memory exhaustion after upgrade 2.9 to 2.12

### ISSUE THREAD

**Issue by rlevytskyi** [opensearch-project/OpenSearch#12455] opened 2024-02-26 08:46 UTC
### Describe the bug

Hello OpenSearch Team,
We’ve just updated our OpenSearch cluster from version 2.9.0 to 2.12.0.
Among other issues, we’ve noticed that Opensearch coordinating node is now consuming all the heap it is provided with.

### Related component

Other

### To Reproduce

1. Have an OpenSearch cluster version 2.9
2. Upgrade it to 2.12
3. Provide coordinating node with 18 GB heap instead of 4GB
4. See JVM eats all it get.

### Expected behavior

We didn't expect significant memory usage increase after upgrade

### Additional Details

**Plugins**
- security

**Screenshots**
Please note JVM young is high now
![image](https://github.com/opensearch-project/OpenSearch/assets/131670547/9360d974-0c5a-410a-a67f-5dfcdd0df633)

**Host/Environment (please complete the following information):**
 - OS: Oracle Linux 8.9
 - OS: Docker image opensearchproject/opensearch-dashboards:2.12.0

**Comment by peternied** [comment] 2024-02-28 16:39
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/Mahima081)]
@rlevytskyi Thank for filing, as there we don't have enough details to act on this issue.  Without a root cause its hard to know how this would be addressed.  It looks like this is directly related to [1] and we are going to close this issue to funnel discussion in this space to a single location.

- [1] https://github.com/opensearch-project/OpenSearch/issues/12454

**Closed by peternied** 2024-02-28 16:39 UTC
Labels: bug, untriaged, Other
