### ISSUE TITLE
[BUG] org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}} is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#10046] opened 2023-09-14 14:15 UTC
**Describe the bug**
The test case org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}} is flaky:

```
org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}}

java.lang.AssertionError: 
Expected: a value less than or equal to <4L>
     but: <5L> was greater than <4L>
	at __randomizedtesting.SeedInfo.seed([D30D5DEAC663DE87:9ECE7E7BADC6DF04]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples(DiversifiedSamplerIT.java:248)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
- https://build.ci.opensearch.org/job/gradle-check/25586/
- https://build.ci.opensearch.org/job/gradle-check/25543/
- 
**Expected behavior**
Test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**

**Comment by dblock** [comment] 2023-10-02 20:31
https://github.com/opensearch-project/OpenSearch/pull/10256#issuecomment-1743344241

**Comment by andrross** [comment] 2023-10-05 22:16
https://github.com/opensearch-project/OpenSearch/pull/10388#issuecomment-1748018309

**Comment by ashking94** [comment] 2023-10-07 11:30
https://github.com/opensearch-project/OpenSearch/pull/10492#issuecomment-1751686146

**Comment by shwetathareja** [comment] 2023-10-19 05:07
https://github.com/opensearch-project/OpenSearch/pull/10711#issuecomment-1769877683 - [org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/28370/testReport/junit/org.opensearch.search.aggregations.bucket/DiversifiedSamplerIT/testNestedSamples__p0___search_concurrent_segment_search_enabled___true___/)

**Comment by amkhar** [comment] 2023-10-20 09:29
https://github.com/opensearch-project/OpenSearch/pull/10670#issuecomment-1772393152

**Comment by jed326** [comment] 2023-10-30 19:44
`DiversifiedSamplerIT.testNestedSamples` is the test specified in this issue and was muted as a part of https://github.com/opensearch-project/OpenSearch/pull/10437 for the concurrent search case.

Based on the other reported occurrences, it seems like the following tests are also flaky:
- `DiversifiedSamplerIT.testNestedDiversity`
- `DiversifiedSamplerIT.testNestedSamples`

**Comment by jed326** [comment] 2023-11-01 19:14
Looks like the problem here is the `maxDocsPerValue` is being evaluated at the slice level for concurrent segment search so at the shard level we are getting more than expected docs. Added a 100% reproduction POC here: https://github.com/jed326/OpenSearch/commit/09e9d498bb1dd0ace3ffc729525f62d076b998cb.

Will work on publishing a fix for this.

**Closed** 2023-11-04 01:47 UTC
Labels: bug, flaky-test
