### ISSUE TITLE
[BUG] Flaky test org.opensearch.search.nested.SimpleNestedIT.testSimpleNestedSortingWithNestedFilterMissing

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10231] opened 2023-09-26 08:07 UTC
**Describe the bug**
`org.opensearch.search.nested.SimpleNestedIT.testSimpleNestedSortingWithNestedFilterMissing {p0={"search.concurrent_segment_search.enabled":"true"}}` is flaky. 

**To Reproduce**
REPRODUCE WITH: `./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.nested.SimpleNestedIT" -Dtests.method="testSimpleNestedSortingWithNestedFilterMissing {p0={"search.concurrent_segment_search.enabled":"true"}}" -Dtests.seed=589B9B48CFDCA68E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=bg-BG -Dtests.timezone=America/Grand_Turk -Druntime.java=20`
 I have not tested if this reproduces the issue.

**Expected behavior**
This test should always pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
CI - https://build.ci.opensearch.org/job/gradle-check/26298/testReport/junit/org.opensearch.search.nested/SimpleNestedIT/testSimpleNestedSortingWithNestedFilterMissing__p0___search_concurrent_segment_search_enabled___true___/

**Comment by jed326** [comment] 2024-01-31 18:19
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/11187, already resolved

**Closed by jed326** 2024-01-31 18:19 UTC
Labels: bug, flaky-test
