### ISSUE TITLE
[BUG] Gradle configure registers `destructiveDistroTest.docker` task twice

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#1640] opened 2021-12-01 21:13 UTC
**Describe the bug**
Gradle scripts are configuring `destructiveDistroTest.docker` task twice and we see warning with run.

```
> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.3
  OS Info               : Mac OS X 10.16 (x86_64)
  JDK Version           : 14 (Oracle JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
  Random Testing Seed   : E282A63209C90F93
  In FIPS 140 mode      : false
=======================================
```

**To Reproduce**
1. Checkout OpenSearch
2. Run `./gradlew spotlessJavaCheck`

**Expected behavior**
`destructiveDistroTest.docker` should be configured once.

**Comment by reta** [comment] 2021-12-02 20:56
Interesting, seems to be an old / known issue:

https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java#L121

**Comment by lliu0947** [comment] 2022-05-19 07:57
I have the same problem when executing ./gradlew test

**Comment by reta** [comment] 2022-05-20 14:49
@MaxKsyunz would you like to submit a pull request? thank you!

**Comment by MaxKsyunz** [comment] 2022-05-20 23:57
@reta thanks for interest! My change got me past the error but I didn't think it was PR-worthy -- it doesn't address the root cause.

**Comment by techrajdeep** [comment] 2022-10-09 05:15
I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

**Comment by reta** [comment] 2022-10-09 17:11
> I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

@techrajdeep sure, your help would be much appreciated, what kind of help on this issue do you need?

**Comment by techrajdeep** [comment] 2022-10-10 06:40
@reta Is this issue still available. If available , could you please assign it to me.

**Comment by minalsha** [comment] 2023-01-11 23:38
@techrajdeep, could you please let us know if you need any help? Could you please share the progress on this issue?

**Closed** 2023-04-03 16:30 UTC
Labels: bug, good first issue, Build Libraries & Interfaces, Priority-Low, hacktoberfest
