### ISSUE TITLE
[BUG] org.opensearch.search.sort.FieldSortIT.testSimpleSorts {p0={"search.concurrent_segment_search.enabled":"true"}} flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#11929] opened 2024-01-18 18:35 UTC
### Describe the bug

org.opensearch.search.sort.FieldSortIT.testSimpleSorts {p0={"search.concurrent_segment_search.enabled":"true"}}

### Related component

Search

### To Reproduce

```
  1> [2024-01-18T10:39:13,906][INFO ][o.o.s.s.FieldSortIT      ] [testSimpleSorts] [p0={"search.concurrent_segment_search.enabled":"true"}] after test
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.sort.FieldSortIT" -Dtests.method="testSimpleSorts {p0={"search.concurrent_segment_search.enabled":"true"}}" -Dtests.seed=7F636AA451844A43 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pt-BR -Dtests.timezone=Canada/Yukon -Druntime.java=21
  2> Failed to execute phase [query], all shards failed; shardFailures {[V4_CDsasQ2eONdvq9SznzQ][test][0]: RemoteTransportException[[node_s0][127.0.0.1:44483][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NotSerializableExceptionWrapper[unsupported_operation_exception: null]; }
        at __randomizedtesting.SeedInfo.seed([7F636AA451844A43:3D188F6C65E2365D]:0)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:718)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:379)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:757)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:511)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:301)
        at app//org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
        at app//org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
        at app//org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:760)
        at app//org.opensearch.telemetry.tracing.handler.TraceableTransportResponseHandler.handleException(TraceableTransportResponseHandler.java:81)
        at app//org.opensearch.transport.TransportService$9.handleException(TransportService.java:1702)
        at app//org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1488)
        at app//org.opensearch.transport.InboundHandler.lambda$handleException$5(InboundHandler.java:447)
        at app//org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
        at app//org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:445)
        at app//org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:437)
        at app//org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:170)
        at app//org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:127)
        at app//org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770)
        at app//org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
        at app//org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
        at app//org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
        at app//org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:343)
        at app//org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
        at app//org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
        at app//org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
        at app//org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
        at app//org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
        at app//org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
        at app//org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
        at app//org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
        at java.****@21.0.1/java.lang.Thread.run(Thread.java:1583)

        Caused by:
        NotSerializableExceptionWrapper[unsupported_operation_exception: null]
            at org.opensearch.index.fielddata.AbstractNumericDocValues.advance(AbstractNumericDocValues.java:57)
            at org.apache.lucene.search.comparators.NumericComparator$NumericLeafComparator$2.advance(NumericComparator.java:407)
            at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:286)
            at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:236)
            at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71)
            at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
            at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:327)
            at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:283)
            at org.apache.lucene.search.IndexSearcher.lambda$search$2(IndexSearcher.java:721)
            at org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:118)
            at java.util.concurrent.FutureTask.run(FutureTask.java:317)
            at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
            at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            at java.lang.Thread.run(Thread.java:1583)
```

### Expected behavior

Test passes.

### Additional Details

https://build.ci.opensearch.org/job/gradle-check/32296/

**Comment by reta** [comment] 2024-01-18 22:14
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/11875

**Closed by reta** 2024-01-18 22:14 UTC
Labels: bug, untriaged, flaky-test, Search
