### ISSUE TITLE
[BUG] Indexing throughput regression in OpenSearch main branch

### ISSUE THREAD

**Issue by shwetathareja** [opensearch-project/OpenSearch#12991] opened 2024-04-01 03:36 UTC
### Describe the bug

There is regression observed in Indexing Performance around 10-15% starting March 22 2024 in mainline branch during the nightly runs.
![Screenshot 2024-03-29 at 5 44 30 PM](https://github.com/opensearch-project/OpenSearch/assets/2943091/43cee92d-b31d-49a0-918d-86ec3efb0cc6)

Pending further details.

### Related component

Indexing:Performance

### Expected behavior

No regression.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by khushbr** [comment] 2024-04-01 05:09
The Indexing throughput degradation is seen only on 3.0.0, refer below screenshot taken from https://opensearch.org/benchmarks/

The version 2.12.0 and 2.13.0 performance numbers are close. 

![Screenshot 2024-04-01 at 10 35 39 AM](https://github.com/opensearch-project/OpenSearch/assets/59671881/f43fcd51-df66-4bab-9750-c5ffbae1e9d1)

**Comment by khushbr** [comment] 2024-04-01 06:03
I looked at the delta commits and one suspect is https://github.com/opensearch-project/OpenSearch/pull/12494/files, 

@bbarani  Do we have support to run the Nightly Benchmarks against a commit ? Can we run the HTTP corpus against the above commit ?

**Comment by bbarani** [comment] 2024-04-01 17:52
@rishabh6788 can you help @khushbr ?

**Comment by rishabh6788** [comment] 2024-04-02 07:28
Synced up with @khushbr and provided her the details.
The reason we don't see regression on 2.13 is because the commit Khushboo mentioned has not been merged onto 2.13 branch. It is there on 2.x branch and once we schedule nightlies for 2.14 after 2.13 release tomorrow we should see similar pattern as 3.0 on 2.x line, if in fact that is the offending commit.

**Comment by khushbr** [comment] 2024-04-02 08:11
Commit at the tip of main branch for 03/21 run:
[Light weight Transport action to verify local term before fetching cluster-state from remote](https://github.com/opensearch-project/OpenSearch/commit/7ad30171a8869f659c1feeb6185acf023ebaa203)

Commit at the tip of main branch for 03/22 run:
[Catch task description error](https://github.com/opensearch-project/OpenSearch/commit/0c956e81373c9d5878710c1bafe471431000a64f)

Delta commits:
* [Catch task description error ](https://github.com/opensearch-project/OpenSearch/commit/0c956e81373c9d5878710c1bafe471431000a64f)
* [Add release-notes for 2.13.0 ](https://github.com/opensearch-project/OpenSearch/commit/0c0bcd9ffa10ba7999418f2f7d400ba3a1d446dd)
* [Add 2.14.0 to version & BWC ](https://github.com/opensearch-project/OpenSearch/commit/7bd3715c81acdaa3c3eaf2c50032db139718f485)
* [Update the support version to 2.13 as term-check is merged to 2.x ](https://github.com/opensearch-project/OpenSearch/commit/e673b6194fab6f672b62dfdaf8f082bc8dec403f)
* [Fix Flaky SimpleQueryStringIT Tests](https://github.com/opensearch-project/OpenSearch/commit/fd458d62faa0a264d3e7378d9a0a8ffd90f6f235)
* [Update supported version for the wait_for_completion parameter in open&clone&shrink&split APIs ](https://github.com/opensearch-project/OpenSearch/commit/53c0ce38b26569c90f8980f1c2b0b70e5ebbf6fc)
* [Integrate with CPU admission controller for cluster-manager Read API's.](https://github.com/opensearch-project/OpenSearch/commit/2069bd805804dd93bd69695a4c6521cc6f2b9bb6)
* [[Remote Migration] Changes for Primary Relocation during migration ](https://github.com/opensearch-project/OpenSearch/commit/f3d2beee637f63e38c8f26dbcee9f2a82f9c87b6)

**Comment by bbarani** [comment] 2024-04-02 17:11
> The Indexing throughput degradation is seen only on 3.0.0, refer below screenshot taken from https://opensearch.org/benchmarks/
> 
> The version 2.12.0 and 2.13.0 performance numbers are close.
> 


I still notice the regression (especially when security is disabled) in main branch


<img width="1321" alt="Screenshot 2024-04-02 at 10 10 10 AM" src="https://github.com/opensearch-project/OpenSearch/assets/70038446/d947ff93-927d-4942-ae72-b01e083f1814">

**Comment by khushbr** [comment] 2024-04-04 05:37
Uptill ([[Remote Migration] Changes for Primary Relocation during migration ](https://github.com/opensearch-project/OpenSearch/commit/f3d2beee637f63e38c8f26dbcee9f2a82f9c87b6)) OSB runs (in docs/s):

|  | Min Throughput  | Mean Throughput  | Median Throughput  | Max Throughput  |
|---|---|---|---|---|
| 1 | 191314 | 200558 | 199832 | 210299 |
| 2 | 183816 | 197962 | 194975 | 216139 |
| 3 | 185448 | 193235 | 192683 | 200703 |

Uptill ([Update supported version for the wait_for_completion parameter in open&clone&shrink&split APIs ](https://github.com/opensearch-project/OpenSearch/commit/53c0ce38b26569c90f8980f1c2b0b70e5ebbf6fc)) OSB runs(in docs/s):
|  | Min Throughput  | Mean Throughput  | Median Throughput  | Max Throughput  |
|---|---|---|---|---|
| 1 | 187156 | 193726 | 193174 | 200601 |
| 2 | 188290 | 196304 | 195373 | 205012 |
| 3 | 191328 | 200612 | 199125 | 210423 |

Full Set Commits taken on 03/22 ([Catch task description error](https://github.com/opensearch-project/OpenSearch/commit/0c956e81373c9d5878710c1bafe471431000a64f)) OSB runs(in docs/s):
|  | Min Throughput  | Mean Throughput  | Median Throughput  | Max Throughput  |
|---|---|---|---|---|
| 1 | 192710 | 201019 | 199823 | 210869 |
| 2 | 191049 | 201927 | 199053 | 216989 |
| 3 | 193736 | 205920 | 203444 | 221371 |

**Comment by khushbr** [comment] 2024-04-04 05:41
The 'Max Throughput' with the Full Set of Commits on 03/22 reaches `> 220k` for 1 run and the mean throughput `>200k`. The baseline commit runs are still underway.

**Comment by gbbafna** [comment] 2024-04-04 08:49
I see that the throughput has increased again for all of the benchmarks except `HTTP logs - indexing throughput (Security enabled) - SegRep disabled `  . We have added a change to memoize a value rather than looking into index settings for same : https://github.com/opensearch-project/OpenSearch/pull/12994 and backported it to 2.x (2.14) as well . The results of 2.14 are on par with 2.13 now.  I will wait for another day to see if `HTTP logs - indexing throughput (Security enabled) - SegRep disabled `  improves as well before closing this issue.

**Closed** 2024-04-04 14:58 UTC
Labels: bug, Indexing, Indexing:Performance
