### ISSUE TITLE
[BUG] RemoteStoreStatsIT.testStatsResponseFromAllNodes is flaky

### ISSUE THREAD

**Issue by shourya035** [opensearch-project/OpenSearch#9828] opened 2023-09-06 16:40 UTC
**Describe the bug**
RemoteStoreStatsIT.testStatsResponseFromAllNodes is failing
Gradle build: https://build.ci.opensearch.org/job/gradle-check/24535/

Seems like the failure is coming from:

https://github.com/opensearch-project/OpenSearch/blob/742267dba8599b60bb5bb16bb69ad4ba114a5581/server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java#L639-L641

**Comment by shourya035** [comment] 2023-09-06 16:40
Tagging @BhumikaSaini-Amazon

**Comment by BhumikaSaini-Amazon** [comment] 2023-09-07 12:13
Thanks @shourya035

I tried to repro this locally:

```shell
Tests with failures:
 - org.opensearch.remotestore.RemoteStoreStatsIT.testStatsResponseFromAllNodes {seed=[BF41DC8F5BDE48FB:EAF82628D3FF804A]}
 - org.opensearch.remotestore.RemoteStoreStatsIT.testStatsResponseFromAllNodes {seed=[BF41DC8F5BDE48FB:E70285B0347709C0]}
 - org.opensearch.remotestore.RemoteStoreStatsIT.testStatsResponseFromAllNodes {seed=[BF41DC8F5BDE48FB:5EF77F8498B1EB9F]}

200 tests completed, 3 failed

> Task :server:internalClusterTest FAILED
```

The 3/200 failed instances are failing on asserting 0 failed segment uploads:
```java
assertEquals(0, stats.totalUploadsFailed);
```

Will check for more iterations and post if I am able to repro with tlog failures.

**Comment by ashking94** [comment] 2024-01-08 18:02
I have run this test for around 1K iterations without failure. Resolving this issue. I am also running this test on loop overnight. If I see failures, will reopen this.

**Comment by ashking94** [comment] 2024-01-16 07:47
I have root caused this issue to be same as https://github.com/opensearch-project/OpenSearch/issues/9774. @linuxpi  is already working on fixing it. Closing this issue.

**Closed by ashking94** 2024-01-16 07:47 UTC
Labels: bug, flaky-test
