### ISSUE TITLE
[BUG] Improper Error Handling in index creation API

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#4806] opened 2022-10-17 13:00 UTC
**Describe the bug**
Sending malformed JSON to index creation API returns `500 Internal Server Error` response. Ideally, it should be `400 Bad Request`.

**Comment by mch2** [comment] 2022-10-17 18:54
Looks like a duplicate of #2756.

**Closed by mch2** 2022-10-17 18:54 UTC
Labels: bug, untriaged
