### ISSUE TITLE
Remote Translog pruning

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#3766] opened 2022-07-04 19:51 UTC
**Is your feature request related to a problem? Please describe.**
This is a meta issue and we would like to discuss various approaches when and how should operations on the remote Translog be pruned

It can be done as a background task to periodically detect unreferenced readers and clean up files as may be needed. 

For remote Translog there is going to be just one store common for all shard copies and should retain all operations till the max seq no referenced by remote segments

Will add more details on this issue after deliberation 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gbbafna** [comment] 2023-01-02 13:51
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/5567

**Closed by gbbafna** 2023-01-02 13:51 UTC
Labels: enhancement, distributed framework, durability
