### ISSUE TITLE
[BUG] org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions is flaky

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/OpenSearch#12622] opened 2024-03-12 16:55 UTC
### Describe the bug

The test `org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions` is flaky.

```
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Full CI details report: <https://build.ci.opensearch.org/job/gradle-check/34698/testReport/org.opensearch.ratelimitting.admissioncontrol/AdmissionControlMultiNodeIT/testAdmissionControlEnforcedOnNonACEnabledActions/>

### Related component

Search

### To Reproduce

See `REPRODUCE WITH:` in the log below:

```
مار 12, 2024 10:07:13 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4457,opensearch[node_t0][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:13 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4460,opensearch[node_t2][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:13 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4462,opensearch[node_t4][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:13 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4461,opensearch[node_t3][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:13 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4465,opensearch[node_t5][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:13 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4472,opensearch[node_t1][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlRejectionOnDisabled" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlRejectionOnDisabled" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlRejectionOnDisabled" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlRejectionOnDisabled" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlRejectionOnDisabled" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlRejectionOnDisabled" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
مار 12, 2024 10:07:41 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4669,opensearch[node_t0][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:41 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4672,opensearch[node_t2][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:41 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4673,opensearch[node_t1][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:41 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4679,opensearch[node_t5][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:41 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4677,opensearch[node_t4][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

مار 12, 2024 10:07:41 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4674,opensearch[node_t3][generic][T#3],5,TGRP-AdmissionControlMultiNodeIT]
java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([62DE73D5CA8E5066]:0)
	at org.opensearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:215)
	at org.opensearch.cluster.service.ClusterService.state(ClusterService.java:172)
	at org.opensearch.node.ResourceUsageCollectorService.collectLocalNodeResourceUsageStats(ResourceUsageCollectorService.java:129)
	at org.opensearch.node.ResourceUsageCollectorService.lambda$doStart$3(ResourceUsageCollectorService.java:147)
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:246)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlMultiNodeIT.testAdmissionControlEnforcedOnNonACEnabledActions" -Dtests.seed=62DE73D5CA8E5066 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=Asia/Pontianak -Druntime.java=21
NOTE: test params are: codec=Asserting(Lucene99): {index_uuid=Lucene99, key.keyword=Lucene99, _id=PostingsFormat(name=Asserting), type=Lucene99, key=Lucene99}, docValues:{_seq_no=DocValuesFormat(name=Asserting), key.keyword=DocValuesFormat(name=Asserting), _primary_term=DocValuesFormat(name=Lucene90), _version=DocValuesFormat(name=Asserting)}, maxPointsInLeafNode=1853, maxMBSortInHeap=5.231156149620813, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=ar-QA, timezone=Asia/Pontianak
NOTE: Linux 5.15.0-1048-aws amd64/Eclipse Adoptium 21.0.2 (64-bit)/cpus=32,threads=1,free=314826416,total=679477248
NOTE: All tests run in this JVM: [TasksIT, DataStreamRolloverIT, BulkIntegrationIT, CreateIndexBlockIT, AwarenessAllocationIT, AllocationIdIT, ClusterDisruptionCleanSettingsIT, GatewayIndexStateIT, ShardIndexingPressureSettingsIT, IndexShardIT, ConcurrentDynamicTemplateIT, SegmentReplicationIT, SimpleIndexStateIT, AdmissionControlMultiNodeIT]
```

### Expected behavior

The test should always pass.

### Additional Details

**Plugins**

Plugins available during CI.

**Screenshots**

**Host/Environment (please complete the following information):**

CI.

**Additional context**

**Comment by andrross** [comment] 2024-03-13 15:09
[Triage - attendees [1](https://github.com/andrross) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek)]
@lukas-vlcek Thanks for filing this issue.

**Comment by andrross** [comment] 2024-03-13 15:11
There was a file leak in another test (https://github.com/opensearch-project/OpenSearch/issues/12619) in this same build, which may be related to or the cause of this failure.

**Comment by sandeshkr419** [comment] 2024-11-27 19:43
Closing this issue since we haven't been seeing this test as flaky for a while and if it happens again then `opensearch-ci-bot` will open up the issue back automatically.

**Closed by sandeshkr419** 2024-11-27 19:43 UTC
Labels: bug, flaky-test, Search, Resiliency
