### ISSUE TITLE
`IpFieldMapper` should use `IndexOrDocValuesQuery` where possible

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/OpenSearch#11144] opened 2023-11-09 01:28 UTC
**Is your feature request related to a problem? Please describe.**
While going through the `IpFieldMapper` class and looking through `IpFieldMapperType` I noticed that the termQuery, termsQuery, and rangeQuery all use underlying lucene index queries. The documentation also incorrectly points to the fact that IP address do not have doc_values enabled by default. This is incorrect, ref: https://github.com/opensearch-project/OpenSearch/blob/b78176afefd8c09a19de6bc52907b40c8c4fedf2/server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java#L89

**Describe the solution you'd like**
Wrap all three queries in `IndexOrDocValuesQuery` and add checks to ensure that we return the index query if the field is only indexed and doc_values query if we only have doc_values enabled.

**Describe alternatives you've considered**
Alternative is to leave this as is. But there is potentially a lot of performance improvement to be had. Consider a query that looks like

```
{
  query: {
  "range":{
  "timestamp: {
      "from" :xyz,
       "to": xyz
    }
   },
"terms": {
"ipaddress" :["0.0.0.0", "1.1.1.1"]
}
}
}
```
We could let the range on the timestamp drive the query and use the doc_values to match the documents for the terms in the ipaddress.

**Additional context**
#7057

**Comment by hdhalter** [comment] 2023-12-11 23:40
Hi @harshavamsi , will this require documentation for 2.12? If so, can you please create a doc issue, let me know who will be responsible for the doc PR, and add this to the unified tracker project? Thank you!

**Comment by kiranprakash154** [comment] 2024-01-19 00:32
Hi, are we on track for this to be released in 2.12 ?

**Comment by getsaurabh02** [comment] 2024-01-23 20:06
@reta Is there are reason we should move this to 3.0? Given the PR is already out by @vamshin we might be able to close it in before 2.12?

**Comment by reta** [comment] 2024-01-23 21:53
> @reta Is there are reason we should move this to 3.0? Given the PR is already out by @vamshin we might be able to close it in before 2.12?

Yeah, I think so, the issue is tagged to `2.12.0` (and `3.0.0` surely) :)

**Comment by hdhalter** [comment] 2024-01-23 22:04
@reta Does this require documentation for 2.12?

**Comment by reta** [comment] 2024-01-23 22:06
> @reta Does this require documentation for 2.12?

I believe there are no user facing changes here

**Closed** 2024-01-30 00:06 UTC
Labels: enhancement, v3.0.0, Search:Performance, v2.12.0
