### ISSUE TITLE
[BUG] Unable to install lang-painless module when testDistribution is set to INTEG_TEST for k-NN

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/OpenSearch#1676] opened 2021-12-01 21:09 UTC
**What is the bug?**
For k-NN, I am trying to run integ tests on Mac. To do this, I first switched [testDistribution](https://github.com/jmazanec15/k-NN-1/blob/build-on-mac/build.gradle#L205) from ARCHIVE to INTEG_TEST. Otherwise, it cannot find the OpenSearch artifact:
```
Execution failed for task ':run'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-1.3.0-SNAPSHOT-'.
   > Could not resolve opensearch-distribution-snapshot:opensearch:1.3.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve opensearch-distribution-snapshot:opensearch:1.3.0-SNAPSHOT.
         > Could not get resource 'https://artifacts.opensearch.org/snapshots/core/opensearch/1.3.0-SNAPSHOT/opensearch-min-1.3.0-SNAPSHOT-darwin-x64-latest.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/snapshots/core/opensearch/1.3.0-SNAPSHOT/opensearch-min-1.3.0-SNAPSHOT-darwin-x64-latest.tar.gz'. Received status code 403 from server: Forbidden
```

After making the above switch, it is able to download, but fails with the following error (k-NN has a dependency on lang-painless):
```
| Exception in thread "main" java.lang.IllegalArgumentException: Missing plugin [lang-painless], dependency of [opensearch-knn]
|       at org.opensearch.plugins.PluginsService.addSortedBundle(PluginsService.java:512)
|       at org.opensearch.plugins.PluginsService.sortBundles(PluginsService.java:480)
|       at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:839)
|       at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:813)
|       at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
|       at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
|       at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
|       at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
|       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
|       at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
|       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
|       at org.opensearch.cli.Command.main(Command.java:101)
|       at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```
This is because the modules do not come with the INTEG_TEST distribution.

So, I create the lang painless module from source and placed it in [test resources](https://github.com/jmazanec15/k-NN-1/tree/build-on-mac/src/test/resources/lang-painless). Then, I add it [as a plugin](https://github.com/jmazanec15/k-NN-1/blob/build-on-mac/build.gradle#L220-L232). However, this then fails with this error:
```
| ERROR: plugin 'lang-painless' cannot be installed as a plugin, it is a system module
```

So, I switch [this line](https://github.com/jmazanec15/k-NN-1/blob/build-on-mac/build.gradle#L220) from plugin to module. However, this then produces the missing plugin error again:
```
| Exception in thread "main" java.lang.IllegalArgumentException: Missing plugin [lang-painless], dependency of [opensearch-knn]
|       at org.opensearch.plugins.PluginsService.addSortedBundle(PluginsService.java:512)
|       at org.opensearch.plugins.PluginsService.sortBundles(PluginsService.java:480)
|       at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:839)
|       at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:813)
|       at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
|       at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
|       at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
|       at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
|       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
|       at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
|       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
|       at org.opensearch.cli.Command.main(Command.java:101)
|       at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```
I was wondering if there is any way to prevent gradle from attempting to install an [extended plugin](https://github.com/opensearch-project/k-NN/blob/main/build.gradle#L105) as a plugin when it is a module.

**How can one reproduce the bug?**
1. Clone the repo
```
git clone https://github.com/jmazanec15/k-NN-1.git
cd k-NN-1 
git checkout build-on-mac
```
2. Install dependencies
```
brew install openblas
```
3. Run build
```
./gradlew build
```
**What is the expected behavior?**
Expect to be able to add lang-painless as a module.

**What is your host/environment?**
 - OS: Mac Big Sur
 - Version 1.3
 - Plugins k-NN, lang-painless

**Comment by saratvemulapalli** [comment] 2021-12-08 01:20
@jmazanec15 Modules are only installed for `INTEG_TEST` test distribution. 
Ref: https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java#L725
Manually installing a module will also fail because its not a plugin. 

The rootcause of the problem is 1.3.0-SNAPSHOT opensearch min artifact is not available for darwin. 
`https://artifacts.opensearch.org/snapshots/core/opensearch/1.3.0-SNAPSHOT/opensearch-min-1.3.0-SNAPSHOT-darwin-x64-latest.tar.gz`
Here is the issue: https://github.com/opensearch-project/opensearch-build/issues/38 which is tracking for 1.3 release.

So unless that is resolved running integration tests on darwin would not work. 
The alternative solution is to run integration tests while spinning up an external cluster: https://github.com/opensearch-project/opensearch-plugins/issues/103

That said, for the last part of the question:
 `I was wondering if there is any way to prevent gradle from attempting to install an extended plugin as a plugin when it is a module.`
The `ARCHIVE` test distribution was not intended was these reasons. You should continue to use `INTEG_TEST` distribution to have modules installed by default.

**Comment by saratvemulapalli** [comment] 2021-12-08 16:11
Closing this. Feel free to reopen if the comment does not help.

**Comment by jmazanec15** [comment] 2022-03-17 17:18
@saratvemulapalli Not sure I have the ability to reopen, but wanted to continue discussion.

I tried switching to INTEG_TEST, but this does not come with modules other than transport-netty. 

I was thinking about installing the "lang-painless" in the following way:
1. Adding a dependency on it in my build.gradle.
```
configurations {
    painless
}

dependencies {
    ...
    painless "org.opensearch.plugin:lang-painless:${opensearch_version}"
}

```
2. Zipping up the files pulled from the dependency as a gradle task
```
task prepareLangPainlessZip(type: Zip) {
    from configurations.painless.allArtifacts.files
    from configurations.painless
    destinationDirectory = layout.buildDirectory.dir("jack")
    archiveFileName = "lang-painless.zip"
}
```
3. Adding the zip as a module in the cluster setup:
```
testClusters.integTest {
    testDistribution = "INTEG_TEST"
    module(provider(new Callable<RegularFile>(){
        @Override
        RegularFile call() throws Exception {
            return new RegularFile() {
                @Override
                File getAsFile() {
                    return fileTree("build/jack").getSingleFile()
                }
            }
        }
    }))
    ...
}
```

However, I get the following error:
```
| Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for module directory [lang-painless]
|       at org.opensearch.plugins.PluginsService.readPluginBundle(PluginsService.java:452)
|       at org.opensearch.plugins.PluginsService.findBundles(PluginsService.java:437)
|       at org.opensearch.plugins.PluginsService.getModuleBundles(PluginsService.java:425)
|       at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:849)
|       at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:825)
|       at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
|       at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
|       at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
|       at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
|       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
|       at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
|       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
|       at org.opensearch.cli.Command.main(Command.java:101)
|       at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
| Caused by: java.nio.file.NoSuchFileException: .../k-NN-1/build/testclusters/integTest-0/distro/2.0.0-INTEG_TEST/modules/lang-painless/plugin-descriptor.properties
|       at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
|       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
|       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
|       at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
|       at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
|       at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
|       at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
|       at java.base/java.nio.file.Files.newInputStream(Files.java:160)
|       at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:199)
|       at org.opensearch.plugins.PluginsService.readPluginBundle(PluginsService.java:449)

```

I have a couple questions:
1. Why plugins in https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/ do not contain the plugin descriptors?
2. Why is module call trying to use plugin cli?
3. Is there a better way to go about doing this?

Related issue: https://github.com/opensearch-project/opensearch-build/issues/1750#issuecomment-1069789476

**Comment by dblock** [comment] 2022-05-18 21:02
@prudhvigodithi should be able to answer ^

**Comment by prudhvigodithi** [comment] 2022-05-18 21:20
Hey @jmazanec15 [opensearch.pluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip), this will publish the generated distribution plugin zip's to maven repo, is `lang-painless` zip part of any plugin bundle task? If so yes this `opensearch.pluginzip` can be used to publish to maven repo with right maven coordinates.

**Comment by jmazanec15** [comment] 2022-06-16 22:51
It seems like there are several other plugins that might have this issue (i.e. cant bring up cluster on mac):
1. https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L616
2. https://github.com/opensearch-project/alerting/blob/main/alerting/build.gradle#L82
3. https://github.com/opensearch-project/asynchronous-search/blob/main/build.gradle#L117

I am wondering if, [given that modules are meant to be shipped with OpenSearch](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#modules), it makes sense to have a testDistribution that includes modules and works on mac.

Im not sure if this means adding support for it through the ARCHIVE distribution, or adding another distribution similar to INTEG_TEST.

What do you think? @dblock @saratvemulapalli @prudhvigodithi @ryanbogan .

**Comment by amitgalitz** [comment] 2022-06-16 22:55
> It seems like there are several other plugins that might have this issue (i.e. cant bring up cluster on mac):
> 
> 1. https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L616
> 2. https://github.com/opensearch-project/alerting/blob/main/alerting/build.gradle#L82
> 3. https://github.com/opensearch-project/asynchronous-search/blob/main/build.gradle#L117
> 
> I am wondering if, [given that modules are meant to be shipped with OpenSearch](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#modules), it makes sense to have a testDistribution that includes modules and works on mac.
> 
> Im not sure if this means adding support for it through the ARCHIVE distribution, or adding another distribution similar to INTEG_TEST.
> 
> What do you think? @dblock @saratvemulapalli @prudhvigodithi @ryanbogan .

+1 on this issue, Anomaly Detection is experiencing the exact same bug.

**Comment by saratvemulapalli** [comment] 2022-06-17 16:23
@amitgalitz @jmazanec15 I see it as a workaround to help install default modules for a test distribution(`INTEG_TEST`/ new distribution) to run tests on MacOS. 
The `ARCHIVE` test distribution already is bundled with all default modules (including lang-painless) but its not available on MacOS yet[1]. 
cc: @bbarani 

My thoughts, I would rather have it supported the right way rather than putting in a work around. 
That said, if this is impacting your productivity we can look at alternative options.


[1] https://github.com/opensearch-project/opensearch-build/issues/38

**Comment by jmazanec15** [comment] 2022-06-17 16:47
>  That said, if this is impacting your productivity we can look at alternative options.

In general, it creates a lot of extra effort for someone to rampup on the project. They have to figure out a system that will sync mac dev environment with linux. Also, makes running debuggers more difficult. Overall, makes the bar to contribute higher.

https://github.com/opensearch-project/opensearch-build/issues/38 seems to be focused on supporting the bundle as a whole on Mac. I am wondering if as a first step, we could just enable it for OpenSearch and its modules to unblock development. Specifically, focus on making ARCHIVE work on Mac as opposed to waiting for Mac bundle to be ready and supported.

**Comment by saratvemulapalli** [comment] 2022-06-17 17:11
> In general, it creates a lot of extra effort for someone to rampup on the project. They have to figure out a system that will sync mac dev environment with linux. Also, makes running debuggers more difficult. Overall, makes the bar to contribute higher.

Absolutely, I feel the pain as well :). 

> [opensearch-project/opensearch-build#38](https://github.com/opensearch-project/opensearch-build/issues/38) seems to be focused on supporting the bundle as a whole on Mac. I am wondering if as a first step, we could just enable it for OpenSearch and its modules to unblock development. Specifically, focus on making ARCHIVE work on Mac as opposed to waiting for Mac bundle to be ready and supported.

Yeah that would be a nice intermediate step which unblocks this, I love this idea. 
Which is btw already available from OpenSearch, its just that opensearch-build has to publish the artifact.  
Is this something your team could consider ? @bbarani @peterzhuamazon

**Comment by bbarani** [comment] 2022-06-17 21:29
@saratvemulapalli Can you please clarify the artifact that you are referring in the above comments? Are you referring to opensearch-min artifact?

**Comment by saratvemulapalli** [comment] 2022-06-17 21:32
> @saratvemulapalli Can you please clarify the artifact that you are referring in the above comment? Are you referring to opensearch-min artifact?

Correct, opensearch-min artifact for MacOS (darwin).

**Comment by dblock** [comment] 2022-06-17 23:44
Does a cross-platform build for MacOS work on MacOS? If so we can probably add to the existing Jenkinsfile a "mac" build that's good enough?

**Comment by prudhvigodithi** [comment] 2022-06-18 15:10
> Does a cross-platform build for MacOS work on MacOS? If so we can probably add to the existing Jenkinsfile a "mac" build that's good enough?

or we can just run the distribution build on macOS ec2 jenkins agent, then the logic `PLATFORM ` `uname -s` will be inferred as `Darwin`
https://aws.amazon.com/ec2/instance-types/mac/

**Comment by bbarani** [comment] 2022-06-20 17:57
We are currently explore this option. We will update this thread soon with our findings.

CC: @prudhvigodithi @saratvemulapalli @jmazanec15 @dblock

**Comment by prudhvigodithi** [comment] 2022-06-20 22:48
Hey @jmazanec15, can you please test with `opensearch-min-2.0.1-darwin-x64.tar.gz`
https://ci.opensearch.org/ci/dbc/Playground/distribution-build-opensearch-pgodithi/2.0.1/0/darwin/x64/builds/opensearch/dist/opensearch-min-2.0.1-darwin-x64.tar.gz
**NOTE: This is not a final darwin published artifact, this is to just test the OpenSearch min darwin format.**

**Comment by jmazanec15** [comment] 2022-06-20 23:16
Yes it works!

```
./bin/opensearch-plugin install file:/Users/jmazane/opensearch-knn-2.0.1.0.zip
warning: ignoring JAVA_TOOL_OPTIONS=-Dlog4j2.formatMsgNoLookups=true
...
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission loadLibrary.opensearchknn_faiss
* java.lang.RuntimePermission loadLibrary.opensearchknn_nmslib
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed opensearch-knn with folder name opensearch-knn

./bin/opensearch
...
[2022-06-20T16:15:10,817][INFO ][o.o.p.PluginsService     ] [38f9d3cc26d7.ant.amazon.com] loaded plugin [opensearch-knn]
...

curl localhost:9200/_cat/plugins
xxxxx opensearch-knn 2.0.1.0
```

Just to be sure, this will get published to something like 
```
'https://artifacts.opensearch.org/snapshots/core/opensearch/2.0.1-SNAPSHOT/opensearch-min-2.0.1-SNAPSHOT-darwin-x64-latest.tar.gz'
```

correct?

**Comment by navneet1v** [comment] 2022-06-21 02:40
Similar [issue](https://github.com/opensearch-project/OpenSearch/issues/3637) but happening for all the OS versions with mavenLocalPublish. Can someone please take a look at this too?

**Comment by prudhvigodithi** [comment] 2022-06-21 11:21
> Just to be sure, this will get published to something like
> 
> ```
> 'https://artifacts.opensearch.org/snapshots/core/opensearch/2.0.1-SNAPSHOT/opensearch-min-2.0.1-SNAPSHOT-darwin-x6
> ```

@jmazanec15 mostly yes, but will post an update here, if anything changed.
Thank you

**Comment by saratvemulapalli** [comment] 2022-08-02 05:57
Closing this. Thanks for all the work @prudhvigodithi.

**Closed by saratvemulapalli** 2022-08-02 05:57 UTC
Labels: Build Libraries & Interfaces

**Comment by navneet1v** [comment] 2022-08-02 06:20
@prudhvigodithi Thanks for the work. This was really a blocker for the development on mac.
