### ISSUE TITLE
[BUG] org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex is flaky

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/OpenSearch#11547] opened 2023-12-08 23:22 UTC
**Describe the bug**
[org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex](https://build.ci.opensearch.org/job/gradle-check/31019/testReport/junit/org.opensearch.index/IndexServiceTests/testAsyncTranslogTrimTaskOnClosedIndex/) is flaky again. Looks like it was addressed earlier -- https://github.com/opensearch-project/OpenSearch/issues/6124 and https://github.com/opensearch-project/OpenSearch/issues/5414

**To Reproduce**
REPRODUCE WITH: `./gradlew ':server:test' --tests "org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex" -Dtests.seed=AE4E5801E112D5E3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CL -Dtests.timezone=America/St_Kitts -Druntime.java=21`

**Comment by ankitkala** [comment] 2023-12-12 11:42
```
 2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex" -Dtests.seed=AE4E5801E112D5E3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CL -Dtests.timezone=America/St_Kitts -Druntime.java=21
  2> [test/P2V5Snd6R3SLA8OCf5jdbQ] IndexNotFoundException[no such index [test]]
        at __randomizedtesting.SeedInfo.seed([AE4E5801E112D5E3:6930AD98B086A97E]:0)
        at app//org.opensearch.indices.IndicesService.indexServiceSafe(IndicesService.java:701)
        at app//org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex(IndexServiceTests.java:459)
  1> [2023-12-08T14:26:21,231][INFO ][o.o.i.IndexServiceTests  ] [testRefreshTaskIsUpdated] before test
```

**Comment by peternied** [comment] 2024-02-07 16:42
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@harshavamsi Thanks for filing

**Comment by r1walz** [comment] 2024-06-05 09:07
Unable to reproduce locally, even after 23k runs:

![image](https://github.com/opensearch-project/OpenSearch/assets/31043830/e8eff0ac-cab4-4107-8ed1-0f666fbfd6b6)

**Comment by reta** [comment] 2024-06-19 15:30
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14407

**Closed by reta** 2024-06-19 15:30 UTC
Labels: bug, flaky-test, Indexing
