### ISSUE TITLE
[Segment Replication] Run all tests with segment replication enabled on CI

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#7147] opened 2023-04-13 17:59 UTC
Coming from https://github.com/opensearch-project/OpenSearch/issues/6761 excecise and as follow up task, we want to run tests with segment replication enabled on CI. We need to identify specific test classes (or all the tests?), we want to run on CI with segment replication. This would need to have test orchestration where same test is run with both replica strategies.

Running all the tests with segment replcation enabled, will double the time on CI, so choosing a smaller subset of tests will be better. Other idea, is to run two different checks for docrep and segrep on CI.

**Comment by mch2** [comment] 2024-05-09 23:08
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/6761

**Closed by mch2** 2024-05-09 23:08 UTC
Labels: :test, CI, Indexing:Replication
