### ISSUE TITLE
[BUG][2.x] org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod is flaky

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/OpenSearch#11037] opened 2023-10-31 18:58 UTC
**Describe the bug**
https://build.ci.opensearch.org/job/gradle-check/29391/

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 31, 2023 5:40:36 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
WARNING: Will linger awaiting termination of 2 leaked thread(s).
Oct 31, 2023 5:40:41 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
SEVERE: 1 thread leaked from SUITE scope at org.opensearch.repositories.s3.S3BlobContainerRetriesTests: 
   1) Thread[id=38, name=sdk-ScheduledExecutor-2-0, state=TIMED_WAITING, group=TGRP-S3BlobContainerRetriesTests]
        at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
        at java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
        at java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
Oct 31, 2023 5:40:41 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
INFO: Starting to interrupt leaked threads:
   1) Thread[id=38, name=sdk-ScheduledExecutor-2-0, state=TIMED_WAITING, group=TGRP-S3BlobContainerRetriesTests]
Oct 31, 2023 5:40:44 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
SEVERE: There are still zombie threads that couldn't be terminated:
   1) Thread[id=38, name=sdk-ScheduledExecutor-2-0, state=TIMED_WAITING, group=TGRP-S3BlobContainerRetriesTests]
        at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
        at java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
        at java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
REPRODUCE WITH: ./gradlew ':plugins:repository-s3:test' --tests "org.opensearch.repositories.s3.S3BlobContainerRetriesTests" -Dtests.seed=C7F2A0241CB3F601 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=17
REPRODUCE WITH: ./gradlew ':plugins:repository-s3:test' --tests "org.opensearch.repositories.s3.S3BlobContainerRetriesTests" -Dtests.seed=C7F2A0241CB3F601 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=17
NOTE: test params are: codec=Asserting(Lucene95): {}, docValues:{}, maxPointsInLeafNode=263, maxMBSortInHeap=7.743924075697856, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=lt-LT, timezone=Etc/GMT+8
NOTE: Linux 5.15.0-1048-aws amd64/Eclipse Adoptium 17.0.8 (64-bit)/cpus=32,threads=3,free=461322272,total=536870912
NOTE: All tests run in this JVM: [S3BlobContainerRetriesTests]
```

**Comment by gbbafna** [comment] 2024-01-09 05:11
@BhumikaSaini-Amazon , can you please take this up ?

**Comment by BhumikaSaini-Amazon** [comment] 2024-03-07 05:18
This seems a duplicate of #9905. We will track #9905, closing this one.

**Closed by BhumikaSaini-Amazon** 2024-03-07 05:18 UTC
Labels: bug, flaky-test, Storage:Snapshots
