### ISSUE TITLE
OpenSearch : Pinned Queries

### ISSUE THREAD

**Issue by ajaymovva** [opensearch-project/OpenSearch#1134] opened 2021-08-23 04:32 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes it is desirable to artificially boost certain search results for a query and arrange them higher with the rest of the search results. This feature is typically used to guide searchers to curated documents that are promoted over and above any "organic" matches for a search. The promoted or "pinned" documents are identified using the document IDs stored in the [_id](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) field.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by macrakis** [comment] 2022-04-14 16:47
Duplicate of #72

**Closed** 2022-04-15 16:56 UTC
Labels: enhancement, Indexing & Search
