### ISSUE TITLE
[CI] SharedClusterSnapshotRestoreIT.testSnapshotCanceledOnRemovedShard fails sporadically

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1396] opened 2021-10-20 16:34 UTC
This one has failed a few times. Most recent on #1390. 

Needs triage and further investigation

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotCanceledOnRemovedShard" -Dtests.seed=9350EB7A8335C1F9 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sl -Dtests.timezone=SystemV/PST8 -Druntime.java=17

org.opensearch.snapshots.SharedClusterSnapshotRestoreIT > testSnapshotCanceledOnRemovedShard FAILED
    SnapshotMissingException[[test-repo:test-snap] is missing]
        at org.opensearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:160)
        at org.opensearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:80)
        at org.opensearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:124)
        at org.opensearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:197)
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by xuezhou25** [comment] 2021-11-11 06:14
🙋‍♀️

**Comment by xuezhou25** [comment] 2021-11-12 19:35
I am not able to reproduce this. need some advice.😵‍💫

**Comment by kartg** [comment] 2021-11-15 20:10
Update: We will attempt to dig into the test to find a hypothesis for why the snapshot is intermittently missing.

@nknize can you link to other instances where this failure has occurred, so we can get more data to try and identify a pattern?

**Comment by xuezhou25** [comment] 2021-12-08 16:50
`java.lang.IllegalStateException*: Cannot cleanup [test-repo] - a snapshot is currently running in [SnapshotsInProgress[test-snap]]`

From my point of view, this failure is because when creating a snapshot, `setWaitForCompletion(false)`
https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/internalClusterTest/java/org/opensearch/snapshots/SharedClusterSnapshotRestoreIT.java#L1918
 will lead to `SnapshotsInProgress`(as the cluster state) exist for times and fail the test cleanup before it removed from cluster state.

**Comment by xuezhou25** [comment] 2022-01-10 18:21
I am closing this issue because the failure is not reproducible and not be seen for a while. If the failure shows again or someone can reproduce it reliably, feel free to reopen it😄

**Closed by xuezhou25** 2022-01-10 18:21 UTC
Labels: >test-failure, v2.0.0, distributed framework
