### ISSUE TITLE
[BUG] Opensearch 2.0 maxClauseCount Errors

### ISSUE THREAD

**Issue by CayvonH** [opensearch-project/OpenSearch#3652] opened 2022-06-22 17:02 UTC
**Describe the bug**
Upgrade to Opensearch 2.0 causing:
```
{"error":{"root_cause":[{"type":"too_many_nested_clauses","reason":"too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 4096"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{ ...
```

When searching in opensearch-dashboards with a lucene query such as `A OR B OR C OR D` this expansion error occurs but if I split the query to something like `A OR B` I can get passed the expansion error. The total number of fields in the index is ~2000. Elasticsearch 7.10.2 has no issue with the same index.

**To Reproduce**
1. Create an index with ~2000 fields
2. Issue a search query similar to:
```
"query": {
  "bool": {
    "must": [
      {
        "query_string": {
          "query": "A OR B OR C",
          "analyze_wildcard": true,
          "time_zone": "America/Chicago"
        }
      }
    ],
    "filter": [
      {
        "range": {
          "@timestamp": {
            "gte": "2022-05-11T13:27:05.002Z",
            "lte": "2022-05-11T13:30:49.682Z",
            "format": "strict_date_optional_time"
          }
        }
      }
    ],
    "should": [],
    "must_not": []
  }
}
```
3. Observe errors

**Expected behavior**
The above query should not error.

**Comment by CayvonH** [comment] 2022-06-22 19:24
Just tested with Opensearch 1.3.3, this version does not have this issue. Perhaps the cause is the lucene upgrade? Easier steps to reproduce:
```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.0.0
curl -XPUT -i -H "Content-Type: application/json" -k -u "admin:admin" "https://localhost:9200/test_index" -d @index.json
curl -i -k -u "admin:admin" "https://localhost:9200/test_index/_search?q=b+OR+a+OR+d"

{"error":{"root_cause":[{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 1024"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test_index","node":"SZHZ9La7Tb2KBFHzkTq-1A","reason":{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 1024"}}],"caused_by":{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 1024","caused_by":{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 1024"}}},"status":500}%
```

Where `index.json` is just:
```
{
  "mappings": {
    "properties": {
      "field0": {
        "type": "text"
      },
      "field1": {
        "type": "text"
      },
      "field2": {
        "type": "text"
      },
     ...
      "field519": {
        "type": "text"
      }
  }
}
```

**Comment by mattweber** [comment] 2022-06-22 19:32
This probably due to [LUCENE-8811](https://issues.apache.org/jira/browse/LUCENE-8811).

**Comment by andrross** [comment] 2022-07-08 16:15
I'm closing this because it looks like it is working as intended with new behavior for maximum clause count in Lucene 9. Please reopen if you think we should do anything differently here.

**Closed by andrross** 2022-07-08 16:15 UTC
Labels: bug, Indexing & Search
