### ISSUE TITLE
[BUG] Match_phrase_prefix query on a text field with setting index_prefixes works not well

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#9218] opened 2023-08-10 09:07 UTC
**Describe the bug**
When executing match_pharse_prefix query on a text field with multiple values and with setting index_prefixed, the documents which should be hit are not returned, but if the search keyword hits the first element in the text field, the document will be returned.

**To Reproduce**
1. Create a index with a text field which set `index_prefixes` using default properties.
```
PUT test11
{
  "mappings": {
    "properties": {
      "platform_name": {
        "type": "text",
        "index_prefixes": {}
      },
      "applications": {
        "properties": {
          "name": {
            "type": "text",
            "index_prefixes": {}
          },
          "app_version": {
            "type": "keyword"
          },
          "publisher": {
            "type": "text"
          }
        }
      }
    }
  }
}
```
2. Add a doc
```
POST test11/_doc/3?refresh
{
  "platform_name": "Red Hat",
	"applications.name": ["python-libs","bind-libs"]
}
```
3. Search the document, nothing will be returned
```
GET test11/_search
{
  "query": {
    "match_phrase_prefix": {
      "applications.name": "bind-libs"
    }
  }
}
```
4. Add another doc, change the order of elements in the field applications.name, execute the query in step 3, this document will be returned.
```
POST test11/_doc/3?refresh
{
  "platform_name": "Red Hat",
	"applications.name": ["bind-libs","python-libs"]
}
```
**Expected behavior**
Return the document not matter the order of the elements in the text field when executing match_phrase_prefix query.
In addition, match_phrase query works well in this case.

**Host/Environment (please complete the following information):**
 - OS: [macOS]
 - Version [2.9]

**Comment by Ei5enheim** [comment] 2023-08-10 12:25
Duplicate of: https://github.com/opensearch-project/OpenSearch/issues/9203

**Closed** 2023-08-10 14:30 UTC
Labels: bug, untriaged
