### ISSUE TITLE
[BUG] FsHealthService can cause node drops if disk utilization reaches 100%

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/OpenSearch#1041] opened 2021-08-03 12:31 UTC
**Describe the bug**
FsHealthService fails with ```java.io.IOException: No space left on device``` in case the disk utilization on the node reaches 100%. Disk full issue can arise due to multiple reasons such as issues with disk watermark configuration or disk initialisation check not kicking in-time due to  ``cluster.info.update.interval``.  This can end up in the node drop.

```
2021-08-03T05:02:05,428][ERROR][o.o.m.f.FsHealthService  ] [28c54db4129917b0371c73f05bfb9d1b] health check of [<****>/nodes/0] failed
java.io.IOException: No space left on device
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
        at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
        at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
        at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
        at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
        at java.base/java.io.OutputStream.write(OutputStream.java:122)
        at org.opensearch.monitor.fs.FsHealthService$FsHealthMonitor.monitorFSHealth(FsHealthService.java:186)
        at org.opensearch.monitor.fs.FsHealthService$FsHealthMonitor.run(FsHealthService.java:160)
        at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:226)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:765)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. Update cluster setting and remove disk water mark
2. Run indexing workload and allow disk to get full
3. Node with 100% utilization is kicked out of the cluster
4. Above error seen in the data node log

**Expected behavior**
Exceptions related to disk space full should be consumed by the FsHealthService and node should still remain part of the cluster.

**Comment by Bukhtawar** [comment] 2021-08-03 16:54
Duplicate of #1040 This is not a bug as this can manifest even with lag detector kicking the node out on disk full

**Comment by dblock** [comment] 2021-08-03 17:02
Closing as dup.

**Closed by dblock** 2021-08-03 17:02 UTC
Labels: bug, good first issue, v1.1.0

**Comment by getsaurabh02** [comment] 2021-08-03 17:28
@dblock In my opinion this not by design but a bug since the intent ``FsHealthService `` is to detect grey disk issues such as read only file system, which is currently failing and kicking out nodes on disk being full. I have seen this happening even if indexing traffic has stopped, and node is unable to join back the cluster. My take on this is that the exception related to disk space full should be consumed by the FsHealthService and node should not be kicked out of the cluster as suggested above.

Also this is similar to #1040, however #1040 is more specific version of this issue where issue happens post segment merges. I see there are other ways how disk full scenario can occur, such as combination of change in disk water mark setting and shard relocation.

**Comment by dblock** [comment] 2021-08-03 17:35
I agree that #1040 is a narrower example of this issue, so we can leave that one open and when fixed we should re-examine this one and make sure that's fixed too. Or do you think we should reopen this one specifically?

@Bukhtawar saying this is not a bug, you two should agree ;)

**Comment by getsaurabh02** [comment] 2021-08-03 17:39
@dblock I am fine either ways. However the fix proposed for both the issues are different though. 
I will let @Bukhtawar comment and decide if this is a concern wrt to FsHealthService behaviour, or I am missing out something here.

**Comment by Bukhtawar** [comment] 2021-08-03 18:06
Few things to consider
1. Firstly a node should very rarely run full on disk, segment merges is something we plan on fixing in Lucene to not make an attempt if the disk is low or fail gracefully when merge runs out of disk
2. If the node is running full for a pro-longed interval, writes would anyways fail, failing the shard on the node(this is by design). The reads can work until the next cluster state update
3. Once the cluster state update happens and the node is unable to write the new metadata onto the disk, master starts a Lag Detector to kick out lagging nodes in the cluster. This is imperative to ensure that cluster metadata on nodes aren't stale, should it be stale it might turn out poisonous for the entire cluster
4. The Lag detector today will flip-flop the node causing a loop of joins and disconnects with every cluster state update
5. The idea of #1040 is to detect a persistent nature of failure where all attempts to relocate the shards off the node have failed and the node cannot cannot operate normally mandating an external intervention.
