### ISSUE TITLE
[BUG] The bundled JDK cannot be downloaded

### ISSUE THREAD

**Issue by xiaodizi** [opensearch-project/OpenSearch#7187] opened 2023-04-17 09:13 UTC
<img width="972" alt="image" src="https://user-images.githubusercontent.com/10411525/232439390-ca99cd96-acbe-45de-a895-996422fa9c8c.png">

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/10411525/232439564-6c0ffa43-6217-4ec6-84a6-d6e544651b65.png">
Can I choose not to download this jdk? I AM NOW in China network is not good, has been downloading failure, I have been looking for a long time, this is where to call? I want to modify the call to my local, but I can't find it.

**Comment by Hailong-am** [comment] 2023-04-18 15:18
@xiaodizi you can customize the java_home https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#custom-runtime-jdk

and the download logic is here [runtime-jdk-provision.gradle](https://github.com/opensearch-project/OpenSearch/blob/main/gradle/runtime-jdk-provision.gradle#L19)
and 
 [JdkDownloadPlugin](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java)

**Comment by xiaodizi** [comment] 2023-04-19 01:16
> 

Thanks, I found this location and I am trying to change it.

**Comment by kotwanikunal** [comment] 2023-05-18 20:10
> @xiaodizi you can customize the java_home https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#custom-runtime-jdk
> 
> and the download logic is here [runtime-jdk-provision.gradle](https://github.com/opensearch-project/OpenSearch/blob/main/gradle/runtime-jdk-provision.gradle#L19) and [JdkDownloadPlugin](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java)

Closing this issue since a bunch of alternatives were provided and the issue is unrelated to OpenSearch itself. :)

**Closed by kotwanikunal** 2023-05-18 20:10 UTC
Labels: help wanted, non-issue
