### ISSUE TITLE
[BUG] DiskThresholdDeciderIT/CreateIndexIT Test Failures

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#6217] opened 2023-02-07 10:33 UTC
```
org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testIndexCreateBlockWithAReadOnlyBlock
org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testIndexCreateBlockIsRemovedWhenAnyNodesNotExceedHighWatermark
```

```
org.opensearch.action.admin.indices.create.CreateIndexIT.testCreateAndDeleteIndexConcurrently
org.opensearch.action.admin.indices.create.CreateIndexIT.classMethod
```
URL: https://build.ci.opensearch.org/job/gradle-check/10769/

**Comment by Bukhtawar** [comment] 2023-02-07 10:33
@RS146BIJAY can you please take a look.

**Comment by RS146BIJAY** [comment] 2023-02-08 12:13
Closing this as there is already existing github issues for both the above flaky test failures [DiskThresholdDeciderIT](https://github.com/opensearch-project/OpenSearch/issues/5956) and [CreateIndexIT](https://github.com/opensearch-project/OpenSearch/issues/5425).

**Comment by anshu1106** [comment] 2023-02-08 13:38
failure seen in https://build.ci.opensearch.org/job/gradle-check/10833/

**Comment by dbwiddis** [comment] 2023-02-10 21:13
Closing as a duplicate of #5956 and #5425

**Closed by dbwiddis** 2023-02-10 21:13 UTC
Labels: bug, untriaged, flaky-test
