### ISSUE TITLE
Flattened data type

### ISSUE THREAD

**Issue by XiaoConstantine** [opensearch-project/OpenSearch#5404] opened 2022-11-29 23:02 UTC
**Is your feature request related to a problem? Please describe.**

As a AWS Opensearch user (we are on AWS ElasticSearch 7.10), we are currently facing the mapping explosion issue.

A bit of investigation leads me to the flattened data type, which seems to be a great feature to avoid mapping explosion, per [Flattend Data Type](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html#flattened)

Checking current opensearch master, I m not seeing we have this field mapper, wondering if there's plan to porting this feature to OpenSearch

**Describe the solution you'd like**
Port this feature to the supported AWS ElasticSearch version. (probably not feasible, seems 7.10 is the latest version AWS will support ElasticSearch)

**Describe alternatives you've considered**
Porting this to OpenSearch 2.0?

**Additional context**

**Comment by reta** [comment] 2022-11-30 13:56
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/1018

**Closed by reta** 2022-11-30 13:56 UTC
Labels: enhancement, untriaged
