### ISSUE TITLE
[BUG] :test:fixtures:s3-fixture:composeUp (random test failure)

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/OpenSearch#1566] opened 2021-11-16 18:22 UTC
**Describe the bug**
Random Test Failure. Please dig in, and figure out what went wrong :(

[https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1067_reports.zip](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1067_reports.zip)

**Comment by andrross** [comment] 2021-12-10 23:39
Another instance of same failure: https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/1447

**Comment by reta** [comment] 2021-12-29 19:23
@CEHENKLE could you please close this one as duplicate of https://github.com/opensearch-project/OpenSearch/issues/1806, thank you.

**Closed** 2021-12-29 19:24 UTC
Labels: bug, Flakey Random Test Failure

**Comment by CEHENKLE** [comment] 2022-01-02 02:09
Thanks @dblock  (and @reta for pointing it out :) )  

/C
