### ISSUE TITLE
Introduce new Consolidated Backpressue API

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#7760] opened 2023-05-25 19:43 UTC
**Is your feature request related to a problem? Please describe.**
Currently we using three different backpressure mechanisms to reject write requests from users [Shard Indexing backpressure, Segment Replication backpressure, Remote Storage backpressure]. And we have three different API's to fetch the metrics related to each mechanism individually. 

With the Introduction of new Consolidated API for backpressure it would be easy for the user to just call one API to know why write requests are getting rejected instead of calling each backpressure mechanisms API individually.

This consolidated API will not replace existing backpressure mechanisms individual API as those are needed for more deep level granular details. 

**Describe the solution you'd like**
Introduce a new REST API for backpressure to consolidate high level metrics of all 3 existing backpressure mechanisms.

**Describe alternatives you've considered**

**Additional context**

**Comment by mch2** [comment] 2023-05-25 20:46
@Rishikesh1159 This looks like a duplicate of https://github.com/opensearch-project/OpenSearch/issues/7683

**Closed** 2023-05-25 21:31 UTC
Labels: enhancement, untriaged
