### ISSUE TITLE
[BUG][Segment Replication] Failing flaky test SegmentReplicationIndexShardTests.testReplicaReceivesLowerGeneration

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#4976] opened 2022-10-28 17:21 UTC
**Describe the bug**
The test case shows flaky failures - org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaReceivesLowerGeneration 

**To Reproduce**
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaReceivesLowerGeneration" -Dtests.seed=25A1BC6ABB78D54B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=hu -Dtests.timezone=Australia/Darwin -Druntime.java=17

org.opensearch.index.shard.SegmentReplicationIndexShardTests > testReplicaReceivesLowerGeneration FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([25A1BC6ABB78D54B:AACF30236089C3AF]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.index.shard.SegmentReplicationIndexShardTests.assertEqualCommittedSegments(SegmentReplicationIndexShardTests.java:717)
        at org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaReceivesLowerGeneration(SegmentReplicationIndexShardTests.java:306)

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Rishikesh1159** [comment] 2022-11-09 15:44
Tried looking through code to reproduce this failure. But couldn't reproduce this anytime. Closing this issue for now. If anyone find this test failing again feel free to reopen the issue.

**Closed** 2022-11-09 15:45 UTC
Labels: bug, distributed framework, flaky-test
