### ISSUE TITLE
COMPAT locale provider will be removed in a future release

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#11550] opened 2023-12-09 20:44 UTC
From https://bugs.openjdk.org/browse/JDK-8305402

> COMPAT locale provider has remained to keep the backward compatibility of JDK 8's locale data, since CLDR-based locale data became the default in JDK 9. The intention was to encourage applications to migrate to CLDR, so for future removal of the COMPAT locale provider, acknowledging the user of future removal is recommended.

**To Reproduce**
1. Run tests on a plugin using JDK 21 
2. Observe multiple warnings:
```
> Task :test
Dec 09, 2023 12:30:31 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release
```

**Expected behavior**
No warnings.

**Plugins**

Error occurs when testing any plugin which inherits from `OpenSearchTestBasePlugin`

**Host/Environment (please complete the following information):**
 - OS: macOS 14.1.2 (aarch64)
 - JDK Version 21.0.1

**Additional context**

The locale is set here:

https://github.com/opensearch-project/OpenSearch/blob/3c14cc187525fde6cc24fd5e3acec18c44ce9a1d/buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java#L113

The fix is to simply replace `COMPAT` with `CLDR`.   _Some tests will break and will need to be fixed._

Note that the "breaking change" here was the JDK default behavior, so this only breaks our tests which explicitly set COMPAT, overriding the default JDK.  SO this should be safe to backport.

CLDR is supported since JDK11: https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html

**Comment by peternied** [comment] 2024-02-07 16:42
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@dbwiddis Thanks for filing this issue.

Before backporting this to 2.x please be sure that isn't a breaking change, as it looks like it could be.

**Comment by dbwiddis** [comment] 2024-02-07 17:16
@peternied Good call-out.  I did research and this is a breaking change in terms of output format, so should be 3.x only.

@hurutoriya I see you got started on a PR for this. Will you be updating that?

**Comment by dbwiddis** [comment] 2024-02-07 18:01
@peternied Looked at this again, I don't think it's a breaking change.

The actual breaking change was in upgrading JDK8 to any later JDK.   We explicitly set the locale in our tests to enforce the older behavior.   So this only breaks tests, and anyone already using a later JDK than 8 either has updated to the new code, or is explicitly setting COMPAT themselves.

**Comment by akolarkunnu** [comment] 2024-05-28 09:26
Since this bug is unassigned, assigning to me and I am working on the fix.
Let me know, if anyone else is working on this issue.

**Comment by andrross** [comment] 2024-05-31 20:15
@akolarkunnu Yeah I think we should handle it in all places. Seems reasonable to take care of all of them at the same time, assuming the fix doesn't grow too large.

**Comment by reta** [comment] 2024-06-06 16:55
Reopening the issue, the change introduced new flaky tests and was reverted: https://github.com/opensearch-project/OpenSearch/pull/14039

**Comment by akolarkunnu** [comment] 2024-06-07 07:45
> Reopening the issue, the change introduced new flaky tests and was reverted: #14039

I believe this is a consistent failure, so this test JavaJodaTimeDuellingTests is not part of CI, I ran CI multiple times and didn't observe this failure.

**Comment by reta** [comment] 2024-06-07 11:39
> Is it a random failure or consistent in CI ? If it happened multiple times, can I get that multiple error traces ?

It is all provided in the description of https://github.com/opensearch-project/OpenSearch/pull/14039:

```
./gradlew ':server:test' --tests "org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns" -Dtests.seed=D64AD5330C8A32D4
```

```
./gradlew ':server:test' --tests "org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns" -Dtests.seed=5593D79ECB158B24

```

**Comment by akolarkunnu** [comment] 2024-06-11 06:25
A simple reproducer of this issue: 

import java.util.Locale;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;

public class TestClass {
public static void main(String[] args) {
	System.setProperty("java.locale.providers", "SPI,CLDR");
	DateTime dateTime = DateTimeFormat.forPattern("YYYY-MM-dd'T'HH:mm:ss.SSSZ")
            .withOffsetParsed()
            .parseDateTime("2019-01-01T01:01:01.001+0000");
	String jodaZoneId = DateTimeFormat.forPattern("YYYY-MM-dd'T'HH:mm:ss.SSSz")
			.withLocale(Locale.forLanguageTag("sd-Arab")).print(dateTime);
        System.out.println("jodaZoneId: " + jodaZoneId);
}
}

**Comment by reta** [comment] 2024-06-11 12:24
@akolarkunnu I would like to point out this is not a single case - there are other failing combinations.

**Comment by akolarkunnu** [comment] 2024-06-11 13:27
@reta Can you please share the details.

**Comment by reta** [comment] 2024-06-11 13:33
> @reta Can you please share the details.

2 are above, for others - run `./gradlew ':server:test' --tests "org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns"` repeatably to have more seeds tested

**Comment by akolarkunnu** [comment] 2024-06-11 13:44
> > @reta Can you please share the details.
> 
> 2 are above, for others - run `./gradlew ':server:test' --tests "org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns"` repeatably to have more seeds tested


ok, that means the same test case fails for different time zones, that's expected. Any other test cases or use cases are affected?

**Comment by reta** [comment] 2024-06-11 14:04
> Any other test cases or use cases are affected?

I don't know at this moment

**Comment by akolarkunnu** [comment] 2024-06-14 01:30
I reported a bug against OpenJDK about this behavioral change(https://bugs.openjdk.org/browse/JDK-8334225) and their explanation is:
"CLDR v45 has the following translation of "Etc/UTC" (an alias to "UTC") zone in Sindhi language:
https://unicode.org/cldr/charts/45/summary/sd.html#4c4fea4c1e106866
Thus the behavior is the expected one."

So I will adjust the test case assertion accordingly.

**Closed** 2024-06-15 00:41 UTC
Labels: good first issue, CI, Plugins, v3.0.0, Build
