### ISSUE TITLE
[BUG]For ES version after 6.0.0 the index seems to be created with " index.mapper.dynamic " attribute which ideally it should not have

### ISSUE THREAD

**Issue by niravpi** [opensearch-project/OpenSearch#3879] opened 2022-07-13 13:00 UTC
**Describe the bug**
For ES version after 6.0.0 seen some specific case where the index seems to be created  with " index.mapper.dynamic " attribute which should not happened as while I am trying the change this setting getting below error 
```
"error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Setting index.mapper.dynamic was removed after version 6.0.0"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Setting index.mapper.dynamic was removed after version 6.0.0"
  },
  "status" : 400
```
But where as I can see that some index which are created in the 1.0.0 version are having this settings which we are not able to change or remove 

Sample settings
```
"index" : {
        "creation_date_string" : "2022-03-03T00:45:30.711Z",
        "refresh_interval" : "30s",
        "number_of_shards" : "5",
        "provided_name" : "index name",
        "mapper" : {
          "dynamic" : "false"
        },
        "creation_date" : "1646268330711",
        "number_of_replicas" : "3",
        "uuid" : "Some UUID",
        "version" : {
          "created_string" : "1.0.0",
          "created" : "135217827"
        }
      }
```

**Expected behavior**
Newly created index on ES version above 6.0.0 should not have this settings

**Comment by shwetathareja** [comment] 2022-07-14 12:38
@dblock : this code path has not changed in OpenSearch 2.0, It might still be there. I will take a look at this one.

**Comment by derek-ho** [comment] 2022-10-13 19:47
Hey folks, I am trying to connect Jaeger with Opensearch and getting this same error on startup of the Jaeger Collector. Could somebody take a look? Happy to hop on a call and try to reproduce this issue

**Comment by shwetathareja** [comment] 2022-10-14 10:34
@derek-ho : can you provide details on Jaeger Collection? How does it connect? Is the index created manually or using auto creation? is the error for existing index or during creation?

**Comment by derek-ho** [comment] 2022-10-14 14:02
I am using Jaeger version 1.38.1. I believe it is connecting with the ES go client: 
https://github.com/jaegertracing/jaeger/blob/3d67ac86f53866332568b0f542265b00d86407fc/plugin/storage/es/spanstore/writer.go#L48
https://github.com/jaegertracing/jaeger/blob/3d67ac86f53866332568b0f542265b00d86407fc/plugin/storage/es/spanstore/writer.go#L110
But I am not sure. I think it is getting auto created, and the error seems to imply it is for creating the index itself. Let's jump on a call next week to dig deeper.

**Comment by derek-ho** [comment] 2022-10-14 14:04
They do not have a dedicated Opensearch connection package yet - this is using the same one that is used to connect to Elasticsearch; that is one of the TODO's. However, I would like to investigate whether this problem might arise when a Opensearch connection package is written as well.

**Comment by shutlle** [comment] 2022-10-26 13:45
Hi, we have same error with OpenSearch 2.2.0 and Jaeger 1.38.1
Any additional information about this issue?

**Comment by derek-ho** [comment] 2022-10-26 18:21
@shutlle can you run with --es.version=7? That fixed the issue for me.

**Comment by hardened-user** [comment] 2022-11-09 11:10
@derek-ho it's work

**Comment by peternied** [comment] 2023-11-14 00:10
Saw this issue today, I'll see about making this more addressable so that you can 'unset' the value rather than being stuck deleting the index.

**Comment by peternied** [comment] 2023-11-14 03:20
See #11193 for the fix, I ended up expanding the fix to allow the setting value to be null or false - this should mitigate migration issues when no backwards capability issue would occur.  This would also allow indices that were using this setting to be unset so they can be cleanly migrated.

**Comment by mgodwan** [comment] 2024-02-21 06:35
@peternied Do we know the root cause around how this setting was added to the index in OS 1.0 created index in the first place? I was trying to go through the issue but could not find the root cause through the trail. Is it just part of `include_defaults` response?

**Comment by peternied** [comment] 2024-02-21 14:09
> root cause around how this setting was added to the index in OS 1.0 created index in the first place

@mgodwan No, in the cases where I've encountered this issue the cluster operator did not remember the historical context and I didn't find any traces of how the index came to be.  I'm going to close this specific issue as I've got a fix for this case, lets keep tracking the root cause investigation in [1]. 

- [1] https://github.com/opensearch-project/OpenSearch/issues/12350

**Closed** 2024-02-21 14:51 UTC
Labels: bug, Indexing & Search, v3.0.0, v2.13.0
