### ISSUE TITLE
[BUG] improper shard distribution in search nodes after scaling.

### ISSUE THREAD

**Issue by Dileep-Dora** [opensearch-project/OpenSearch#14747] opened 2024-07-15 10:33 UTC
### Describe the bug

When adding search nodes to existing cluster, ideal expectation is all search nodes having equal number of shards, but this is not happening. We had to delete all the indices and restore all at once in order to get the equal distribution, Which implies availability of overall service

### Related component

Search:Searchable Snapshots

### To Reproduce

1. create a cluster with search nodes
2. ingest some data in 2-3 indices
3. take snapshots
4. delete and restore on search nodes
5. add extra search nodes and verify shards distribution

### Expected behavior

After adding extra search nodes, all search nodes should have equal number of shards.

### Additional Details

Opensearch
version: 2.13

**Comment by kkhatua** [comment] 2024-07-24 16:24
Adding new nodes will not necessarily move shards from the older nodes to the new nodes to rebalance. This is because moving shards is essentially a peer recovery activity and consumes resources that could be critical to traffic. 

Lucene shards tend to be sticky in nature and will stay on a node as long as there are no violations.

When users add nodes, it might be due to the cluster already having a high shard count or disk usage. In a scenario for the latter, adding new nodes will cause any old nodes exceeding threshold to relocate the shards to nodes with more disk space (in this case, the new nodes). 

A simple way to achieve a balanced cluster after adding new nodes would be to explictly set the `cluster.routing.allocation.total_shards_per_node` to a value that will target approximately the average shards with the larger cluster's node count. 

There has been a discussion of making this automatic, but the competing resources of shard migration is why this has not been automated. A monitoring system, however, could look at `cat/alocation` API and based on the skew periodically update this threshold and achieve the same effect.

(Closing this as it is working as designed)

**Closed by kkhatua** 2024-07-24 16:24 UTC
Labels: bug, Search:Searchable Snapshots, ShardManagement:Routing

**Comment by jed326** [comment] 2024-07-24 16:26
Also for Searchable Snapshots specifically, we balance only by average primary shard count:

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java#L232-L267
