### ISSUE TITLE
[BUG] version number is incompatible with existing ES clients

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/OpenSearch#693] opened 2021-05-12 19:24 UTC
**Describe the bug**
The API which provides version includes a field `version.number`. Clients parse this value to determine what version of ElasticSearch is running, and is used for checking API compatibility.

In ElasticSearch 7.10, this value is reported as `7.10`.

In OpenSearch 1.0.0, the value is `1.0.0-SNAPSHOT`.

Existing clients which parse this string are unable to communicate with OpenSearch when they rely on the value of the version.

**To Reproduce**

1. Start ElasticSearch 7.10
2. `curl http://localhost:9200`
3. Read `version.number`.
4. Start OpenSearch
5. `curl http://localhost:9200`
6. Read `version.number`.

**Expected behavior**

Because OpenSearch uses the same API as ElasticSearch 7.10.2, the value of `version.number` should be `7.10.2`.

Expected:

```
  "version" : {
    "number" : "7.10.2",
```

Actual:

```
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0-SNAPSHOT",
```

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**

We confirmed that this is the cause of #667. It also appears that this may be causing #669.

**Comment by dlvenable** [comment] 2021-05-12 20:51
Since the problem is only with the `number` property, a possible solution would be:
* Retain the `number` property as matching the ElasticSearch API version
* Add a new property representing the OpenSearch version.

For example:

```
"version" : {
    "distribution" : "opensearch",
    "number" : "7.10",               // This is the ES API
    "opensearchVersion" : "1.0.0"    // This is the OpenSearch version
    ...
}  
```

There is probably a property name to use rather than "opensearchVersion." But, the advantage of this solution is that callers can know the ElasticSearch API version and the actual OpenSearch version (if that matters to the client).

**Comment by dblock** [comment] 2021-05-13 17:34
Doesn't feel right that we're retaining ES number anywhere. Are we saying that we don't want clients to have to modify anything to work against OpenSearch?

**Comment by dlvenable** [comment] 2021-05-13 18:44
Yes, I believe that clients should not have to make changes to migrate from ElasticSearch 7.10.2 to OpenSearch 1.0. We've already found that Logstash with the Logstash ES plugin can work with OpenSearch if we manually change `version.number` to `7.10.2`.

The [introduction blog post](https://aws.amazon.com/blogs/opensource/introducing-opensearch/) also indicates this is the case.
> The Amazon OpenSearch Service APIs will be backward compatible with the existing service APIs to eliminate any need for customers to update their current client code or applications. 

Clients could assert compatibility with OpenSearch by using the new `distribution` field which has already been added.

Additionally, the solution I proposed above may serve as a stepping stone from OpenSearch 1.x to 2.x. The change allows existing clients to work with OpenSearch 1.x without modifications (assuming other APIs are still compatible). Clients and libraries could eventually move to support OpenSearch only, or attempt to support both ElasticSearch and OpenSearch by utilizing the `distribution` field. Perhaps OpenSearch 2.x would remove the `version.number` entirely in favor of `version.opensearchVersion`.

For example, clients could start to write code along these lines. It would be compatible with the suggestions above and would continue to work if `version.number` were removed in 2.x.

```
if version.distribution == 'opensearch':
  if version.opensearch.startsWith('1.x'):
    handleOpensearch1();
else:
  if version.opensearch.startsWith('7.x'):
    handleElasticsearch7();
```

**Comment by dblock** [comment] 2021-05-13 20:04
I am 💯  with you on backward compatibility, but OpenSearch didn't break backward compatibility by changing the value of `version.number` (the API continues to return the same fields, including `number`, but a value has changed to `1.0-...`). Even though reverting it to 7.x seems to work around the problem, someone should figure out what the actual root cause of #667 is without that. The exception produced (`java.lang.IllegalArgumentException: mapper [log.level] cannot be changed from type [keyword] to [text]`) looks odd to me.

Someone here will definitely get to #667 in order, but don't let them beat you to it :)

**Comment by jcgraybill** [comment] 2021-05-13 20:08
@dlvenable raises a great point that this is almost certainly going to be more than a logstash issue: a lot of clients that interact with OpenSearch are going to check the version # to know the wire protocol to use. The proposed solution seems really elegant: keep version.number at 7.10.2 which reflects the API compatibility and lets current clients work without changing, and have a separate openSearchVersion identifier for new clients.

**Comment by dblock** [comment] 2021-05-13 20:54
@jcgraybill I think I agree, but I do worry that this could lead to users having broken software more often as a production surprise. We'd be asserting that OpenSearch 1.0 works just like ES 7.10 in _every way_ rather than the fact that it _has a backward-compatible API_ that minimizes client code changes.

Either way, we need to contribute integration tests against OpenSearch to https://github.com/logstash-plugins/logstash-output-elasticsearch. It currently runs against multiple versions of ES.

**Comment by dlvenable** [comment] 2021-05-14 14:25
@dblock , Thanks for engaging on this.

I'm unsure exactly what issues you might be imagining. Are they problems with automated tools expecting specific behavior from specific versions? Or more of a human-related issue?

With the latter, I could see an issue with logging. Code like `log.info("ElasticSearch version {}", version.number)` would log out `ElasticSearch version 7.9.2`. That could lead to confusion for human operators.

It is likely a fair assumption that automated clients which parse the version mostly care about the major version, and maybe sometimes care about the minor version. The patch version is probably ignored.

Perhaps OpenSearch could have an alternate patch value? Some possible ideas are:
1. Format the OpenSearch version into the patch value. Something like `MMmmpp` (M=major, m=minor, p=patch).
2. Start at some large version and auto-increment from there
3. To support a 2-digit only patch, start at a smaller patch version and auto-increment from there

OpenSearch Version | Formatted | Auto-Increment | Auto-Increment w/ 2 Digits
------------ | ------------- | ------------- | -------------
1.0.0 | 7.2.10000 | 7.2.1001 | 7.2.51
1.0.1 | 7.2.10001 | 7.2.1002 | 7.2.52
1.0.2 | 7.2.10002 | 7.2.1003 | 7.2.53
1.1.0 | 7.2.10100 | 7.2.1004 | 7.2.54
2.0.0 | 8.0.20000 | 8.0.1000 | 8.0.51

Now that log line about could read `ElasticSearch version 7.9.10000`.

**Comment by nknize** [comment] 2021-05-14 16:11
Let's be careful not to engineer a ton of cosmetic surgery just to treat a secondary symptom. Doing so risks causing other problems. First things first, the backwards compatibility tests are still disabled; so we absolutely need to re-enable those in order to catch any/all other areas affected by the version rebase. (/cc @harold-wang) That's being worked now.

As for this particular symptom, the root cause is similar to the ["opensearch node fails to join" issue](https://github.com/opensearch-project/OpenSearch/issues/669) - /cc @shwetathareja. In short, since the server side transport layer is "version aware" of the client we can detect what version of the client is attempting to connect and "mask" the OpenSearch version to predecessor 7.10.2 appropriately. This is why we've been super thoughtful to have the 1.0.0 release not introduce any breaking changes from 7.10.2.

**Comment by nknize** [comment] 2021-05-14 16:16
> Perhaps OpenSearch could have an alternate patch value?

There is already a patch value in the semantic versioning system. (e.g., 1.0.0 is the 0 patch version of Major 1, Minor 0 release).  

Are you suggesting a "feature" or "nightly" number? This has been brought up before (in the context of plugins) and I think it's worth discussing as a separate topic independent of this particular bug because I think it has merit. Would you like to open a separate discuss issue?

**Comment by dlvenable** [comment] 2021-05-14 20:59
@nknize , The issue you referenced for ["OpenSearch node fails to join"](https://github.com/opensearch-project/OpenSearch/issues/669) mentions a "backward compatibility mode" solution. Is the idea that OpenSearch would report `version.number` as `7.10.2` when that flag is set? 

Regarding the patch idea, this was an extension of my original proposal. Rather than returning `7.9.2` as the version, we could have a different patch value so that human-operators can clearly see that it is OpenSearch. I offered it as a suggestion to @dblock 's concern:

> I do worry that this could lead to users having broken software more often as a production surprise.

**Comment by dlvenable** [comment] 2021-05-14 21:07
To elaborate on the purpose of this bug, we found that Logstash and Filebeats both fail to load templates when running against OpenSearch 1.0.0.

----

In local experiments, we modified [MainResponse](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/main/MainResponse.java#L122) to return a hardcoded value:

```
.field("number", "7.10.2")
```

After this change, Logstash and Filebeats can run against OpenSearch.

It does appear that this is the cause of #706 as well. I did not create the exact setup that author included. However, both of us saw this same error in OpenSearch 1.0.0.

```
couldn't load template: 400 Bad Request: {"error":{"root_cause":[{"type":"mapper_parsing_exception"
```

Again, that manual change to MainResponse was sufficient to get past the error.

**Comment by Smithx10** [comment] 2021-05-15 02:02
@dlvenable,

Just chiming in to say thanks,  and this worked in our testing.  https://github.com/opensearch-project/OpenSearch/issues/706#issuecomment-841582430

**Comment by nknize** [comment] 2021-05-15 02:28
> Is the idea that OpenSearch would report version.number as 7.10.2 when that flag is set?

No. I'm saying use the versioning system as it is intended (for backward compatibility) and fix MainResponse to [return the predecessor version for LegacyClients](https://github.com/nknize/OpenSearch/commit/798f614a0d86840ecbc58bd8a649c79c4d5955d2) which wasn't covered in the [initial patch](https://github.com/opensearch-project/OpenSearch/commit/6e04778d0c8aa33b3360bf6b000f85da93cec650#diff-dd348945320568d6b330e1ae112fb2f2d3906e19c307a9a75fee64bacb59718dR205) that adds the `distribution` key-value to the MainResponse to identify OpenSearch builds from `other` forks.

> In local experiments, we modified [MainResponse](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/main/MainResponse.java#L122) to return a hardcoded value:

No hardcoded values. It should be based on the client version. But as I mentioned, I wouldn't treat this symptom just yet while Backwards Compatibility testing is disabled. This could be "patching" one issue and causing another. This "fix" I'm suggesting is on hold until we can smoke test w/ bwc tests enabled.

**Comment by dblock** [comment] 2021-05-17 17:27
@harold-wang or @nknize, are you working on this?

**Comment by nknize** [comment] 2021-05-17 17:35
> @harold-wang or @nknize, are you working on this?

First [PR opened](https://github.com/opensearch-project/OpenSearch/pull/708)

**Comment by dlvenable** [comment] 2021-05-18 14:33
@nknize , As I understand PR #708, this will support the _internal_ node-to-node communication inside an ElasticSearch cluster.

I created this ticket mostly to support _external_ clients. Also, #667 and #706 relate to Logstash and Filebeats. How would ElasticSearch determine the client version in order to change the reported version number?

**Comment by nknize** [comment] 2021-05-19 16:30
> @nknize , As I understand PR #708, this will support the _internal_ node-to-node communication inside an ElasticSearch cluster.

It will support compatibility with transport layer clients. Those that don't connect via the transport layer and solely rely on a raw http call to obtain server version number in this manner will get the 1.0.0 OpenSearch version; and that should be the correct behavior. Hard coding that to a spoofed version is not the solution, it's a hack, and OpenSearch doesn't provide any forward compatibility guarantees. The correct fix in this situation just might be to fork those clients and correctly add backward compatibility with legacy ES versions.

**Comment by mch2** [comment] 2021-05-28 23:04
For an immediate path forward - will put up a small change to support an optional config param in opensearch.yml.  The presence of this parameter controls which version is returned to external clients [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/main/MainResponse.java#L126). If the parameter is not present (default behavior) we return the current OpenSearch version.

**Comment by dblock** [comment] 2021-05-29 00:37
> For an immediate path forward - will put up a small change to support an optional config param in opensearch.yml. The presence of this parameter controls which version is returned to external clients [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/main/MainResponse.java#L126). If the parameter is not present (default behavior) we return the current OpenSearch version.

Will this be a node-local or a cluster-wide setting?

**Comment by dlvenable** [comment] 2021-05-29 00:55
> For an immediate path forward - will put up a small change to support an optional config param in opensearch.yml. The presence of this parameter controls which version is returned to external clients here. If the parameter is not present (default behavior) we return the current OpenSearch version.

This sounds like a good approach. In addition, I suggest that we either disable the [`distribution` property](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/main/MainResponse.java#L125), or assign it a different value than `opensearch`.

This way, clients can start to support different variations using code along these lines.

```
if version.distribution == 'opensearch':
  if version.opensearchVersion.startsWith('1'):
    compatibleWithElasticsearch7();
  if version.opensearchVersion.startsWith('2'):
    compatibleWithOpensearch2();
else:
  if version.number.startsWith('7'):
    compatibleWithElasticsearch7();
  if version.number.startsWith('6'):
    compatibleWithElasticsearch6();

```

**Comment by mch2** [comment] 2021-06-02 22:14
> Will this be a node-local or a cluster-wide setting?

After poking at this a bit, I think it makes sense to be a cluster wide setting to protect against inconsistencies across nodes & the convenience of setting it once with the update settings API during an upgrade.  I threw up an example of this [here](https://github.com/mch2/OpenSearch/commit/ee42286f9a29454b2deee123cb28c13965653efd) 

@dlvenable I'm not sure I'm following your suggestion for the distribution property.  This was introduced with opensearch [here](https://github.com/opensearch-project/OpenSearch/commit/6e04778d0c8aa33b3360bf6b000f85da93cec650#diff-dd348945320568d6b330e1ae112fb2f2d3906e19c307a9a75fee64bacb59718dR205).  If not an opensearch distribution, it should be empty / another value allowing the client code you are suggesting?

**Comment by elfisher** [comment] 2021-06-02 23:00
Reading through this, I'm wondering if the YML update is the only way we want to support setting versions. Having a REST API would be convenient as it would not require cluster restarts. There would probably need to be some way to durably persist the value set in the event the cluster would restart. Alternatively we could just read off the YML as a baseline after restarts. Just a thought.

**Comment by dlvenable** [comment] 2021-06-02 23:42
@mch2 ,

What I was suggesting was that when we are in backward compatibility mode, we return `null` or some other constant for `distribution`.

e.g.

```
version: {
  "number" : "7.10.2",
  "distribution" : null
 ... 
}
```

When not in that mode, we return it exactly as it is presently.

```
version: {
  "number" : "1.0.0",
  "distribution" : "opensearch"
 ... 
}
```

The reason for this suggestion is to support a migration path toward the new `1.0.0` OpenSearch version. 

Clients can write code that alters the meaning of `1` and `7` depending upon the presence of `distribution==opensearch`.

**Comment by dlvenable** [comment] 2021-06-02 23:47
The `distribution` change I suggested might not be necessary however since there is presently no OpenSearch 7.

Clients could write code along the lines of:

```
if distribution == "opensearch":
  if majorNumber == 1 || majorNumber == 7:
    doSomethingForElasticSearch7()
if distribution is null:
  readElasticSearchVersions()
```

This code would be valid until OpenSearch 7 is released. At that point in time it would be incorrect.

**Comment by shwetathareja** [comment] 2021-06-03 04:32
> > Will this be a node-local or a cluster-wide setting?
> 
> After poking at this a bit, I think it makes sense to be a cluster wide setting to protect against inconsistencies across nodes & the convenience of setting it once with the update settings API during an upgrade. I threw up an example of this [here](https://github.com/mch2/OpenSearch/commit/53e21369300e93c81ec55246f777be4c0ec2af37)
> 
I am wondering is this going to be an advanced control being offered to users to run in BWC mode for the main response (localhost:9200). There are few other APIs which return node version like _cat/nodes, with this change localhost:9200 with return version as 7.10.2 but _cat/nodes will still return version as 1.0.0. @elfisher is this expected or the plan is to change all the API response?

IMO, if it is an advanced control it can even be provided as a system property (that ways it is not a recommended option but still a way out in case user gets stuck like in this case)

Also, what is the plan to make all these clients understand OpenSearch distribution?

**Comment by elfisher** [comment] 2021-06-03 12:22
> @elfisher is this expected or the plan is to change all the API response?

My understanding from this issue is that the goal is to enable users to define their own version numbers for backwards compatibility/client compatibility where version checking could happen. If the version number is returned in multiple routes my instinct is to make that value consistent across all routes. Inconsistencies with version numbers across different API calls might cause unintended bugs/side effects. Is the version value used in the different API calls fetched some sort of global variable?

**Comment by dblock** [comment] 2021-06-03 14:14
Some random thoughts.

I would be very scared of a global, `opensearch.version` setting because it implies too many things. However, if we are confident that we can implement a complete 7.10.2 backwards compatibility mode that quacks like 7.10.2, then I think a global `opensearch.compatibility.version = 7.10.2` setting could make sense, it would not allow random values (only 7.10.2 and any future version we want to be compatible with) and `_cat/nodes` would then need to also return 7.10.2 and OpenSearch would need to behave like a 7.10.2 in every possible way. It might do it today and I think provides a good path to be forward compatible with 8.x if we chose to.

I have mixed feelings to be allowing any random version number in opensearch.yml, but I can see how it can be convenient if we only want to change the number in the REST API. If that's the case, I'd go with the most specific key to what's being changed, e.g. `opensearch.rest.api.version.number = 7.10.2`. That doesn't imply OpenSearch is running as 7.10.2, it just says that the API returns 7.10.2. It's a lot less work, but I suspect we might regret this choice and want to do the above at some point.

**Comment by dlvenable** [comment] 2021-06-03 14:54
> However, if we are confident that we can implement a complete 7.10.2 backwards compatibility mode that quacks like 7.10.2, then I think a global opensearch.compatibility.version = 7.10.2

I do think that this could be a very valuable field to include. It would provide the solution for clients going forward. Shall I open a ticket to discuss this idea further?

That idea would help with how clients are written going forward. For current versions of clients, we would still need to return `version.number: 7.10.2` in order for them to work without modification.

**Comment by elfisher** [comment] 2021-06-03 14:56
> However, if we are confident that we can implement a complete 7.10.2 backwards compatibility mode that quacks like 7.10.2, then I think a global `opensearch.compatibility.version = 7.10.2` setting could make sense, it would not allow random values (only 7.10.2 and any future version we want to be compatible with) and `_cat/nodes` would then need to also return 7.10.2 and OpenSearch would need to behave like a 7.10.2 in every possible way.

It makes sense to me that 7.10.2 would be what is targeted from a backwards compatibility perspective. My fear of not having consistent version numbers returned across the API is that clients/tools may be validating against version numbers in more than one place. The claim in [FAQ 1.8](https://opensearch.org/faq/#q1.8) on the website is that it API responses should "quack" like 7.10. Is there more than just version number that would cause it to not?

**Comment by dblock** [comment] 2021-06-03 16:41
> I do think that this could be a very valuable field to include. It would provide the solution for clients going forward. Shall I open a ticket to discuss this idea further?

No need, this is the issue and we're basically talking what the best implementation would be. Is someone already writing the code? @shwetathareja @nknize?

**Comment by nknize** [comment] 2021-06-03 17:04
Let's not overthink this hack. It's a stopgap solution for 1.0+ forward compatibility with existing legacy clients to prevent users from having to mass upgrade.


> The `distribution` change I suggested might not be necessary

It's not necessary but what your suggesting isn't a bad idea to spoof `MainResponse` exactly like a legacy cluster. This could be done in a follow up PR / "enhancement".


> my instinct is to make that value consistent across all routes

`/cat` API uses the transport layer. Changing it breaks nodes joining the cluster so we don't want to do this.




> I have mixed feelings to be allowing any random version number in opensearch.yml, but I can see how it can be convenient if we only want to change the number in the REST API.

Yes. This approach is a forward compatibility hack for MainResponse content until a compatibility module can do this "correctly". I would suggest that compatibility module provide an endpoint to return the spoofed version information instead of `:9200` returning a lie.



> Also, what is the plan to make all these clients understand OpenSearch distribution?

If OpenSearch sticks with Elastic clients then compatibility going forward is an unknown. Case in point: the [new java client](https://github.com/elastic/elasticsearch-java) which Elastic intends to replace the existing Java High Level rest client. At some point here (preferably before 2.0) OpenSearch will be forced to fork the clients to ensure compatibility with a diverging core.



> Having a REST API would be convenient as it would not require cluster restarts.

Rolling upgrades are required to deploy OpenSearch anyway.

**Comment by dblock** [comment] 2021-06-03 17:42
Assigned to @mch2

**Comment by mch2** [comment] 2021-06-03 22:07
Put up a draft [here](https://github.com/opensearch-project/OpenSearch/pull/814) for some initial comments

**Comment by liangxibing** [comment] 2021-06-07 23:32
Hi, do we have any idea when we will have this released?
Just tried latest opensearch docker image (with tag `1.0.0-rc1`), still return below version number:
```
{
  "name" : "6d33cb208961",
  "cluster_name" : "es-cluster",
  "cluster_uuid" : "Y034pkVIRxq7E4DtbPH6Kg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0-rc1",
    "build_type" : "tar",
    "build_hash" : "26d579287f50bb33e17c8fe1f05ea208d5c64d1f",
    "build_date" : "2021-05-28T18:18:49.848386Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }
}
```
And when logstash started, still report below errors:
```
logstash            | [2021-06-07T23:08:25,184][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Got response code '400' contacting Elasticsearch at URL 'https://es:9200/_template/logstash'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError" ...
```
```

**Comment by dlvenable** [comment] 2021-06-08 14:05
The upcoming change should certainly help allow easy migration to using OpenSearch with existing clients.

I also want to bring up the topic of how compatibility will be expressed going forward. Once an ES administrator flips the switch off, clients will need to examine at the `version.distribution` and `version.number` to determine how to communicate with the OpenSearch cluster. This means _clients_ must have built-in mappings from each OpenSearch version to compatible ElasticSearch versions.

For example, clients will need to know OpenSearch 1.0 is compatible with ElasticSearch 7.10, OpenSearch 2.0 is compatible with ElasticSearch 8.0 (hypothetically), OpenSearch 3.0 is compatible with ElasticSearch 8.5 (again, hypothetical), or whatever it is.

I'm hoping to open the discussion on how what support OpenSearch should provide for advertising ElasticSearch compatibility with clients. OpenSearch could make it easier for clients to know which ElasticSearch version the current OpenSearch version is compatible with. One possible solution is adding a new property named `version.compatibility_number` which would have the `7.10.2`.

For example, `curl http://localhost:9200` would have:

```
"version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0-SNAPSHOT",
    "compatibility_number" : "7.10"
```

This can make it much easier for clients to support both ElasticSearch and OpenSearch going forward.

I think one big question is whether OpenSearch will retain compatibility with ElasticSearch or not. If not, then something like this makes little sense. But if so, then this could be a good way to encourage clients to write code for both ElasticSearch and OpenSearch.

**Comment by dblock** [comment] 2021-06-08 16:16
> I think one big question is whether OpenSearch will retain compatibility with ElasticSearch or not. If not, then something like this makes little sense. But if so, then this could be a good way to encourage clients to write code for both ElasticSearch and OpenSearch.

OpenSearch is _derived_ from Elasticsearch. It's a fork at 7.10.2, so it's only compatible with ES until then. I expect ES to diverge. Clients can decide whether they want to support either or both. 

We tried to answer some of these questions in [the upgrading FAQ](https://opensearch.org/faq/#c3). If we didn't do a good job, maybe bring more questions up? Try to answer them in a PR and we can discuss!

**Comment by dlvenable** [comment] 2021-06-08 21:27
Thank you for clarifying on the current expectations for compatibility.

**Comment by shwetathareja** [comment] 2021-06-09 02:31
> We tried to answer some of these questions in [the upgrading FAQ](https://opensearch.org/faq/#c3). If we didn't do a good job, maybe bring more questions up? Try to answer them in a PR and we can discuss!

@dblock FAQ link is broken

**Comment by dblock** [comment] 2021-06-09 11:36
@shwetathareja Works for me... where does it land you? `https://opensearch.org/faq/#c3`

**Comment by dlvenable** [comment] 2021-06-23 20:47
@dblock , @nknize 
I want to bring up the idea of the `distribution` property again so that clients can know how to handle version going forward.

With the merge of #847 , if the setting is activated, then clients should get this:

```
"version" : {
    "distribution" : "opensearch",
    "number" : "7.10.2",
```

I believe that we want our clients to write code that can support all of these possibilities: ElasticSearch 7, OpenSearch 1 with version compatibility, and OpenSearch 1 without version compatibility. This helps with the migration path to OpenSearch 1 without version compatibility.

Currently, when in version compatibility mode, the client will have to add some short-term hack that also assumes OpenSearch 7 is the same as OpenSearch 1. Clients can write cleaner, more-robust code if we just remove the `distribution` value, or give it some other constant name, like `version-compatible-opensearch`. Then, OpenSearch 1 with version compatibility is treated like ElasticSearch 7 by the client.

**Comment by dblock** [comment] 2021-06-24 16:01
I see your point @dlvenable, we're going to have a problem when we release OpenSearch 7.10.2. WDYT @nknize @mch2?

**Comment by nknize** [comment] 2021-06-24 17:00
I think by the time OpenSearch 7.10.2 is released there will be a long tail divergence from the Elasticsearch codebase that this "compatibility" issue will be a distant memory. But this is a good point.

The `distribution` key-value was [added](https://github.com/opensearch-project/OpenSearch/commit/6e04778d0c8aa33b3360bf6b000f85da93cec650#diff-dd348945320568d6b330e1ae112fb2f2d3906e19c307a9a75fee64bacb59718dR178) as a way of tracking compatibility and "forked" distributions. It's a new field in OpenSearch that legacy clients (forward compatibilty) will not even be aware of so there should be no issue.  Nevertheless, for completeness we could simply not set this field when running in "compatibility" mode so that MainResponse looks exactly like the legacy response.

**Comment by dblock** [comment] 2021-06-24 17:51
I opened https://github.com/opensearch-project/OpenSearch/issues/880

**Comment by dlvenable** [comment] 2021-06-24 21:59
Yes, because ElasticSearch does not have the `distribution` property, that is why I think we can remove it in version compatibility mode. Ticket #880 is what I suggested and should help clients write code supporting different scenarios. Thanks!

**Comment by newzubakhin** [comment] 2021-07-07 20:54
Are you going to release a new RC in July with the fix? My team can't use filebeat in production

**Comment by dblock** [comment] 2021-07-07 21:09
A cluster setting was introduced in https://github.com/opensearch-project/OpenSearch/pull/847. We removed the distribution in backwards-compatible mode in https://github.com/opensearch-project/OpenSearch/pull/898. Set `compatibility.override_main_response_version` to put the cluster into a configuration that returns 7.10.2 as with ES OSS.

I am going to close this because the code is done. I added an issue to document it in https://github.com/opensearch-project/documentation-website/issues/72.

**Comment by dblock** [comment] 2021-07-07 21:09
> Are you going to release a new RC in July with the fix? My team can't use filebeat in production

This will be in 1.0 GA, shortly.

**Closed by dblock** 2021-07-07 21:09 UTC
Labels: Beta, Priority-Immediate, Severity-Critical, backwards-compatibility, bug
