### ISSUE TITLE
[BUG] High memory consumption

### ISSUE THREAD

**Issue by Mavtti** [opensearch-project/OpenSearch#15934] opened 2024-09-13 15:46 UTC
### Describe the bug

We are using aws opensearch and since upgrading from 2.11 to 2.15, the memory usage increased and it slows down the whole cluser.
The biggest impact is on write operations which started to timeout after the upgrade.

I've seen [this issue](https://github.com/opensearch-project/OpenSearch/issues/13927) but I thought that the issue was supposed to be fixed in 2.15.

Upgrade happened on the 10th.

Max memory utilization more than often reaches 100% since then.
![image](https://github.com/user-attachments/assets/9ff52208-9d0e-43b0-8369-a45c3da99db0)

There is also an increase in Java Heap memory
![image](https://github.com/user-attachments/assets/318ea504-e93d-4459-8a57-80a036d2f66b)

Any idea ? Thx !

### Related component

Other

### To Reproduce

1. Upgrade to 2.15

### Expected behavior

No issue when inserting data and lower memory consumption

### Additional Details

No modification on our side on memory settings

**Comment by reta** [comment] 2024-09-13 16:28
@Mavtti by any chance, could you capture class histogram to understand where the heap consumption is coming from? Thank you.

**Comment by Mavtti** [comment] 2024-09-16 08:51
@reta Sorry I never had to do it before, would you mind explaining me how to do it ? 

Btw, to mitigate the issue, we changed our instances type from t3 to m7g. It gave us more leeway. 
But at the same time, we also saw an issue with an ever increasing memory just like [this case](https://github.com/opensearch-project/OpenSearch/issues/12454#issuecomment-2174752960).

**Comment by reta** [comment] 2024-09-16 14:19
> @reta Sorry I never had to do it before, would you mind explaining me how to do it ?

Thanks @Mavtti , there are multiple ways to do that (we just need to do this on any node that consumes more heap):

- using jcmd (https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr006.html)
```
jcmd <pid> GC.class_histogram
```
- using jmap (https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr014.html)
```
jmap  -histo <pid>
```

**Comment by Mavtti** [comment] 2024-09-18 09:33
Hey since I'm on managed aws opensearch, there is no way for me to run these commands.

And I saw that the jackson issue was supposed to be fixed but we actually are on 2.15 (OpenSearch_2_15_R20240904 to be exact) and still see this issue.
![image](https://github.com/user-attachments/assets/07dda805-e0d1-4c25-8366-88ead297a246)

**Comment by reta** [comment] 2024-09-18 12:03
> Hey since I'm on managed aws opensearch, there is no way for me to run these commands.

Got it :(


> And I saw that the jackson issue was supposed to be fixed but we actually are on 2.15 (OpenSearch_2_15_R20240904 to be exact) and still see this issue.

Correct, the heap consumption might be caused by another issue

**Comment by Mavtti** [comment] 2024-09-18 15:30
So in the end, I can't give you more insight and there's not much you can do without it, correct ?

**Comment by reta** [comment] 2024-09-18 16:28
> So in the end, I can't give you more insight and there's not much you can do without it, correct ?

I think the best option we have is to engage with AWS support to ask for these details

**Comment by dblock** [comment] 2024-10-07 16:07
Let's close it here. Do post what you find through working with AWS support please for the next person.

[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

**Closed by dblock** 2024-10-07 16:07 UTC
Labels: bug, untriaged, Other
