### ISSUE TITLE
Add GH workflow for windows to gate PRs.

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#5323] opened 2022-11-21 19:49 UTC

**Comment by minalsha** [comment] 2023-02-03 00:12
@mch2  do we need this issue?

**Comment by mch2** [comment] 2023-02-03 17:23
Will close as a duplicate of - https://github.com/opensearch-project/opensearch-build-libraries/issues/114

**Closed by mch2** 2023-02-03 17:23 UTC
