### ISSUE TITLE
[BUG] GeoHashGridIT.testGeoShapes failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6222] opened 2023-02-07 17:15 UTC
See https://build.ci.opensearch.org/job/gradle-check/10743/consoleFull

```
REPRODUCE WITH: ./gradlew ':modules:geo:internalClusterTest' --tests "org.opensearch.geo.search.aggregations.bucket.GeoHashGridIT.testGeoShapes" -Dtests.seed=58EEE2632DEE6DD -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-OM -Dtests.timezone=Europe/Madrid -Druntime.java=19

org.opensearch.geo.search.aggregations.bucket.GeoHashGridIT > testGeoShapes FAILED
    Failed to execute phase [query], all shards failed; shardFailures {[C7ePtMCAQWamX99P3Fj6MA][geoshape_index][0]: RemoteTransportException[[node_s0][127.0.0.1:37239][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ArrayIndexOutOfBoundsException[Index 17680 out of bounds for length 17680]; }
        at __randomizedtesting.SeedInfo.seed([58EEE2632DEE6DD:EF3356E9BDA2B5C0]:0)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:663)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:372)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:698)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:471)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:294)
        at app//org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
        at app//org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74)
        at app//org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:747)
        at app//org.opensearch.transport.TransportService$6.handleException(TransportService.java:783)
        at app//org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1391)
        at app//org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1505)
        at app//org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1479)
        at app//org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:79)
        at app//org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:71)
        at app//org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:70)
        at app//org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103)
        at app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54)
        at app//org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
        at app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at app//org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
        at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
        at app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at java.****@19.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.****@19.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.****@19.0.2/java.lang.Thread.run(Thread.java:1589)

        Caused by:
        [Index 17680 out of bounds for length 17680]; nested: ArrayIndexOutOfBoundsException[Index 17680 out of bounds for length 17680];
            at app//org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:678)
            at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:370)
            ... 23 more

            Caused by:
            java.lang.ArrayIndexOutOfBoundsException: Index 17680 out of bounds for length 17680
                at org.opensearch.index.fielddata.SortingNumericDocValues.nextValue(SortingNumericDocValues.java:123)
                at org.opensearch.geo.search.aggregations.bucket.geogrid.GeoGridAggregator$1.collect(GeoGridAggregator.java:104)
                at org.opensearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:123)
                at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:222)
                at org.apache.lucene.search.MatchAllDocsQuery$1$1.score(MatchAllDocsQuery.java:63)
                at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71)
                at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
                at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:279)
                at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:250)
                at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:551)
                at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:349)
                at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:443)
                at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:432)
                at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:275)
                at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:152)
                at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:525)
                at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:589)
                at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:558)
                at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73)
                at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88)
                at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
                ... 8 more
```

/cc @navneet1v

**Comment by andrross** [comment] 2023-02-07 17:29
Also just want to note that this test appears to take about 3 minutes to run when it passes. These things can really add up (as evidenced by the fact that gradle check currently takes about half an hour) so if possible it would be great to see if we can get the same coverage with a faster test runtime.

**Comment by navneet1v** [comment] 2023-02-07 18:41
I will look into that. I am aware of the test runtime. but the longer runtime doesn't happen everytime. As the test data is generated randomly this sometime leads to test running long time.


The failure provided above is due to this high runtime. And there is no other failure from the tests.

**Comment by navneet1v** [comment] 2023-02-07 22:43
I am able to figure out the Root Cause of the Exception. I am currently working on it. Will raise PR soon.

**Comment by navneet1v** [comment] 2023-02-08 20:19
@andrross PR is raised https://github.com/opensearch-project/OpenSearch/pull/6242

**Comment by navneet1v** [comment] 2023-02-10 18:18
The PR is merged. Resolving the issue.

**Closed by navneet1v** 2023-02-10 18:18 UTC
Labels: bug, >test-failure, untriaged, flaky-test, Geospatial
