### ISSUE TITLE
Add support of "unsigned_long" Data Type in OpenSearch

### ISSUE THREAD

**Issue by vhordiienkohk** [opensearch-project/OpenSearch#7560] opened 2023-05-15 09:35 UTC
The current problem in OpenSearch is the lack of support for the "unsigned_long" data type. This limitation prevents developers from efficiently handling large numeric values without a sign. As a result, specific use cases involving unsigned long integers, such as network protocols, cryptographic operations, and hardware interfaces, cannot be effectively addressed within the OpenSearch ecosystem.

I would like to request the addition of support for the "unsigned_long" data type in OpenSearch. This enhancement would involve incorporating the necessary modifications to the OpenSearch core codebase, including indexing, querying, and mapping components, to enable seamless integration and handling of unsigned long integer values. By introducing support for the "unsigned_long" data type, developers would gain the ability to accurately represent and manipulate unsigned long integer data, expanding the scope of applications that can be built using OpenSearch.

Currently, developers working with OpenSearch have resorted to alternative solutions to work around the absence of "unsigned_long" support. These workarounds often involve converting unsigned long integers to other supported data types, which can be error-prone and inefficient and not very efficient for range queries. However, integrating native support for the "unsigned_long" data type would eliminate the need for these alternative approaches and provide a more streamlined and reliable solution.

The opensearch-java library version 2.4 already includes support for the "unsigned_long" data type. Therefore, incorporating this feature into OpenSearch would align it with the existing functionality available in the library and ensure consistency across the OpenSearch ecosystem. By addressing this missing capability, OpenSearch would significantly enhance its versatility and attract a broader community of developers who rely on the "unsigned_long" data type for their applications.

Please consider this feature request, as it would greatly improve the usability and effectiveness of OpenSearch in handling unsigned long integer values

**Comment by Yury-Fridlyand** [comment] 2023-05-16 02:36
Duplicate of #3538 and #2083

**Comment by dblock** [comment] 2023-05-16 17:50
Yep! And available since the next version of OpenSearch 2.8.0 :)

**Comment by dblock** [comment] 2023-05-16 17:50
@vhordiienkohk would you give a snapshot build a try and tell us whether the new feature works as expected for you?

**Closed by dblock** 2023-05-16 17:50 UTC
Labels: enhancement, untriaged
