### ISSUE TITLE
[BUG] Performance Regression in 2.14 and 3.0 hourly_aggs in http_logs workload

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/OpenSearch#13345] opened 2024-04-23 08:39 UTC
### Describe the bug

https://opensearch.org/benchmarks

![Screenshot 2024-04-23 at 2 10 27 PM](https://github.com/opensearch-project/OpenSearch/assets/81609427/8ad59633-e6c9-42d6-bf59-2398bc368e84)

The P90 latency observed for hourly_aggs query has regressed over the last weekk

### Related component

Search:Aggregations

### Expected behavior

Latency should not increase

**Comment by mgodwan** [comment] 2024-04-23 08:42
Tagging @getsaurabh02 @msfroh @bbarani to see if they may be aware of any changes. In parallel, looking through the commit history to see if I can find some commit which could've cause this.

**Comment by mgodwan** [comment] 2024-04-23 09:02
One of the commits (on the same day when regression started) which touch aggregation path slightly: https://github.com/opensearch-project/OpenSearch/commit/8332859ff28c9cd03e468cbd0e7b97092fd795ee [Can be evaluated if this could have had some impact]

**Comment by getsaurabh02** [comment] 2024-04-23 14:55
@mgodwan This looks related to the https://github.com/opensearch-project/OpenSearch/pull/13179 where @bowenlan-amzn has added cluster setting to dynamically disable filter rewrite optimization.

Based on the description it reduces the deciding threshold for rewrite filters from 1024 to 24. Meaning if the date histogram aggregation include more than 24 buckets (e.g. hourly aggregation of 1 day), we won't use the optimization After this change, we will probably see regression for date_histogram_hourly_agg of big5 workload. That will be handled after the long term solution merged in next.

**Comment by bowenlan-amzn** [comment] 2024-04-23 15:19
The change causing this is adding a dynamic cluster setting to decrease the threshold of apply our optimization on date histogram. The threshold is the number of filters rewritten from date histogram. Previous 1024 is reported to causing regression on pmc workload.

Since it's a dynamic setting, it won't actually cause regression for users and instead giving them ability to tune for their workload.

**Comment by mgodwan** [comment] 2024-04-24 04:40
Thanks @bowenlan-amzn 

> Since it's a dynamic setting, it won't actually cause regression for users and instead giving them ability to tune for their workload.

Is this setting enabled for the benchmark setup where we are seeing regression?

**Comment by lanbowen23** [comment] 2024-04-24 15:09
The setting is a threshold. This operation of http workload currently exceed the threshold so our previous optimization is disabled, hence the regression.

**Comment by peternied** [comment] 2024-04-24 15:18
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/vikasvb90) [4](https://github.com/mch2) [5](https://github.com/jed326) [6](https://github.com/dbwiddis)]
@mgodwan Thanks for creating this issue.  This looks like a potential release blocking for v2.14.  Please let me know if you need any help getting eyes on this issue.

**Comment by mgodwan** [comment] 2024-04-29 05:19
> The setting is a threshold. This operation of http workload currently exceed the threshold so our previous optimization is disabled, hence the regression.

@bowenlan-amzn Do we need to revisit the threshold defaults in that case as the current ones have shown to cause regression?

**Comment by bowenlan-amzn** [comment] 2024-05-03 05:45
Fix/Improvements merged in

**Closed by bowenlan-amzn** 2024-05-03 05:45 UTC
Labels: bug, Search:Aggregations, Performance, engine performance, Search:Performance, v2.14.0
