### ISSUE TITLE
sql "track_total_hits": true setting  Lose Efficacy

### ISSUE THREAD

**Issue by binbinjianjian** [opensearch-project/OpenSearch#2366] opened 2022-03-05 17:13 UTC
POST /_plugins/_sql?format=json
{
  "query": "SELECT  * FROM logstash-java-* WHERE MATCH_PHRASE(message, 'ERROR') ",
  "track_total_hits": true
}

{
  "took" : 19,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    }

**Comment by dblock** [comment] 2022-03-07 16:54
@binbinjianjian care to explain what you're trying to do and what the issue is?

**Comment by kavilla** [comment] 2022-03-08 08:03
Probably something similar to this https://github.com/opensearch-project/OpenSearch/issues/2093.

Where although they are passing `track_total_hits` the results show total hits being `10000` even though there should be more hits.

**Comment by anasalkouz** [comment] 2022-03-08 19:35
Closing this, since we are tracking this as feature enhancement on https://github.com/opensearch-project/OpenSearch/issues/2093. Feel free to reopen if you have more questions or concerns.

**Closed by anasalkouz** 2022-03-08 19:35 UTC
Labels: enhancement, untriaged

**Comment by binbinjianjian** [comment] 2022-03-09 06:15
> @binbinjianjian care to explain what you're trying to do and what the issue is?

i  know hit How much data
