### ISSUE TITLE
[BUG] _cat/nodes "segments.memory": "0b"

### ISSUE THREAD

**Issue by artemus717** [opensearch-project/OpenSearch#13852] opened 2024-05-28 07:57 UTC
### Describe the bug

_cat/nodes?h=name,*heap*,*memory*,*Cache*&format=json

[
    {
        "name": "node-hot-04",
        "heap.current": "37.8gb",
        "heap.percent": "59",
        "heap.max": "64gb",
        "fielddata.memory_size": "513.8mb",
        "query_cache.memory_size": "110.6mb",
        "request_cache.memory_size": "643.7mb",
        "segments.memory": "0b",
        "segments.index_writer_memory": "326.5mb",
        "segments.version_map_memory": "11mb",
        "segments.fixed_bitset_memory": "1.2kb",
        "query_cache.evictions": "581379",
        "query_cache.hit_count": "1809845",
        "query_cache.miss_count": "60305497",
        "request_cache.evictions": "386218",
        "request_cache.hit_count": "829303",
        "request_cache.miss_count": "1061657",
        "script.cache_evictions": "584",
        "script.compilation_limit_triggered": "0"
    }

 "segments.memory": "0b"  

No idea, if segments.memory is designed to display 0b or this is a bug.

### Related component

Other

### To Reproduce

_cat/nodes?h=name,*heap*,*memory*,*Cache*&format=json

### Expected behavior

segments.memory response true segments memory statistic.

### Additional Details

OpenSearch 2.14.0

**Comment by peternied** [comment] 2024-05-29 15:16
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/lukas-vlcek/) [5](https://github.com/dbwiddis) [6](https://github.com/srikanthpadakanti/)
@artemus717 Thanks for creating this issue, we'd welcome a pull request to address this issue.

**Comment by msfroh** [comment] 2024-07-31 17:54
> No idea, if segments.memory is designed to display 0b or this is a bug.

If I recall correctly, Lucene stopped tracking heap usage for segment-level data structures, mostly because it's very close to 0 these days (as everything is memory-mapped and off-heap).

We stopped populating the stat in OpenSearch 2.0 (the first version to use Lucene 9), but continue to include it in node stats for backward compatibility: https://github.com/opensearch-project/OpenSearch/pull/2029

**Comment by msfroh** [comment] 2024-07-31 17:55
I'm going to close this as "not a bug", but rather a known, intentional change.

Please feel free to comment/reopen if you disagree!

**Closed by msfroh** 2024-07-31 17:55 UTC
Labels: bug, Indexing, Cluster Manager, Other
