### ISSUE TITLE
[BUG] RemoteRestoreSnapshotIT.testRestoreInSameRemoteStoreEnabledIndex is Flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#9326] opened 2023-08-14 23:01 UTC
https://build.ci.opensearch.org/job/gradle-check/22710/testReport/org.opensearch.remotestore/RemoteRestoreSnapshotIT/testRestoreInSameRemoteStoreEnabledIndex/

**Comment by andrross** [comment] 2023-08-15 01:08
At least two failures of this test in #9083

**Comment by sachinpkale** [comment] 2023-09-06 12:20
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/9116

**Closed by sachinpkale** 2023-09-06 12:20 UTC
Labels: bug, distributed framework, flaky-test
