### ISSUE TITLE
[BUG] :test:fixtures:minio-fixture:composeUp Docker-compose test intermittently fails.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#1274] opened 2021-09-22 17:55 UTC
This test intermittently fails on gradle check running docker-compose up.

Gradle check runs:

[gradle_check_536.log](https://github.com/opensearch-project/OpenSearch/files/7212800/gradle_check_536.log)
[gradle_check_536_reports.zip](https://github.com/opensearch-project/OpenSearch/files/7212801/gradle_check_536_reports.zip)
```
> Task :test:fixtures:minio-fixture:composeUp

ERROR: for 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture-for-snapshot-tool_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture-other_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Creating 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture_1                   ... done

ERROR: for minio-fixture-for-snapshot-tool  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for minio-fixture-other  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Stopping 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture_1 ... 
```

**Comment by andrross** [comment] 2022-01-10 23:37
I believe this is a duplicate of #1806 so it should be fixed by #1866 

I'm going to close this but we can reopen if it happens again.

**Closed by andrross** 2022-01-10 23:37 UTC
Labels: bug, Build Libraries & Interfaces, Priority-Medium
