### ISSUE TITLE
[BUG][Flaky Test] org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs

### ISSUE THREAD

**Issue by ticheng-aws** [opensearch-project/OpenSearch#11149] opened 2023-11-09 21:34 UTC
**Describe the bug**
URL: https://build.ci.opensearch.org/job/gradle-check/29779/

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs" -Dtests.seed=1C7FDC2BEF76D934 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=cs -Dtests.timezone=Australia/West -Druntime.java=21
```
```
org.opensearch.remotestore.RemoteStoreStatsIT > testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([1C7FDC2BEF76D934:D18809F7A9690EF2]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs$16(RemoteStoreStatsIT.java:586)
        at java.****/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.****/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs$17(RemoteStoreStatsIT.java:582)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1089)
        at org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs(RemoteStoreStatsIT.java:576)


```

**Expected behavior**
The test should always pass.

**Comment by reta** [comment] 2023-11-23 17:13
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/10983

**Closed by reta** 2023-11-23 17:13 UTC
Labels: bug, untriaged, flaky-test
