### ISSUE TITLE
[BUG] node drop on o.o.cluster.routing.allocation.decider.MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1907] opened 2022-01-14 17:46 UTC
**Describe the bug**
Caught on PR #1902 . Another failure that can't be reproduced! (╯°□°)╯︵ ┻━┻

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark" -Dtests.seed=994DB46D3A71E388 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pt -Dtests.timezone=Asia/Tel_Aviv -Druntime.java=17
```

Looks like a node timeout issue at [MockDiskUsagesIT.java#L166](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/MockDiskUsagesIT.java#L166)

```
1> [2022-01-14T19:03:26,620][WARN ][o.o.c.NodeConnectionsService] [node_t1] failed to connect to {node_t0}{C3fT4Fp9SjmjuepSij5_0Q}{IqnPkDZ7TZu52WOm_HWKOA}{127.0.0.1}{127.0.0.1:43583}{dimr}{shard_indexing_pressure_enabled=true} (tried [1] times)
  1> org.opensearch.transport.ConnectTransportException: [node_t0][127.0.0.1:43583] connect_exception
```

Gave up after one try... valiant effort （。々°）

**To Reproduce**
Another failure that can't be reproduced! (╯°□°)╯︵ ┻━┻

**Expected behavior**
No node drops...happy WIFi happy LIFi

**Plugins**
All core opensearch

**Screenshots**

**Host/Environment (please complete the following information):**
 - PR #1902

**Additional context**

relates #1715

**Comment by ankitkala** [comment] 2023-12-05 06:22
Not able to reproduce even after 20K iterations. 
Given the issue was very generic(node timeout) & not specific to the test, resolving this as one-off case.

**Closed by ankitkala** 2023-12-05 06:22 UTC
Labels: >test-failure, flaky-test
