### ISSUE TITLE
[BUG][Segment Replication] Stuck Initializing Shard w/ Segment Replication enabled

### ISSUE THREAD

**Issue by mattweber** [opensearch-project/OpenSearch#6084] opened 2023-01-30 17:40 UTC
**Describe the bug**
I have recently enabled segment replication on an OpenSearch 2.5.0 cluster and ran into a stuck initializing shard somehow.  The only thing different on this cluster is 2.5.0 upgrade + enabling segment replication.  I am leaning toward being related to the segment replication since it is experimental.

**To Reproduce**
I have not been able to reproduce, not sure how it even happened in first place.

**Expected behavior**
Shards initialize and finish

**Additional context**
I didn't see anything suspicious in the logs and issue was easy to resolve using the shard reroute api.

**Comment by reta** [comment] 2023-01-30 17:52
@mattweber could it be related to this bug [1]? do you have any exceptions in the log to pinpoint the issue?

[1] https://github.com/opensearch-project/OpenSearch/issues/570

**Comment by dreamer-89** [comment] 2023-01-30 17:58
Thank you @mattweber for reporting this. I have also seen this error once while working on #5898 where replica shard remained `INITIALIZING` and never caught up with primary. Performing`_refresh` and `_flush` also did not change the state. I did not cut issue as I couldn't repro the issue. I faced this on 3 data node, 1 master node cluster setup with 1 shard, 1 repilca for only index I created.

**Comment by mattweber** [comment] 2023-01-30 18:01
@reta maybe, I will go dig though the logs again and see what I find.  Its a little rough as I have 48 nodes and not shipping logs in this environment.

@dreamer-89 yes I debated even opening this as well and decided just in case someone else might have hit it and have more info.  Looks like that was a good call.  You can resolve it using the cluster reroute api w/ cancel + allocate_replica commands.

My particular index was 24 shards, 1 replica and only a single replica ran into this issue.

**Comment by dreamer-89** [comment] 2023-03-06 19:57
Looking into it.

**Comment by dreamer-89** [comment] 2023-03-07 19:06
Not able to reproduce this with following. 
1. Integ test. Created integration test to mimic the setup with large number of primaries and node restarts. [Code link](https://github.com/dreamer-89/OpenSearch/blob/stuck_init/server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java#L139)
2. Manual experiment. Perform node stops during data ingestion. Used `nyc_taxis` workload from `OpenSearch--Benchmark` to perform data ingestion. Using 3 cluster-manager nodes, 3 data nodes setup which was used previously.

**Comment by dreamer-89** [comment] 2023-03-07 19:37
Able to repro the issue on older `2.x` branch (containing commits upto [Jan 30](https://github.com/dreamer-89/OpenSearch/commits/2.x_reverts) around timeline when this issue was reported). We recently had few critical changes (listed below) I believe solved the issue.
1. Skip performOnPrimary step when executing PublishCheckpoint https://github.com/opensearch-project/OpenSearch/commit/4bb8d246c8132d7323f3a44ed7cf8861fc34d9f1
2. Update replicationCheckpoint to include accurate seqNo from SegmentInfos https://github.com/opensearch-project/OpenSearch/commit/bd6484a2018ba17bb6ea6c4c542c9eec79da5257

#### On Failure
On cluster-manager node, I see shard failure warning for stuck shard `[nyc_taxis][14]`, as it is already replicating. This happens when source node receives a `get_checkpoint_info` from target and registers a new `RemoteSegmentFileChunkWriter`. It [fails](https://github.com/dreamer-89/OpenSearch/blob/2.x_reverts/server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java#L140) when there is already a `RemoteSegmentFileChunkWriter` corresponding to an allocationId. This could happen when there replica sends another `get_checkpoint_info` while replication is on-going or when primary fails to clear up this state.
```
[2023-03-07T18:40:05,093][WARN ][o.o.c.r.a.AllocationService] [seed] failing shard [failed shard, shard [nyc_taxis][14], node[gG95UUzJTfiBg9AXRb-OAQ], [R], s[STARTED], a[id=RMdc-ofaRs-0-SX1nyZedg], message [shard failure, reason [replication failure]], failure [OpenSearchException[Segment Replication failed]; nested: RemoteTransportException[[ip-10-0-4-214.us-west-2.compute.internal][10.0.4.214:9300][internal:index/shard/replication/get_checkpoint_info]]; nested: OpenSearchException[Shard copy [nyc_taxis][14] on node {ip-10-0-3-212.us-west-2.compute.internal}{gG95UUzJTfiBg9AXRb-OAQ}{GFGDoa4bSCS1c1ccBx5zvg}{10.0.3.212}{10.0.3.212:9300}{di}{shard_indexing_pressure_enabled=true} already replicating]; ], markAsStale [true]]
org.opensearch.OpenSearchException: Segment Replication failed
        at org.opensearch.indices.replication.SegmentReplicationTargetService$3.onFailure(SegmentReplicationTargetService.java:302) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) ~[opensearch-2.6.0.jar:2.6.0]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.BaseFuture.setException(BaseFuture.java:178) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.ListenableFuture.onFailure(ListenableFuture.java:149) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.StepListener.innerOnFailure(StepListener.java:82) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.NotifyOnceListener.onFailure(NotifyOnceListener.java:62) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.ActionListener$4.onFailure(ActionListener.java:190) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.ActionListener$6.onFailure(ActionListener.java:309) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.support.RetryableAction$RetryingListener.onFinalFailure(RetryableAction.java:218) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:210) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1414) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:420) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) ~[opensearch-2.6.0.jar:2.6.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.opensearch.transport.RemoteTransportException: [ip-10-0-4-214.us-west-2.compute.internal][10.0.4.214:9300][internal:index/shard/replication/get_checkpoint_info]
Caused by: org.opensearch.OpenSearchException: Shard copy [nyc_taxis][14] on node {ip-10-0-3-212.us-west-2.compute.internal}{gG95UUzJTfiBg9AXRb-OAQ}{GFGDoa4bSCS1c1ccBx5zvg}{10.0.3.212}{10.0.3.212:9300}{di}{shard_indexing_pressure_enabled=true} already replicating
        at org.opensearch.indices.replication.OngoingSegmentReplications.prepareForReplication(OngoingSegmentReplications.java:147) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.indices.replication.SegmentReplicationSourceService$CheckpointInfoRequestHandler.messageReceived(SegmentReplicationSourceService.java:134) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.indices.replication.SegmentReplicationSourceService$CheckpointInfoRequestHandler.messageReceived(SegmentReplicationSourceService.java:115) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.6.0.jar:2.6.0]
        ... 3 more
```

**Comment by dreamer-89** [comment] 2023-03-08 00:29
Resolving this issue as it is not repro'able on latest `2.x` and `main`.

**Comment by dreamer-89** [comment] 2023-03-13 19:52
Hit this bug today. Reopening.

**Comment by mch2** [comment] 2023-05-19 21:01
@dreamer-89 

From what you posted it looks like the recovery is still in progress in "translog" state.  For segrep replica recoveries the translog step will only write the ops to xlog.


```
➜  opensearch-cluster-cdk git:(inclusive_naming_changes) ✗ curl -s -X GET "$host/_cat/recovery?active_only=true&v=true" 
index     shard time type stage    source_host source_node                             target_host target_node                              repository snapshot files files_recovered files_percent files_total bytes     bytes_recovered bytes_percent bytes_total translog_ops translog_ops_recovered translog_ops_percent
nyc_taxis 22    5m   peer translog 10.0.5.39   ip-10-0-5-39.us-west-2.compute.internal 10.0.4.133  ip-10-0-4-133.us-west-2.compute.internal n/a        n/a      70    70              100.0%        70          105104077 105104077       100.0%        105104077   492100       492100                 100.0%
```

I haven't hit this bug where a replica *never* finishes recovery, but I think we have a bug here in that we are attempting to copy more xlog ops where necessary, slowing recovery.  The startingSeqNo is always sent as -2 (UNASSIGNED_SEQ_NO) when starting recovery with SR.  This triggers a file based recovery and uses the local cp of the safe commit as the starting point of ops to recover.  This means even if the replica has those ops already in its xlog they will get sent.  I think we can optimize this and use the global cp stored in the local xlog on the replica as the starting point.  After ops are sent over we still perform a round of segrep to catch up from the safe commit.

**Comment by mch2** [comment] 2023-06-06 23:57
Closing this as not reproducible, please re-open if this happens with OS 2.7+.

**Closed by mch2** 2023-06-06 23:57 UTC
Labels: bug, distributed framework
