### ISSUE TITLE
[Segment Replication + Remote Store] DocRep (without Remote Store) or  Index level override should not be allowed to enable Remote store

### ISSUE THREAD

**Issue by nandi-github** [opensearch-project/OpenSearch#8499] opened 2023-07-06 17:30 UTC
When the cluster is configured with **DocRep (without RemoteStore)** — configuration change should prevent user from enabling remote store.

**Describe the solution you'd like**
Upon detecting that the user is trying to enable remote store on a cluster with **DocRep Cluster**, the config should fail and keep the original configuration. The user should be notified of the failure and a proper error message with details should be provided.

Example error message : "Enabling Remote Store on clusters with DocRep is not allowed"

**Additional context**

**Comment by dreamer-89** [comment] 2023-07-06 21:40
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/8497. Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/8497

**Closed by dreamer-89** 2023-07-06 21:40 UTC
Labels: enhancement, distributed framework
