### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards is flaky 

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#10708] opened 2023-10-18 16:21 UTC
**Describe the bug**

https://github.com/opensearch-project/OpenSearch/pull/10695 

https://build.ci.opensearch.org/job/gradle-check/28270/testReport/junit/org.opensearch.remotestore/RemoteStoreStatsIT/testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards/

https://build.ci.opensearch.org/job/gradle-check/26576/

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards" -Dtests.seed=21F83F3B31962790 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=de -Dtests.timezone=Australia/Broken_Hill -Druntime.java=17
```

**Comment by reta** [comment] 2023-10-31 01:04
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/10152

**Closed by reta** 2023-10-31 01:04 UTC
Labels: bug, untriaged, flaky-test
