### ISSUE TITLE
[BUG]  org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=nodes.stats/20_response_filtering/Nodes Stats filtered using both includes and excludes filters} is flaky

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#10032] opened 2023-09-13 20:07 UTC
**Describe the bug**
`org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=nodes.stats/20_response_filtering/Nodes Stats filtered using both includes and excludes filters}` is flaky

**To Reproduce**
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v2.11.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=nodes.stats/11_indices_metrics/Metric - blank}" -Dtests.seed=2F3DFE87E8073580 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-Hans-CN -Dtests.timezone=Asia/Tbilisi -Druntime.java=20

**Expected behavior**
Test to pass

**Screenshots**

```
java.lang.AssertionError: Failure at [nodes.stats/20_response_filtering:173]: field [nodes.$node_id.name] doesn't have a true value
Expected: not null
     but: was null
```

**Host/Environment (please complete the following information):**
Jenkins CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/25505/testReport/
- https://build.ci.opensearch.org/job/gradle-check/25494

**Comment by msfroh** [comment] 2023-09-13 20:18
Taking a look -- not sure that this one is "flaky", since it seems to be failing pretty consistently. Checking to see if something legitimately broke.

**Comment by msfroh** [comment] 2023-09-13 20:41
May have been fixed by https://github.com/opensearch-project/OpenSearch/commit/91821c79e3d1eb562a3829818cf397e328b84344 ?

**Comment by msfroh** [comment] 2023-09-13 20:47
Yeah -- I tried to reproduce a bunch of times on my machine but wasn't able to.

I locally reverted https://github.com/opensearch-project/OpenSearch/commit/91821c79e3d1eb562a3829818cf397e328b84344, and I was able to reproduce the failure on my second attempt.

I think we can safely say that https://github.com/opensearch-project/OpenSearch/commit/91821c79e3d1eb562a3829818cf397e328b84344 fixed this.

**Closed by msfroh** 2023-09-13 20:47 UTC
Labels: bug, flaky-test
