### ISSUE TITLE
[BUG] Opensearch repository-s3 plugin cannot read ServiceAccount token

### ISSUE THREAD

**Issue by DimitrisChristinakis** [opensearch-project/OpenSearch#6312] opened 2023-02-14 08:22 UTC
**Describe the bug**
I am running an Opensearch cluster using Opensearch Operator in AWS EKS. I have created a ServiceAccount in order to access an AWS S3 bucket to use for my snapshot but i get the following error:

"reason" : "amazon_client_exception: java.security.AccessControlException: access denied (\"java.io.FilePermission\" \"/var/run/secrets/eks.amazonaws.com/serviceaccount/token\" \"read\")",
"caused_by" : {
"type" : "security_exception",
"reason" : "access denied (\"java.io.FilePermission\" \"/var/run/secrets/eks.amazonaws.com/serviceaccount/token\" \"read\")"

The token has the following permissions:
lrwxrwxrwx 1 root root 12 Feb 13 18:21 /var/run/secrets/eks.amazonaws.com/serviceaccount/token -> ..data/token

If i copy this token under the plugin's directory it works normally:
/usr/share/opensearch/plugins/repository-s3/token

**To Reproduce**
1. Deploy an Opensearch cluster (image version 2.5.0) with repository-s3 plugin installed
2. Configure a Kubernetes service account to assume an IAM role
3. Configure s3.client.default.identity_token_file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token

**Expected behavior**
The plugin should be able to read the token

**Plugins**
repository-s3 plugin

**Host/Environment (please complete the following information):**
 - AWS EKS version 1.21
 - Opensearch cluster (image version 2.5.0) deployed with Opensearch Operator (version 2.2.0)

**Comment by annasunny** [comment] 2023-02-15 22:07
I'm having the same issue.

**Comment by reta** [comment] 2023-02-15 22:17
@DimitrisChristinakis @annasunny this is covered in documentation [1], the `SecurityManager` policy settings prevent `s3-repository` to access arbitrary locations on file system. 

[1] https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#take-snapshots

**Comment by annasunny** [comment] 2023-02-15 22:46
@reta Thank you Andriy! Could you help explain more on this:  Where is the" SecurityManager policy settings", and how I can change it?

**Comment by reta** [comment] 2023-02-15 23:09
Sure, the policy is located here `/usr/share/opensearch/plugins/repository-s3/plugin-security.policy`

**Comment by annasunny** [comment] 2023-02-15 23:59
Thank you @reta! However, I'm not seeing the ` permission java.io.FilePermission` from my `plugin-security.policy` file... 
Here is my `plugin-security.policy` file looks like, and I'm using `cat` command to open it: 
<img width="693" alt="Screen Shot 2023-02-15 at 3 58 31 PM" src="https://user-images.githubusercontent.com/5370146/219222586-2aa01832-38ed-4720-bdab-4e702a688e0d.png">
 

Instead, I'm running into another `[<my-s3-repository-name>] path [<my-s3-path>] is not accessible on cluster-manager node` error. Could you take another look? - https://github.com/opensearch-project/OpenSearch/issues/6332  Thank you in advance!

**Comment by reta** [comment] 2023-02-16 00:32
> Here is my plugin-security.policy file looks like, and I'm using cat command to open it:

That's correct, as I [mentioned](https://github.com/opensearch-project/OpenSearch/issues/6312#issuecomment-1432204711), you may need to add this line manually:

```
permission java.io.FilePermission "/var/run/secrets/eks.amazonaws.com/serviceaccount/token", "read";
```

**Comment by herrbpl** [comment] 2023-02-20 08:01
@reta This is still a problem because:
1. You cannot have files in path s3 plugin will be installed or installation will fail, which means you cannot really mount EKS service account token into accepted path. And you cannot preinstall plugin as it is installed on pod start.
2. You cannot change policy config file because of same reason as 1. 
This is a problem or if there is working solution, could it please documented fully, how to make it work?

My recommendation is to add EKS default token mount path to allowed files in policy, after all its AWS related product.  Or allow custom step between installing plugin and starting opensearch.

**Comment by reta** [comment] 2023-02-20 14:01
@herrbpl we do have a viable approach using soft links [1],  I will update the docs and plugin (if necessary), https://www.elastic.co/guide/en/elasticsearch/reference/8.6/repository-s3.html#iam-kubernetes-service-accounts

> My recommendation is to add EKS default token and Kubernetes default service account token mount path to allowed files in policy, after all its AWS related product. 

The OS plugins (at least core ones) should not access to anything outside it local installation folder.

**Comment by herrbpl** [comment] 2023-02-20 16:04
but how to solve issue that you cannot install plugin if target folder is not empty?

**Comment by reta** [comment] 2023-02-20 16:35
The conf folder is outside of the plugin target folder (it is controlled by `OPENSEARCH_PATH_CONF` env variable)

**Comment by annasunny** [comment] 2023-02-20 23:34
Hi @reta Andriy , After I link those two:
` ln -s $AWS_WEB_IDENTITY_TOKEN_FILE "${OPENSEARCH_PATH_CONFIG}/aws-web-identity-token-file"`
And refer it in opensearch.yml:
`s3.client.default.identity_token_file: aws-web-identity-token-file`
But I/m still seeing the same error - 
`Caused by: org.opensearch.common.io.stream.NotSerializableExceptionWrapper: amazon_client_exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/run/secrets/eks.amazonaws.com/serviceaccount/token" "read")`

Looks like the [symlink in Elastic community](https://www.elastic.co/guide/en/elasticsearch/reference/master/repository-s3.html#iam-kubernetes-service-accounts) won't fix for Opensearch. 
Please let me know if anyone else are able to use symlink to make it working.

**Comment by reta** [comment] 2023-02-20 23:50
Hey @annasunny , 

You need a full path here (afaik the OPENSEARCH_PATH_CONFIG won't be expanded in `opensearch.yml`) at the moment:
```
 s3.client.default.identity_token_file: /full/path/to/aws-web-identity-token-file
```

I have submitted the fix to make the exact case you are trying to wok just fine (https://github.com/opensearch-project/OpenSearch/pull/6390), but it is not yet merged. With it:

```
 s3.client.default.identity_token_file: aws-web-identity-token-file
```

would work out of the box.

**Comment by DimitrisChristinakis** [comment] 2023-02-21 08:22
Hi @reta , I am currently using [Opensearch Operator](https://github.com/Opster/opensearch-k8s-operator) to set up the cluster and I can verify that symlink works after adding it manually to every pod. Unfortunately I cannot find a way to automatically create the symlink or modify plugin-security.policy in order for this to work without modifying images, etc. I don't know if you have any ideas for this?

**Comment by reta** [comment] 2023-02-21 13:11
> Hi @reta , I am currently using [Opensearch Operator](https://github.com/Opster/opensearch-k8s-operator) to set up the cluster and I can verify that symlink works after adding it manually to every pod. Unfortunately I cannot find a way to automatically create the symlink or modify plugin-security.policy in order for this to work without modifying images, etc. I don't know if you have any ideas for this?

Thanks for confirming @DimitrisChristinakis , the modification of the `plugin-security.policy` should not be needed once we get https://github.com/opensearch-project/OpenSearch/pull/6390 in, but I sadly don't know how to instruct the [Opensearch Operator](https://github.com/Opster/opensearch-k8s-operator) to create the symlinks, you may ask the question there.

**Closed** 2023-02-21 20:15 UTC
Labels: bug, Build Libraries & Interfaces
