### ISSUE TITLE
[TEST] Failures in IndexingMemoryControllerTests

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#39] opened 2021-02-03 22:13 UTC
Couple of tests failing in IndexingMemoryControllerTests.

- [ ] org.elasticsearch.indices.IndexingMemoryControllerTests.testSkipRefreshIfShardIsRefreshingAlready
- [x] org.elasticsearch.indices.IndexingMemoryControllerTests.testTranslogRecoveryWorksWithIMC

Reproduced by `./gradlew ':server:test'`

**Comment by owaiskazi19** [comment] 2022-01-05 19:12
Got this issue on the recent GHA run: https://github.com/opensearch-project/OpenSearch/runs/4718277102?check_suite_focus=true for the PR: https://github.com/opensearch-project/OpenSearch/pull/1665. Reopening the issue.

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.IndexingMemoryControllerTests.testSkipRefreshIfShardIsRefreshingAlready" -Dtests.seed=EFEC06DDA82AA01 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CL -Dtests.timezone=America/Santa_Isabel -Druntime.java=17
> Task :server:test

org.opensearch.indices.IndexingMemoryControllerTests > testSkipRefreshIfShardIsRefreshingAlready FAILED
    java.lang.AssertionError: 
    Expected: <91L>
         but: was <0L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.indices.IndexingMemoryControllerTests.lambda$testSkipRefreshIfShardIsRefreshingAlready$6(IndexingMemoryControllerTests.java:490)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1060)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1033)
        at org.opensearch.indices.IndexingMemoryControllerTests.testSkipRefreshIfShardIsRefreshingAlready(IndexingMemoryControllerTests.java:488)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=18872, name=opensearch[org.opensearch.indices.IndexingMemoryControllerTests][refresh][T#1], state=RUNNABLE, group=TGRP-IndexingMemoryControllerTests]

        Caused by:
        java.lang.AssertionError: java.lang.InterruptedException
            at __randomizedtesting.SeedInfo.seed([EFEC06DDA82AA01]:0)
            at org.opensearch.indices.IndexingMemoryControllerTests$2.beforeRefresh(IndexingMemoryControllerTests.java:448)

            Caused by:
            java.lang.InterruptedException
                at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
                at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
                at org.opensearch.indices.IndexingMemoryControllerTests$2.beforeRefresh(IndexingMemoryControllerTests.java:446)

  1> [2022-01-05T10:17:35,025][INFO ][o.o.i.IndexingMemoryControllerTests] [testTranslogRecoveryWorksWithIMC] before test

**Comment by Poojita-Raj** [comment] 2022-12-06 16:27
The failure org.elasticsearch.indices.IndexingMemoryControllerTests.testSkipRefreshIfShardIsRefreshingAlready is also seen on windows machines.

**Comment by andrross** [comment] 2024-02-21 20:57
No references in over a year. Resolving.

**Closed by andrross** 2024-02-21 20:57 UTC
Labels: >test-failure, Indexing & Search, flaky-test
