### ISSUE TITLE
[BUG] CreateRemoteIndexClusterDefaultDocRepIT.testDefaultRemoteStoreNoUserOverrideExceptReplicationTypeSegment is flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#11581] opened 2023-12-11 22:23 UTC
**Describe the bug**
From https://build.ci.opensearch.org/job/gradle-check/31138/
PR: https://github.com/opensearch-project/OpenSearch/pull/11534

**Comment by linuxpi** [comment] 2024-01-17 05:44
Not able to repro failure in 2500 iterations.

**Comment by linuxpi** [comment] 2024-02-02 06:11
closing this due to lack of occurrence and repro. Please reopen if you find any failures

**Comment by reta** [comment] 2024-02-14 14:14
The issue is not gone:
 - https://build.ci.opensearch.org/job/gradle-check/33717/testReport/junit/org.opensearch.remotestore/CreateRemoteIndexClusterDefaultDocRepIT/testDefaultRemoteStoreNoUserOverrideExceptReplicationTypeSegment/

**Comment by linuxpi** [comment] 2024-02-19 11:02
Thanks @reta for reporting this. I need to think a bit more on how to repro this, the build logs are not enough to debug

**Comment by linuxpi** [comment] 2024-05-07 07:04
Looks like an issue while test tearDown

```
java.lang.AssertionError: shard [test-idx-1][0] is not locked
	at __randomizedtesting.SeedInfo.seed([37532D70A3B76622]:0)
	at org.opensearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:587)
	at org.opensearch.indices.IndicesService.deleteShardStore(IndicesService.java:1231)
	at org.opensearch.index.IndexService.onShardClose(IndexService.java:678)
	at org.opensearch.index.IndexService$StoreCloseListener.accept(IndexService.java:801)
	at org.opensearch.index.IndexService$StoreCloseListener.accept(IndexService.java:788)
	at org.opensearch.index.store.Store.closeInternal(Store.java:573)
	at org.opensearch.index.store.Store$1.closeInternal(Store.java:194)
	at org.opensearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:78)
	at org.opensearch.index.store.Store.decRef(Store.java:546)
	at org.opensearch.index.engine.InternalEngine.refresh(InternalEngine.java:1777)
	at org.opensearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:1753)
	at org.opensearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:4498)
	at org.opensearch.index.IndexService.maybeRefreshEngine(IndexService.java:1026)
	at org.opensearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1170)
	at org.opensearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:159)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by reta** [comment] 2024-06-19 15:31
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14381

**Closed by reta** 2024-06-19 15:31 UTC
Labels: bug, flaky-test, Storage, Storage:Remote

**Comment by linuxpi** [comment] 2024-07-01 04:42
Should be fixed by https://github.com/opensearch-project/OpenSearch/pull/14601/files
