### ISSUE TITLE
[BUG] Test case org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"/"false"}} is flaky

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#13792] opened 2024-05-23 05:26 UTC
### Describe the bug

All the variants of this test case seems to be flaky. This issue is for tracking the failure with different values of parameter `opensearch.experimental.feature.pluggable.caching.enabled` i.e. `true/false`

#### Case 1: `org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}`

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([2A675DA2FBD13DF8:14D5C9A2918EC51F]:0)
	at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
	at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1128)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1101)
	at org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode(IndicesRequestCacheIT.java:1282)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
```

#### Case 2: `org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"false"}}`

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([2A675DA2FBD13DF8:14D5C9A2918EC51F]:0)
	at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
	at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1128)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1101)
	at org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode(IndicesRequestCacheIT.java:1282)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1317)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$12(IndicesRequestCacheIT.java:1283)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
```

### Related component

Search

#### Case 1:
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.IndicesRequestCacheIT" -Dtests.method="testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}" -Dtests.seed=2A675DA2FBD13DF8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-AR -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=21
```

#### Case 2:
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.IndicesRequestCacheIT" -Dtests.method="testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"false"}}" -Dtests.seed=2A675DA2FBD13DF8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-AR -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=21
```

### Expected behavior

Test should always pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
CI

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/39104/

**Comment by sgup432** [comment] 2024-05-23 18:42
@sohami We already have an issue for this - https://github.com/opensearch-project/OpenSearch/issues/13600
I will take a look. So probably you can close this one out?

**Comment by reta** [comment] 2024-05-24 16:05
Duplicate of https://github.com/opensearch-project/OpenSearch/issues/13600

**Closed by reta** 2024-05-24 16:05 UTC
Labels: bug, flaky-test, Search
